# coding: utf-8

"""
    Database Repository Identifier Service API

    Service that manages the identifiers  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IdentifierCreateDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'qid': 'int',
        'title': 'str',
        'description': 'str',
        'visibility': 'str',
        'doi': 'str',
        'creators': 'list[CreatorCreateDto]',
        'publication_day': 'int',
        'publication_month': 'int',
        'publication_year': 'int',
        'related_identifiers': 'list[RelatedIdentifierCreateDto]'
    }

    attribute_map = {
        'qid': 'qid',
        'title': 'title',
        'description': 'description',
        'visibility': 'visibility',
        'doi': 'doi',
        'creators': 'creators',
        'publication_day': 'publication_day',
        'publication_month': 'publication_month',
        'publication_year': 'publication_year',
        'related_identifiers': 'related_identifiers'
    }

    def __init__(self, qid=None, title=None, description=None, visibility=None, doi=None, creators=None, publication_day=None, publication_month=None, publication_year=None, related_identifiers=None):  # noqa: E501
        """IdentifierCreateDto - a model defined in Swagger"""  # noqa: E501
        self._qid = None
        self._title = None
        self._description = None
        self._visibility = None
        self._doi = None
        self._creators = None
        self._publication_day = None
        self._publication_month = None
        self._publication_year = None
        self._related_identifiers = None
        self.discriminator = None
        self.qid = qid
        self.title = title
        self.description = description
        self.visibility = visibility
        if doi is not None:
            self.doi = doi
        self.creators = creators
        if publication_day is not None:
            self.publication_day = publication_day
        if publication_month is not None:
            self.publication_month = publication_month
        self.publication_year = publication_year
        if related_identifiers is not None:
            self.related_identifiers = related_identifiers

    @property
    def qid(self):
        """Gets the qid of this IdentifierCreateDto.  # noqa: E501


        :return: The qid of this IdentifierCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._qid

    @qid.setter
    def qid(self, qid):
        """Sets the qid of this IdentifierCreateDto.


        :param qid: The qid of this IdentifierCreateDto.  # noqa: E501
        :type: int
        """
        if qid is None:
            raise ValueError("Invalid value for `qid`, must not be `None`")  # noqa: E501

        self._qid = qid

    @property
    def title(self):
        """Gets the title of this IdentifierCreateDto.  # noqa: E501


        :return: The title of this IdentifierCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this IdentifierCreateDto.


        :param title: The title of this IdentifierCreateDto.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self):
        """Gets the description of this IdentifierCreateDto.  # noqa: E501


        :return: The description of this IdentifierCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this IdentifierCreateDto.


        :param description: The description of this IdentifierCreateDto.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def visibility(self):
        """Gets the visibility of this IdentifierCreateDto.  # noqa: E501


        :return: The visibility of this IdentifierCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility):
        """Sets the visibility of this IdentifierCreateDto.


        :param visibility: The visibility of this IdentifierCreateDto.  # noqa: E501
        :type: str
        """
        if visibility is None:
            raise ValueError("Invalid value for `visibility`, must not be `None`")  # noqa: E501
        allowed_values = ["everyone", "trusted", "self"]  # noqa: E501
        if visibility not in allowed_values:
            raise ValueError(
                "Invalid value for `visibility` ({0}), must be one of {1}"  # noqa: E501
                .format(visibility, allowed_values)
            )

        self._visibility = visibility

    @property
    def doi(self):
        """Gets the doi of this IdentifierCreateDto.  # noqa: E501


        :return: The doi of this IdentifierCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._doi

    @doi.setter
    def doi(self, doi):
        """Sets the doi of this IdentifierCreateDto.


        :param doi: The doi of this IdentifierCreateDto.  # noqa: E501
        :type: str
        """

        self._doi = doi

    @property
    def creators(self):
        """Gets the creators of this IdentifierCreateDto.  # noqa: E501


        :return: The creators of this IdentifierCreateDto.  # noqa: E501
        :rtype: list[CreatorCreateDto]
        """
        return self._creators

    @creators.setter
    def creators(self, creators):
        """Sets the creators of this IdentifierCreateDto.


        :param creators: The creators of this IdentifierCreateDto.  # noqa: E501
        :type: list[CreatorCreateDto]
        """
        if creators is None:
            raise ValueError("Invalid value for `creators`, must not be `None`")  # noqa: E501

        self._creators = creators

    @property
    def publication_day(self):
        """Gets the publication_day of this IdentifierCreateDto.  # noqa: E501


        :return: The publication_day of this IdentifierCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._publication_day

    @publication_day.setter
    def publication_day(self, publication_day):
        """Sets the publication_day of this IdentifierCreateDto.


        :param publication_day: The publication_day of this IdentifierCreateDto.  # noqa: E501
        :type: int
        """

        self._publication_day = publication_day

    @property
    def publication_month(self):
        """Gets the publication_month of this IdentifierCreateDto.  # noqa: E501


        :return: The publication_month of this IdentifierCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._publication_month

    @publication_month.setter
    def publication_month(self, publication_month):
        """Sets the publication_month of this IdentifierCreateDto.


        :param publication_month: The publication_month of this IdentifierCreateDto.  # noqa: E501
        :type: int
        """

        self._publication_month = publication_month

    @property
    def publication_year(self):
        """Gets the publication_year of this IdentifierCreateDto.  # noqa: E501


        :return: The publication_year of this IdentifierCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._publication_year

    @publication_year.setter
    def publication_year(self, publication_year):
        """Sets the publication_year of this IdentifierCreateDto.


        :param publication_year: The publication_year of this IdentifierCreateDto.  # noqa: E501
        :type: int
        """
        if publication_year is None:
            raise ValueError("Invalid value for `publication_year`, must not be `None`")  # noqa: E501

        self._publication_year = publication_year

    @property
    def related_identifiers(self):
        """Gets the related_identifiers of this IdentifierCreateDto.  # noqa: E501


        :return: The related_identifiers of this IdentifierCreateDto.  # noqa: E501
        :rtype: list[RelatedIdentifierCreateDto]
        """
        return self._related_identifiers

    @related_identifiers.setter
    def related_identifiers(self, related_identifiers):
        """Sets the related_identifiers of this IdentifierCreateDto.


        :param related_identifiers: The related_identifiers of this IdentifierCreateDto.  # noqa: E501
        :type: list[RelatedIdentifierCreateDto]
        """

        self._related_identifiers = related_identifiers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IdentifierCreateDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdentifierCreateDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
