# coding: utf-8

"""
    units

    powered by Flasgger  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from api_units.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def api_units_savecolumnsconcept_post(self, body, **kwargs):  # noqa: E501
        """Save concepts to MDB  # noqa: E501

        This is a simple API for saving units and concepts.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_units_savecolumnsconcept_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param UnitsSavecolumnsconceptBody body: to-do description (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_units_savecolumnsconcept_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.api_units_savecolumnsconcept_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def api_units_savecolumnsconcept_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Save concepts to MDB  # noqa: E501

        This is a simple API for saving units and concepts.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_units_savecolumnsconcept_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param UnitsSavecolumnsconceptBody body: to-do description (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_units_savecolumnsconcept_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `api_units_savecolumnsconcept_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/units/savecolumnsconcept', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_units_saveconcept_post(self, body, **kwargs):  # noqa: E501
        """Save concepts to MDB  # noqa: E501

        This is a simple API for saving units and concepts.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_units_saveconcept_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param UnitsSaveconceptBody body: to-do description (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_units_saveconcept_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.api_units_saveconcept_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def api_units_saveconcept_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Save concepts to MDB  # noqa: E501

        This is a simple API for saving units and concepts.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_units_saveconcept_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param UnitsSaveconceptBody body: to-do description (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_units_saveconcept_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `api_units_saveconcept_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/units/saveconcept', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_units_suggest_post(self, body, **kwargs):  # noqa: E501
        """Autosuggest units  # noqa: E501

        This is a simple API which returns a list of suggested units.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_units_suggest_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param UnitsSuggestBody body: to-do description (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_units_suggest_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.api_units_suggest_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def api_units_suggest_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Autosuggest units  # noqa: E501

        This is a simple API which returns a list of suggested units.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_units_suggest_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param UnitsSuggestBody body: to-do description (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_units_suggest_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `api_units_suggest_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/units/suggest', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_units_uri_uname_get(self, uname, **kwargs):  # noqa: E501
        """Get URI of units  # noqa: E501

        This is a simple API for getting the URI of a certain unit in OM.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_units_uri_uname_get(uname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str uname: to-do description (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_units_uri_uname_get_with_http_info(uname, **kwargs)  # noqa: E501
        else:
            (data) = self.api_units_uri_uname_get_with_http_info(uname, **kwargs)  # noqa: E501
            return data

    def api_units_uri_uname_get_with_http_info(self, uname, **kwargs):  # noqa: E501
        """Get URI of units  # noqa: E501

        This is a simple API for getting the URI of a certain unit in OM.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_units_uri_uname_get_with_http_info(uname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str uname: to-do description (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['uname']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_units_uri_uname_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'uname' is set
        if ('uname' not in params or
                params['uname'] is None):
            raise ValueError("Missing the required parameter `uname` when calling `api_units_uri_uname_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'uname' in params:
            path_params['uname'] = params['uname']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/units/uri/{uname}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_units_validate_unit_get(self, unit, **kwargs):  # noqa: E501
        """Validate units  # noqa: E501

        This is a simple API for validating units.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_units_validate_unit_get(unit, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str unit: to-do description (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_units_validate_unit_get_with_http_info(unit, **kwargs)  # noqa: E501
        else:
            (data) = self.api_units_validate_unit_get_with_http_info(unit, **kwargs)  # noqa: E501
            return data

    def api_units_validate_unit_get_with_http_info(self, unit, **kwargs):  # noqa: E501
        """Validate units  # noqa: E501

        This is a simple API for validating units.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_units_validate_unit_get_with_http_info(unit, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str unit: to-do description (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['unit']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_units_validate_unit_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'unit' is set
        if ('unit' not in params or
                params['unit'] is None):
            raise ValueError("Missing the required parameter `unit` when calling `api_units_validate_unit_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'unit' in params:
            path_params['unit'] = params['unit']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/units/validate/{unit}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
