app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: "jdbc:mariadb://metadata-db:3306/${METADATA_DB}"
    driver-class-name: org.mariadb.jdbc.Driver
    username: "${METADATA_USERNAME}"
    password: "${METADATA_PASSWORD}"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: "${METADATA_DB}"
        jdbc:
          time_zone: UTC
  application:
    name: query-service
  rabbitmq:
    host: broker-service
    username: "${BROKER_USERNAME}"
    password: "${BROKER_PASSWORD}"
  cloud:
    loadbalancer.ribbon.enabled: false
management.endpoints.web.exposure.include: health,info,prometheus
server.port: 9093
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: "${LOG_LEVEL}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  instance.hostname: query-service
  client.serviceUrl.defaultZone: http://discovery-service:9090/eureka/
fda:
  gateway.endpoint: "${GATEWAY_ENDPOINT}"
  ready.path: /ready
  consumers: "${BROKER_CONSUMERS}"
  unsupported: "${NOT_SUPPORTED_KEYWORDS}"
  elastic:
    endpoint: search-service:9200
    username: elastic
    password: "${ELASTIC_PASSWORD}"
