<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>at.tuwien</groupId>
        <artifactId>dbrepo-data-service</artifactId>
        <version>1.7.0</version>
    </parent>

    <artifactId>rest-service</artifactId>
    <name>dbrepo-data-service-rest-service</name>
    <version>1.7.0</version>

    <dependencies>
        <dependency>
            <groupId>at.tuwien</groupId>
            <artifactId>services</artifactId>
            <version>1.7.0</version>
        </dependency>
    </dependencies>

    <properties>
        <jacoco.version>0.8.7</jacoco.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal><!-- to make it exuteable with $ java -jar ./app.jar -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>9</source>
                    <target>9</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>