#!/bin/bash
docker container stop $(docker container ls -aq -f name=^/fda-.*) || true
docker container rm $(docker container ls -aq -f name=^/fda-.*) || true
docker volume rm $(docker volume ls -q -f name=^fda-.*) || true
docker network rm $(docker network ls -q -f name=^/fda-.*) || true