{{- if .Values.dataService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: {{ .Values.namespace }}
  labels:
    app: data-service
    service: data-service
spec:
  replicas: {{ .Values.dataService.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: data-service
      service: data-service
  template:
    metadata:
      labels:
        app: data-service
        service: data-service
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: data-service
          image: {{ .Values.dataService.image.name }}
          imagePullPolicy: {{ .Values.dataService.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: {{ .Values.dataService.profileType | default "RuntimeDefault" }}
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 9093
              protocol: TCP
          env:
            - name: METADATA_DB
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: metadata-db
            - name: METADATA_HOST
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: metadata-host
            - name: METADATA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: metadata-username
            - name: METADATA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: metadata-password
            - name: METADATA_JDBC_EXTRA_ARGS
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: metadata-jdbc-extra-args
            - name: SEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: search-username
            - name: SEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: search-password
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: jwt-issuer
            - name: JWT_PUBKEY
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: jwt-pubkey
            - name: BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: broker-username
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: broker-password
            - name: MIN_CONCURRENT_CONSUMERS
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key:  min-concurrent-consumers
            - name: MAX_CONCURRENT_CONSUMERS
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key:  max-concurrent-consumers
            - name: REQUEUE_REJECTED
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: requeue-rejected
            - name: BROKER_HOST
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: broker-host
            - name: BROKER_PORT
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: broker-port
            - name: BROKER_VIRTUALHOST
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: broker-virtualhost
            - name: QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: queue-name
            - name: EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: exchange-name
            - name: ROUTING_KEY
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: routing-key
            - name: CONNECTION_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: connection-timeout
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: log-level
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:9093/actuator/health/readiness | grep 'UP' || exit 1"
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:9093/actuator/health/liveness | grep 'UP' || exit 1"
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts: []
      volumes: []
{{- end }}
