{{ $pidBase := printf "https://%s/pid/" .Values.hostname }}
{{ $jwtIssuer := printf "https://%s/api/auth/realms/dbrepo" .Values.hostname }}
---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  metadata-db: "{{ index .Values "metadata-db" "db" "name" }}"
  metadata-host: "{{ index .Values "metadata-db" "host" }}"
  metadata-username: "{{ index .Values "metadata-db" "rootUser" "user" }}"
  metadata-password: "{{ index .Values "metadata-db" "rootUser" "password" }}"
  metadata-jdbc-extra-args: "{{ index .Values "metadata-db" "jdbcExtraArgs" }}"
  search-username: "{{ index .Values "search-db" "username" }}"
  search-password: "{{ index .Values "search-db" "password" }}"
  jwt-issuer: "{{ $jwtIssuer }}"
  jwt-pubkey: "{{ .Values.dataService.jwt.pubkey }}"
  broker-username: "{{ index .Values "broker-service" "auth" "username" }}"
  broker-password: "{{ index .Values "broker-service" "auth" "password" }}"
  min-concurrent-consumers: "{{ .Values.dataService.consumerConcurrentMin }}"
  max-concurrent-consumers: "{{ .Values.dataService.consumerConcurrentMax }}"
  requeue-rejected: "{{ .Values.dataService.requeueRejected }}"
  log-level: "{{ ternary "debug" "info" .Values.dataService.image.debug }}"
  broker-host: "{{ index .Values "broker-service" "host" }}"
  broker-port: "{{ index .Values "broker-service" "port" }}"
  broker-virtualhost: "{{ index .Values "broker-service" "virtualHost" }}"
  queue-name: "{{ index .Values "broker-service" "queueName" }}"
  exchange-name: "{{ index .Values "broker-service" "exchangeName" }}"
  routing-key: "{{ index .Values "broker-service" "routingKey" }}"
  connection-timeout: "{{ index .Values "broker-service" "connectionTimeout" }}"