{{ $pidBase := printf "https://%s/pid/" .Values.hostname }}
{{ $jwtIssuer := printf "https://%s/api/auth/realms/dbrepo" .Values.hostname }}
---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  metadata-db: "{{ .Values.metadataDb.db.name }}"
  metadata-host: "{{ .Values.metadataDb.host }}"
  metadata-username: "{{ .Values.metadataDb.rootUser.user }}"
  metadata-password: "{{ .Values.metadataDb.rootUser.password }}"
  metadata-jdbc-extra-args: "{{ .Values.metadataDb.jdbcExtraArgs }}"
  search-username: "{{ .Values.searchdb.username }}"
  search-password: "{{ .Values.searchdb.password }}"
  jwt-issuer: "{{ $jwtIssuer }}"
  jwt-pubkey: "{{ .Values.dataService.jwt.pubkey }}"
  broker-username: "{{ .Values.brokerService.auth.username }}"
  broker-password: "{{ .Values.brokerService.auth.password }}"
  min-concurrent-consumers: "{{ .Values.dataService.consumerConcurrentMin }}"
  max-concurrent-consumers: "{{ .Values.dataService.consumerConcurrentMax }}"
  requeue-rejected: "{{ .Values.dataService.requeueRejected }}"
  log-level: "{{ ternary "debug" "info" .Values.dataService.image.debug }}"
  broker-host: "{{ .Values.brokerService.host }}"
  broker-port: "{{ .Values.brokerService.port }}"
  broker-virtualhost: "{{ .Values.brokerService.virtualHost }}"
  queue-name: "{{ .Values.brokerService.queueName }}"
  exchange-name: "{{ .Values.brokerService.exchangeName }}"
  routing-key: "{{ .Values.brokerService.routingKey }}"
  connection-timeout: "{{ .Values.brokerService.connectionTimeout }}"