variables:
  HOSTALIASES: ./hosts
  TRIVY_NO_PROGRESS: "true"
  TRIVY_CACHE_DIR: ".trivycache/"
  DOCKER_HOST: "unix:///var/run/dind/docker.sock"
  TESTCONTAINERS_RYUK_DISABLED: "false"
  DOC_VERSIONS: "latest,1.4.2,1.4.1,1.4.0,1.3.0"
  APP_VERSION: "1.4.2"
  CHART_VERSION: "1.4.2"

image: debian:12-slim

cache:
  policy: pull
  key: ${CI_BUILD_REF_NAME}
  paths:
    - final/
    - .m2/

stages:
  - lint
  - build
  - test
  - docs
  - release
  - verify
  - scan

lint-yaml:
  image: bash:5.2-alpine3.19
  stage: build
  script:
    - "apk add yq"
    - "yq '.services.[] | .environment' docker-compose.yml > ./doc.txt"
    - "yq '.services.[] | .environment' docker-compose.prod.yml > ./other.txt"
    - "cmp --silent ./doc.txt ./other.txt"

build-metadata-service:
  image: maven:3-openjdk-17
  stage: build
  except:
    refs:
      - /^release-.*/
  script:
    - "mvn -f ./dbrepo-metadata-service/pom.xml clean install -Dstyle.color=always -DskipTests"

build-analyse-service:
  image: python:3.9-slim
  stage: build
  except:
    refs:
      - /^release-.*/
  variables:
    PIPENV_PIPFILE: "./dbrepo-analyse-service/Pipfile"
  script:
    - "pip install pipenv"
    - "pipenv install gunicorn && pipenv install --dev --system --deploy"

build-lib:
  image: python:3.11-slim
  stage: build
  except:
    refs:
      - /^release-.*/
  variables:
    PIPENV_PIPFILE: "./lib/python/Pipfile"
  script:
    - "pip install pipenv"
    - "pipenv install gunicorn && pipenv install --dev --system --deploy"

build-data-service:
  image: maven:3-openjdk-17
  stage: build
  except:
    refs:
      - /^release-.*/
  needs:
    - build-metadata-service
  script:
    - "mvn -f ./dbrepo-metadata-service/pom.xml clean install -Dstyle.color=always -DskipTests"
    - "mvn -f ./dbrepo-data-service/pom.xml clean package -Dstyle.color=always -DskipTests"

build-ui:
  image: oven/bun:1.0.26-alpine
  stage: build
  except:
    refs:
      - /^release-.*/
  script:
    - "cd ./dbrepo-ui && bun install && bun run build"

build-search-service:
  image: python:3.10-alpine
  stage: build
  except:
    refs:
      - /^release-.*/
  script:
    - "pip install pipenv"
    - "cd dbrepo-search-service && pipenv install --system --deploy"

build-docker:
  image: docker.io/docker:24-dind
  stage: build
  except:
    refs:
      - /^release-.*/
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY_URL
  script:
    - "cp .env.unix.example .env"
    - "docker build -t dbrepo-metadata-service:build --target build dbrepo-metadata-service"
    - "docker build -t dbrepo-data-service:build --target build dbrepo-data-service"
    - "docker compose build --parallel"

build-helm:
  image: docker.io/docker:24-dind
  stage: build
  except:
    refs:
      - /^release-.*/
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY_URL
  script:
    - apk add sed helm curl
    - 'sed -i -e "s/^version:.*/version: \"${CHART_VERSION}\"/g" ./helm-charts/dbrepo/Chart.yaml'
    - 'sed -i -e "s/^appVersion:.*/appVersion: \"${APP_VERSION}\"/g" ./helm-charts/dbrepo/Chart.yaml'
    - find ./helm-charts -type f -exec sed -i -e "s/__CHARTVERSION__/${CHART_VERSION}/g" {} \;
    - helm package ./helm-charts/dbrepo --destination ./build

verify-install-script:
  image: docker.io/docker:24-dind
  stage: verify
  only:
    refs:
      - /^release-.*/
  variables:
    SKIP_CHECKS: 1
  script:
    - apk add bash curl
    - bash install.sh
    - exit 0

test-metadata-service:
  image: maven:3-openjdk-17
  stage: test
  except:
    refs:
      - /^release-.*/
  needs:
    - build-metadata-service
  script:
    - "mvn -f ./dbrepo-metadata-service/pom.xml clean install -Dstyle.color=always -DskipTests"
    - "mvn -f ./dbrepo-metadata-service/pom.xml clean test -Dstyle.color=always verify"
    - "cat ./dbrepo-metadata-service/report/target/site/jacoco-aggregate/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'"
  artifacts:
    when: always
    paths:
      - ./dbrepo-metadata-service/report/target/site/jacoco-aggregate/
      - ./dbrepo-metadata-service/rest-service/target/surefire-reports/
    expire_in: 1 days
    reports:
      junit: ./dbrepo-metadata-service/rest-service/target/surefire-reports/TEST-*.xml
  coverage: '/Total.*?([0-9]{1,3})%/'

test-data-service:
  image: maven:3-openjdk-17
  stage: test
  except:
    refs:
      - /^release-.*/
  needs:
    - build-data-service
  script:
    - "mvn -f ./dbrepo-metadata-service/pom.xml clean install -Dstyle.color=always -DskipTests"
    - "mvn -f ./dbrepo-data-service/pom.xml clean test verify -Dstyle.color=always"
    - "cat ./dbrepo-data-service/report/target/site/jacoco-aggregate/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'"
  artifacts:
    when: always
    paths:
      - ./dbrepo-data-service/report/target/site/jacoco-aggregate/
      - ./dbrepo-data-service/rest-service/target/surefire-reports/
    expire_in: 1 days
    reports:
      junit: ./dbrepo-data-service/rest-service/target/surefire-reports/TEST-*.xml
  coverage: '/Total.*?([0-9]{1,3})%/'

test-analyse-service:
  image: python:3.9-slim
  stage: test
  except:
    refs:
      - /^release-.*/
  variables:
    PIPENV_PIPFILE: "./dbrepo-analyse-service/Pipfile"
  needs:
    - build-analyse-service
  script:
    - "pip install pipenv"
    - "pipenv install gunicorn && pipenv install --dev --system --deploy"
    - cd ./dbrepo-analyse-service/ && coverage run -m pytest test/test_determine_dt.py test/test_determine_pk.py test/test_s3_client.py --junitxml=report.xml && coverage html --omit="test/*" && coverage report --omit="test/*" > ./coverage.txt
    - "cat ./coverage.txt | grep -o 'TOTAL[^%]*%'"
  artifacts:
    when: always
    paths:
      - ./dbrepo-analyse-service/report.xml
      - ./dbrepo-analyse-service/coverage.txt
    expire_in: 1 days
    reports:
      junit: ./dbrepo-analyse-service/report.xml
  coverage: '/TOTAL.*?([0-9]{1,3})%/'

test-lib:
  image: python:3.11-slim
  stage: test
  except:
    refs:
      - /^release-.*/
  variables:
    PIPENV_PIPFILE: "./lib/python/Pipfile"
  needs:
    - build-lib
  script:
    - "pip install pipenv"
    - "pipenv install gunicorn && pipenv install --dev --system --deploy"
    - cd ./lib/python/ && coverage run -m pytest tests/test_database.py --junitxml=report.xml && coverage html --omit="test/*" && coverage report --omit="test/*" > ./coverage.txt
    - "cat ./coverage.txt | grep -o 'TOTAL[^%]*%'"
  artifacts:
    when: always
    paths:
      - ./lib/python/report.xml
      - ./lib/python/coverage.txt
    expire_in: 1 days
    reports:
      junit: ./lib/python/report.xml
  coverage: '/TOTAL.*?([0-9]{1,3})%/'

scan-analyse-service:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-analyse-service-report.json docker.io/dbrepo/analyse-service:latest
    - trivy image --insecure --exit-code 0 docker.io/dbrepo/analyse-service:latest
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/dbrepo/analyse-service:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-analyse-service-report.json

scan-authentication-service:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-authentication-service-report.json docker.io/dbrepo/authentication-service:latest
    - trivy image --insecure --exit-code 0 docker.io/dbrepo/authentication-service:latest
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/dbrepo/authentication-service:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-authentication-service-report.json

scan-broker-service:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-broker-service-report.json docker.io/dbrepo/broker-service:latest
    - trivy image --insecure --exit-code 0 docker.io/dbrepo/broker-service:latest
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/dbrepo/broker-service:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-broker-service-report.json

scan-gateway-service:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-gateway-service-report.json docker.io/nginx:1.25.0-alpine-slim
    - trivy image --insecure --exit-code 0 docker.io/nginx:1.25.0-alpine-slim
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/nginx:1.25.0-alpine-slim
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-gateway-service-report.json

scan-metadata-service:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-metadata-service-report.json docker.io/dbrepo/metadata-service:latest
    - trivy image --insecure --exit-code 0 docker.io/dbrepo/metadata-service:latest
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/dbrepo/metadata-service:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-metadata-service-report.json

scan-data-service:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-data-service-report.json docker.io/dbrepo/data-service:latest
    - trivy image --insecure --exit-code 0 docker.io/dbrepo/data-service:latest
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/dbrepo/data-service:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-data-service-report.json

scan-search-db:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-search-db-report.json docker.io/dbrepo/search-db:latest
    - trivy image --insecure --exit-code 0 docker.io/dbrepo/search-db:latest
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/dbrepo/search-db:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-search-db-report.json

scan-search-dashboard:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-search-dashboard-report.json docker.io/opensearchproject/opensearch-dashboards:2.10.0
    - trivy image --insecure --exit-code 0 docker.io/opensearchproject/opensearch-dashboards:2.10.0
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/opensearchproject/opensearch-dashboards:2.10.0
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-search-dashboard-report.json

scan-search-db-init:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-search-db-init-report.json docker.io/dbrepo/search-db-init:latest
    - trivy image --insecure --exit-code 0 docker.io/dbrepo/search-db-init:latest
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/dbrepo/search-db-init:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-search-db-init-report.json

scan-data-db:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-data-db-report.json docker.io/bitnami/mariadb:11.2.2-debian-11-r0
    - trivy image --insecure --exit-code 0 docker.io/bitnami/mariadb:11.2.2-debian-11-r0
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/bitnami/mariadb:11.2.2-debian-11-r0
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-data-db-report.json

scan-metadata-db:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-metadata-db-report.json docker.io/dbrepo/metadata-db:latest
    - trivy image --insecure --exit-code 0 docker.io/dbrepo/metadata-db:latest
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/dbrepo/metadata-db:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-metadata-db-report.json

scan-ui:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-ui-report.json docker.io/dbrepo/ui:latest
    - trivy image --insecure --exit-code 0 docker.io/dbrepo/ui:latest
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/dbrepo/ui:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-ui-report.json

scan-storage-service:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-storage-service-report.json docker.io/chrislusf/seaweedfs:3.59
    - trivy image --insecure --exit-code 0 docker.io/chrislusf/seaweedfs:3.59
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/chrislusf/seaweedfs:3.59
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-storage-service-report.json

scan-storage-service-init:
  image: bitnami/trivy:latest
  stage: scan
  only:
    refs:
      - master
  allow_failure: true
  script:
    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-storage-service-init-report.json docker.io/dbrepo/storage-service-init:latest
    - trivy image --insecure --exit-code 0 docker.io/dbrepo/storage-service-init:latest
    - trivy image --insecure --exit-code 1 --severity CRITICAL docker.io/dbrepo/storage-service-init:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    expire_in: 1 days
    reports:
      container_scanning: ./.trivy/trivy-storage-service-init-report.json

docs-registry:
  stage: docs
  image: docker.io/python:3.11-slim
  only:
    refs:
      - /^release-.*/
  script:
    - pip install -r ./requirements.txt
    - python3 .docs/docker/release.py

release-images:
  stage: release
  image: docker:24-dind
  dependencies:
    - test-metadata-service
    - test-data-service
    - test-analyse-service
  only:
    refs:
      - /^release-.*/
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY_URL
    - echo "$CI_REGISTRY2_PASSWORD" | docker login --username "$CI_REGISTRY2_USER" --password-stdin $CI_REGISTRY2_URL
  script:
    - "ifconfig eth0 mtu 1450 up"
    - "apk add make bash"
    - "make release"

release-chart:
  stage: release
  image: docker:24-dind
  only:
    refs:
      - /^release-.*/
  before_script:
    - echo "$CI_REGISTRY2_PASSWORD" | docker login --username "$CI_REGISTRY2_USER" --password-stdin $CI_REGISTRY2_URL
  script:
    - apk add sed helm curl
    - 'sed -i -e "s/^version:.*/version: \"${CHART_VERSION}\"/g" ./helm-charts/dbrepo/Chart.yaml'
    - 'sed -i -e "s/^appVersion:.*/appVersion: \"${APP_VERSION}\"/g" ./helm-charts/dbrepo/Chart.yaml'
    - find ./helm-charts -type f -exec sed -i -e "s/__CHARTVERSION__/${CHART_VERSION}/g" {} \;
    - helm package ./helm-charts/dbrepo --destination ./build
    - helm push "./build/dbrepo-${CHART_VERSION}.tgz" "oci://${CI_REGISTRY2_URL}/helm"

release-docs:
  stage: release
  image: docker.io/python:3.11-slim
  only:
    refs:
      - /^release-.*/
  script:
    - apt-get update && apt-get install -y git make sed wget ssh
    - make docs
    - eval $(ssh-agent -s)
    - echo "$CI_KEY_PRIVATE" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
    - echo "$CI_KEY_PUBLIC" > /root/.ssh/id_rsa.pub
    - echo "$CI_DOC_ID" > ~/.ssh/known_hosts
    - tar czf ./final.tar.gz ./final
    - "scp -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa final.tar.gz $CI_DOC_USER@$CI_DOC_IP:final.tar.gz"
    - "ssh -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa $CI_DOC_USER@$CI_DOC_IP 'rm -rf /system/user/ifs/infrastructures/public_html/dbrepo/*; tar xzf ./final.tar.gz; rm -f ./final.tar.gz; cp -r ./final/* /system/user/ifs/infrastructures/public_html/dbrepo; rm -rf ./final'"

release-libs:
  stage: release
  image: docker.io/python:3.11-alpine
  only:
    refs:
      - /^release-[0-9]+.*/
  variables:
    PIPENV_PIPFILE: "./dbrepo-analyse-service/Pipfile"
  script:
    - apk add sed
    - pip install pipenv
    - pipenv install gunicorn && pipenv install --dev --system --deploy
    - pip install twine build
    - 'sed -i -e "s/__APPVERSION__/${APP_VERSION}/g" ./lib/python/pyproject.toml ./lib/python/setup.py ./lib/python/README.md'
    - python -m build --sdist ./lib/python
    - python -m build --wheel ./lib/python
    - printf "[diskutils]\nindex-servers =\n    pypi\n\n[pypi]\nusername = __token__\npassword = ${CI_PIPY_TOKEN}\nrepository = https://upload.pypi.org/legacy/" > .pypirc
    - python -m twine upload --config-file .pypirc --verbose --repository pypi ./lib/python/dist/dbrepo-*