variables:
  HOSTALIASES: ./hosts
  TAG: "${TAG:-latest}"
  TRIVY_NO_PROGRESS: "true"
  TRIVY_CACHE_DIR: ".trivycache/"
  DOCKER_HOST: "tcp://docker:2375"

cache:
  paths:
    - /root/.m2/repository/
    - /root/.npm/

image: "docker:stable-dind"

stages:
#  - build-backend
#  - build-frontend
  - test-backend
#  - test-frontend
#  - build-docker
#  - test-deployment
#  - scan-docker
#  - release-docker

#build-metadata-service:
#  image: maven:3-openjdk-17
#  stage: build-backend
#  script:
#    - "mvn -f ./dbrepo-metadata-service/pom.xml clean install -DskipTests"

#build-analyse-service:
#  image: python:3.9-slim
#  stage: build-backend
#  script:
#    - "pip install -r ./dbrepo-analyse-service/requirements.txt"
#
#build-data-service:
#  image: maven:3-openjdk-17
#  stage: build-backend
#  needs:
#    - build-metadata-service
#  script:
#    - "mvn -f ./dbrepo-metadata-service/pom.xml clean install -DskipTests"
#    - "mvn -f ./dbrepo-data-service/pom.xml clean package -DskipTests"
#
#build-mirror-service:
#  image: maven:3-openjdk-17
#  stage: build-backend
#  needs:
#    - build-metadata-service
#  script:
#    - "mvn -f ./dbrepo-metadata-service/pom.xml clean install -DskipTests"
#    - "mvn -f ./dbrepo-mirror-service/pom.xml clean package -DskipTests"
#
#build-frontend:
#  image: node:14-alpine
#  stage: build-frontend
#  script:
#    - "yarn config set network-timeout 600000 -g"
#    - "yarn --cwd ./dbrepo-ui install --legacy-peer-deps"
#    - "yarn --cwd ./dbrepo-ui run build"
#
#build-docker:
#  image: docker:24-dind
#  stage: build-docker
#  script:
#    - "cp .env.unix.example .env"
#    - "docker build -t dbrepo-metadata-service:build --target build dbrepo-metadata-service"
#    - "docker build -t dbrepo-data-service:build --target build dbrepo-data-service"
#    - "docker build -t dbrepo-mirror-service:build --target build dbrepo-mirror-service"
#    - "docker build ./dbrepo-log-service -t dbrepo-log-service"
#    - "docker compose build --parallel"

test-metadata-service:
  image: maven:3-openjdk-17
  stage: test-backend
#  needs:
#    - build-metadata-service
  services:
    - docker:stable-dind
  script:
    - "mvn -f ./dbrepo-metadata-service/pom.xml clean install -DskipTests"
    - "mvn -f ./dbrepo-metadata-service/pom.xml clean test verify"
    - "cat ./dbrepo-metadata-service/report/target/site/jacoco-aggregate/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'"
  artifacts:
    when: always
    paths:
      - ./dbrepo-metadata-service/report/target/site/jacoco-aggregate/
      - ./dbrepo-metadata-service/rest-service/target/surefire-reports/
    expire_in: 1 days
    reports:
      junit: ./dbrepo-metadata-service/rest-service/target/surefire-reports/TEST-*.xml
  coverage: '/Total.*?([0-9]{1,3})%/'

#test-data-service:
#  image: maven:3-openjdk-17
#  stage: test-backend
#  needs:
#    - build-data-service
#  script:
#    - "mvn -f ./dbrepo-metadata-service/pom.xml clean install -DskipTests"
#    - "mvn -f ./dbrepo-data-service/pom.xml clean test verify"
#    - "cat ./dbrepo-data-service/report/target/site/jacoco-aggregate/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'"
#  artifacts:
#    when: always
#    paths:
#      - ./dbrepo-data-service/report/target/site/jacoco-aggregate/
#      - ./dbrepo-data-service/rest-service/target/surefire-reports/
#    expire_in: 1 days
#    reports:
#      junit: ./dbrepo-data-service/rest-service/target/surefire-reports/TEST-*.xml
#  coverage: '/Total.*?([0-9]{1,3})%/'
#
#test-mirror-service:
#  image: maven:3-openjdk-17
#  stage: test-backend
#  needs:
#    - build-mirror-service
#  script:
#    - "mvn -f ./dbrepo-metadata-service/pom.xml clean install -DskipTests"
#    - "mvn -f ./dbrepo-mirror-service/pom.xml clean test verify"
#    - "cat ./dbrepo-mirror-service/report/target/site/jacoco-aggregate/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'"
#  artifacts:
#    when: always
#    paths:
#      - ./dbrepo-mirror-service/report/target/site/jacoco-aggregate/
#      - ./dbrepo-mirror-service/rest-service/target/surefire-reports/
#    expire_in: 1 days
#    reports:
#      junit: ./dbrepo-mirror-service/rest-service/target/surefire-reports/TEST-*.xml
#  coverage: '/Total.*?([0-9]{1,3})%/'
#
#test-analyse-service:
#  image: python:3.9-slim
#  stage: test-backend
#  needs:
#    - build-analyse-service
#  script:
#    - "pip install -r ./dbrepo-analyse-service/requirements.txt"
#    - "cd ./dbrepo-analyse-service/ && coverage run -m pytest test/test_determine_dt.py test/test_determine_pk.py --junitxml=report.xml && coverage html && coverage report > ./coverage.txt"
#    - "cat ./coverage.txt | grep -o 'TOTAL[^%]*%'"
#  artifacts:
#    when: always
#    paths:
#      - ./dbrepo-analyse-service/report.xml
#    expire_in: 1 days
#    reports:
#      junit: ./dbrepo-analyse-service/report.xml
#  coverage: '/TOTAL.*?([0-9]{1,3})%/'
#
#test-frontend:
#  image: node:14-alpine
#  stage: test-frontend
#  needs:
#    - build-frontend
#  script:
#    - "yarn --cwd ./dbrepo-ui install"
#    - "yarn --cwd ./dbrepo-ui run test:unit || true"
#    - "yarn --cwd ./dbrepo-ui run coverage || true"
#    - "cat ./dbrepo-ui/coverage/cobertura-coverage.xml | grep -o 'line-rate=\"[0-9.]*' | head -1"
#  artifacts:
#    when: always
#    paths:
#      - ./dbrepo-ui/coverage/
#    expire_in: 1 days
#    reports:
#      coverage_report:
#        coverage_format: cobertura
#        path: ./dbrepo-ui/coverage/cobertura-coverage.xml
#  coverage: '/TOTAL.*?([0-9]{1,3})%/'
#
#scan-analyse-service:
#  image: bitnami/trivy:latest
#  stage: scan-docker
#  needs:
#    - build-docker
#  only:
#    refs:
#      - dev
#      - master
#  allow_failure: true
#  script:
#    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-analyse-service-report.json dbrepo-analyse-service:latest
#    - trivy image --insecure --exit-code 0 dbrepo-analyse-service:latest
#    - trivy image --insecure --exit-code 1 --severity CRITICAL dbrepo-analyse-service:latest
#  cache:
#    paths:
#      - .trivycache/
#  artifacts:
#    when: always
#    expire_in: 1 days
#    reports:
#      container_scanning: ./.trivy/trivy-analyse-service-report.json
#
#scan-authentication-service:
#  image: bitnami/trivy:latest
#  stage: scan-docker
#  needs:
#    - build-docker
#  only:
#    refs:
#      - dev
#      - master
#  allow_failure: true
#  script:
#    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-authentication-service-report.json dbrepo-authentication-service:latest
#    - trivy image --insecure --exit-code 0 dbrepo-authentication-service:latest
#    - trivy image --insecure --exit-code 1 --severity CRITICAL dbrepo-authentication-service:latest
#  cache:
#    paths:
#      - .trivycache/
#  artifacts:
#    when: always
#    expire_in: 1 days
#    reports:
#      container_scanning: ./.trivy/trivy-authentication-service-report.json
#
#scan-broker-service:
#  image: bitnami/trivy:latest
#  stage: scan-docker
#  needs:
#    - build-docker
#  only:
#    refs:
#      - dev
#      - master
#  allow_failure: true
#  script:
#    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-broker-service-report.json dbrepo-authentication-service:latest
#    - trivy image --insecure --exit-code 0 dbrepo-broker-service:latest
#    - trivy image --insecure --exit-code 1 --severity CRITICAL dbrepo-broker-service:latest
#  cache:
#    paths:
#      - .trivycache/
#  artifacts:
#    when: always
#    expire_in: 1 days
#    reports:
#      container_scanning: ./.trivy/trivy-broker-service-report.json
#
#scan-gateway-service:
#  image: bitnami/trivy:latest
#  stage: scan-docker
#  needs:
#    - build-docker
#  only:
#    refs:
#      - dev
#      - master
#  allow_failure: true
#  script:
#    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-gateway-service-report.json "nginx:1.25.0-alpine-slim"
#    - trivy image --insecure --exit-code 0 "nginx:1.25.0-alpine-slim"
#    - trivy image --insecure --exit-code 1 --severity CRITICAL "nginx:1.25.0-alpine-slim""
#  cache:
#    paths:
#      - .trivycache/
#  artifacts:
#    when: always
#    expire_in: 1 days
#    reports:
#      container_scanning: ./.trivy/trivy-gateway-service-report.json
#
#scan-metadata-service:
#  image: bitnami/trivy:latest
#  stage: scan-docker
#  needs:
#    - build-docker
#  only:
#    refs:
#      - dev
#      - master
#  allow_failure: true
#  script:
#    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-metadata-service-report.json dbrepo-metadata-service:latest
#    - trivy image --insecure --exit-code 0 dbrepo-metadata-service:latest
#    - trivy image --insecure --exit-code 1 --severity CRITICAL dbrepo-metadata-service:latest
#  cache:
#    paths:
#      - .trivycache/
#  artifacts:
#    when: always
#    expire_in: 1 days
#    reports:
#      container_scanning: ./.trivy/trivy-metadata-service-report.json
#
#scan-search-db:
#  image: bitnami/trivy:latest
#  stage: scan-docker
#  needs:
#    - build-docker
#  only:
#    refs:
#      - dev
#      - master
#  allow_failure: true
#  script:
#    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-search-db-report.json "dbrepo-search-db"
#    - trivy image --insecure --exit-code 0 "dbrepo-search-db"
#    - trivy image --insecure --exit-code 1 --severity CRITICAL "dbrepo-search-db"
#  cache:
#    paths:
#      - .trivycache/
#  artifacts:
#    when: always
#    expire_in: 1 days
#    reports:
#      container_scanning: ./.trivy/trivy-search-db-report.json
#
#scan-data-db:
#  image: bitnami/trivy:latest
#  stage: scan-docker
#  needs:
#    - build-docker
#  only:
#    refs:
#      - dev
#      - master
#  allow_failure: true
#  script:
#    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-data-db-report.json "bitnami/mariadb:10.5"
#    - trivy image --insecure --exit-code 0 "bitnami/mariadb:10.5"
#    - trivy image --insecure --exit-code 1 --severity CRITICAL "bitnami/mariadb:10.5"
#  cache:
#    paths:
#      - .trivycache/
#  artifacts:
#    when: always
#    expire_in: 1 days
#    reports:
#      container_scanning: ./.trivy/trivy-data-db-report.json
#
#scan-metadata-db:
#  image: bitnami/trivy:latest
#  stage: scan-docker
#  needs:
#    - build-docker
#  only:
#    refs:
#      - dev
#      - master
#  allow_failure: true
#  script:
#    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-metadata-db-report.json dbrepo-metadata-db:latest
#    - trivy image --insecure --exit-code 0 dbrepo-metadata-db:latest
#    - trivy image --insecure --exit-code 1 --severity CRITICAL dbrepo-metadata-db:latest
#  cache:
#    paths:
#      - .trivycache/
#  artifacts:
#    when: always
#    expire_in: 1 days
#    reports:
#      container_scanning: ./.trivy/trivy-metadata-db-report.json
#
#scan-ui:
#  image: bitnami/trivy:latest
#  stage: scan-docker
#  needs:
#    - build-docker
#  only:
#    refs:
#      - dev
#      - master
#  allow_failure: true
#  script:
#    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-ui-report.json dbrepo-ui:latest
#    - trivy image --insecure --exit-code 0 dbrepo-ui:latest
#    - trivy image --insecure --exit-code 1 --severity CRITICAL dbrepo-ui:latest
#  cache:
#    paths:
#      - .trivycache/
#  artifacts:
#    when: always
#    expire_in: 1 days
#    reports:
#      container_scanning: ./.trivy/trivy-ui-report.json
#
#scan-log-service:
#  image: bitnami/trivy:latest
#  stage: scan-docker
#  needs:
#    - build-docker
#  only:
#    refs:
#      - dev
#      - master
#  allow_failure: true
#  script:
#    - trivy image --insecure --exit-code 0 --format template --template "@.trivy/gitlab.tpl" -o ./.trivy/trivy-log-service-report.json dbrepo-log-service:latest
#    - trivy image --insecure --exit-code 0 dbrepo-log-service:latest
#    - trivy image --insecure --exit-code 1 --severity CRITICAL dbrepo-log-service:latest
#  cache:
#    paths:
#      - .trivycache/
#  artifacts:
#    when: always
#    expire_in: 1 days
#    reports:
#      container_scanning: ./.trivy/trivy-log-service-report.json
#
#release-latest:
#  stage: release-docker
#  needs:
#    - scan-analyse-service
#    - scan-authentication-service
#    - scan-broker-service
#    - scan-gateway-service
#    - scan-metadata-service
#    - scan-metadata-db
#    - scan-data-db
#    - scan-search-db
#    - scan-ui
#    - scan-log-service
#  only:
#    refs:
#      - dev
#  script:
#    - cp .env.unix.example .env
#    - docker login -p "${DOCKER_PASSWORD}" -u "${DOCKER_USERNAME}"
#    - docker login "${AZURE_REPO}" -p "${AZURE_PASSWORD}" -u "${AZURE_USERNAME}"
#    - TAG=latest make release
#
#release-version:
#  stage: release-docker
#  needs:
#    - scan-analyse-service
#    - scan-authentication-service
#    - scan-broker-service
#    - scan-gateway-service
#    - scan-metadata-service
#    - scan-metadata-db
#    - scan-data-db
#    - scan-search-db
#    - scan-ui
#  only:
#    refs:
#      - master
#  script:
#    - cp .env.unix.example .env
#    - docker login -p "${DOCKER_PASSWORD}" -u "${DOCKER_USERNAME}"
#    - docker login "${AZURE_REPO}" -p "${AZURE_PASSWORD}" -u "${AZURE_USERNAME}"
#    - TAG=1.3 make release
