# INFO: This compose file builds the local branch and deploys them as a small, local test instance
# MODIFIED: 2022-10-19
# MAINTAINER: Martin Weise <martin.weise@tuwien.ac.at>

version: "3.6"

volumes:
  metadata-db-data:
  search-service-data:
  broker-service-data:
  authentication-service-data:

networks:
  userdb:
    name: userdb
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
  public:
    name: public
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
  core:
    name: core
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16

services:
  fda-metadata-db:
    restart: on-failure
    container_name: dbrepo-metadata-db
    hostname: metadata-db
    build: ./fda-metadata-db
    image: fda-metadata-db
    networks:
      core:
    volumes:
      - metadata-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
      - "9100:9100"
    env_file:
      - .env
    logging:
      driver: json-file

  fda-discovery-service:
    restart: on-failure
    container_name: dbrepo-discovery-service
    hostname: discovery-service
    build: ./fda-discovery-service
    image: fda-discovery-service
    networks:
      core:
    ports:
      - "9090:9090"
    env_file:
      - .env
    logging:
      driver: json-file

  fda-gateway-service:
    restart: on-failure
    container_name: dbrepo-gateway-service
    hostname: gateway-service
    build: ./fda-gateway-service
    image: fda-gateway-service
    networks:
      core:
    ports:
      - "9095:9095"
    env_file:
      - .env
    depends_on:
      fda-discovery-service:
        condition: service_healthy
    logging:
      driver: json-file

  fda-database-service:
    restart: on-failure
    container_name: dbrepo-database-service
    hostname: database-service
    build: ./fda-database-service
    image: fda-database-service
    networks:
      userdb:
      core:
    ports:
      - "9092:9092"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      fda-container-service:
        condition: service_healthy
      fda-broker-service:
        condition: service_started
      fda-authentication-service:
        condition: service_healthy
    logging:
      driver: json-file

  fda-container-service:
    restart: on-failure
    container_name: dbrepo-container-service
    hostname: container-service
    build: ./fda-container-service
    image: fda-container-service
    networks:
      core:
    ports:
      - "9091:9091"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      fda-authentication-service:
        condition: service_healthy
    logging:
      driver: json-file

  fda-authentication-service:
    restart: on-failure
    container_name: dbrepo-authentication-service
    hostname: authentication-service
    image: fda-authentication-service
    build: ./fda-authentication-service
    networks:
      core:
    ports:
      - "9097:9097"
      - "8443:8443"
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - authentication-service-data:/opt/keycloak/data/
    depends_on:
      fda-discovery-service:
        condition: service_healthy
      fda-metadata-db:
        condition: service_healthy
    logging:
      driver: json-file

  fda-query-service:
    restart: on-failure
    container_name: dbrepo-query-service
    hostname: query-service
    build: ./fda-query-service
    image: fda-query-service
    networks:
      core:
      userdb:
    ports:
      - "9093:9093"
    env_file:
      - .env
    volumes:
      - "/tmp:/tmp"
    depends_on:
      fda-table-service:
        condition: service_healthy
      fda-authentication-service:
        condition: service_healthy
    logging:
      driver: json-file

  fda-table-service:
    restart: on-failure
    container_name: dbrepo-table-service
    hostname: table-service
    build: ./fda-table-service
    image: fda-table-service
    networks:
      core:
      userdb:
    ports:
      - "9094:9094"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/tmp:/tmp"
    depends_on:
      fda-authentication-service:
        condition: service_healthy
      fda-search-service:
        condition: service_started
      fda-broker-service:
        condition: service_healthy
    logging:
      driver: json-file

  fda-identifier-service:
    restart: on-failure
    container_name: dbrepo-identifier-service
    hostname: identifier-service
    build: ./fda-identifier-service
    image: fda-identifier-service
    networks:
      core:
    ports:
      - "9096:9096"
    env_file:
      - .env
    depends_on:
      fda-query-service:
        condition: service_healthy
      fda-authentication-service:
        condition: service_healthy
    volumes:
      - /tmp:/tmp
    logging:
      driver: json-file

  fda-metadata-service:
    restart: on-failure
    container_name: dbrepo-metadata-service
    hostname: metadata-service
    build: ./fda-metadata-service
    image: fda-metadata-service
    networks:
      core:
    env_file:
      - .env
    ports:
      - "9099:9099"
    depends_on:
      fda-authentication-service:
        condition: service_healthy
      fda-metadata-db:
        condition: service_healthy
    logging:
      driver: json-file

  fda-analyse-service:
    restart: on-failure
    container_name: dbrepo-analyse-service
    hostname: analyse-service
    build: ./fda-analyse-service
    image: fda-analyse-service
    networks:
      core:
      userdb:
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - "/tmp:/tmp"
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      fda-discovery-service:
        condition: service_healthy
    logging:
      driver: json-file

  fda-user-service:
    restart: on-failure
    container_name: dbrepo-user-service
    hostname: user-service
    build: ./fda-user-service
    image: fda-user-service
    networks:
      core:
    ports:
      - "9098:9098"
    env_file:
      - .env
    depends_on:
      fda-metadata-db:
        condition: service_healthy
      fda-authentication-service:
        condition: service_healthy
    logging:
      driver: json-file

  fda-semantics-service:
    restart: on-failure
    container_name: dbrepo-semantics-service
    hostname: semantics-service
    build: ./fda-semantics-service
    image: fda-semantics-service
    networks:
      core:
    ports:
      - "5010:5010"
    env_file:
      - .env
    volumes:
      - "/tmp:/tmp"
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      fda-discovery-service:
        condition: service_healthy
      fda-metadata-db:
        condition: service_healthy
      fda-authentication-service:
        condition: service_healthy
    logging:
      driver: json-file

  fda-broker-service:
    restart: on-failure
    container_name: dbrepo-broker-service
    hostname: broker-service
    build: ./fda-broker-service
    image: fda-broker-service
    networks:
      core:
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    depends_on:
      fda-discovery-service:
        condition: service_healthy
      fda-authentication-service:
        condition: service_healthy
    volumes:
      - broker-service-data:/var/lib/rabbitmq/
    logging:
      driver: json-file

  fda-search-service:
    restart: always
    container_name: dbrepo-search-service
    hostname: search-service
    build: ./fda-search-service
    image: fda-search-service
    networks:
      core:
    depends_on:
      fda-discovery-service:
        condition: service_healthy
    ports:
      - 9200:9200
      - 9600:9600
    env_file:
      - .env
    volumes:
      - search-service-data:/usr/share/elasticsearch/data
    logging:
      driver: json-file

  fda-ui:
    restart: on-failure
    container_name: dbrepo-ui
    hostname: ui
    build: ./fda-ui
    image: fda-ui
    networks:
      core:
      public:
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "/tmp:/tmp"
    depends_on:
      fda-identifier-service:
        condition: service_healthy
      fda-database-service:
        condition: service_healthy
    logging:
      driver: json-file
