version: "3.6"

volumes:
  metadata-db-data:
  search-service-data:
  broker-service-data:

networks:
  public:
    name: public
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
  userdb:
    name: userdb
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:

  metadata-db:
    restart: on-failure
    container_name: dbrepo-metadata-db
    hostname: metadata-db
    image: dbrepo/metadata-db:1.1
    networks:
      public:
    volumes:
      - metadata-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${METADATA_DB}
      POSTGRES_USER: ${METADATA_USERNAME}
      POSTGRES_PASSWORD: ${METADATA_PASSWORD}
    logging:
      driver: json-file

  discovery-service:
    restart: on-failure
    container_name: dbrepo-discovery-service
    hostname: discovery-service
    image: dbrepo/discovery-service:1.1
    networks:
      public:
    ports:
      - "9090:9090"
    environment:
      METADATA_DB: ${METADATA_DB}
      METADATA_USERNAME: ${METADATA_USERNAME}
      METADATA_PASSWORD: ${METADATA_PASSWORD}
    logging:
      driver: json-file

  gateway-service:
    restart: on-failure
    container_name: dbrepo-gateway-service
    hostname: gateway-service
    image: dbrepo/gateway-service:1.1
    networks:
      public:
    ports:
      - "9095:9095"
    environment:
      METADATA_DB: ${METADATA_DB}
      METADATA_USERNAME: ${METADATA_USERNAME}
      METADATA_PASSWORD: ${METADATA_PASSWORD}
    depends_on:
      discovery-service:
        condition: service_healthy
    logging:
      driver: json-file

  database-service:
    restart: on-failure
    container_name: dbrepo-database-service
    hostname: database-service
    image: dbrepo/database-service:1.1
    networks:
      userdb:
      public:
    ports:
      - "9092:9092"
    environment:
      METADATA_DB: ${METADATA_DB}
      METADATA_USERNAME: ${METADATA_USERNAME}
      METADATA_PASSWORD: ${METADATA_PASSWORD}
      BROKER_USERNAME: ${BROKER_USERNAME}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      container-service:
        condition: service_healthy
      broker-service:
        condition: service_started
      authentication-service:
        condition: service_healthy
    logging:
      driver: json-file

  container-service:
    restart: on-failure
    container_name: dbrepo-container-service
    hostname: container-service
    image: dbrepo/container-service:1.1
    networks:
      public:
    ports:
      - "9091:9091"
    environment:
      METADATA_DB: ${METADATA_DB}
      METADATA_USERNAME: ${METADATA_USERNAME}
      METADATA_PASSWORD: ${METADATA_PASSWORD}
      BROKER_USERNAME: ${BROKER_USERNAME}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      SHARED_FILESYSTEM: ${SHARED_FILESYSTEM}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      authentication-service:
        condition: service_healthy
    logging:
      driver: json-file

  authentication-service:
    restart: on-failure
    container_name: dbrepo-authentication-service
    hostname: authentication-service
    image: dbrepo/authentication-service:1.1
    networks:
      public:
    ports:
      - "9097:9097"
    environment:
      METADATA_DB: ${METADATA_DB}
      METADATA_USERNAME: ${METADATA_USERNAME}
      METADATA_PASSWORD: ${METADATA_PASSWORD}
      WEBSITE: ${WEBSITE}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_REPLY_TO: ${MAIL_REPLY_TO}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_VERIFY: ${MAIL_VERIFY}
    depends_on:
      discovery-service:
        condition: service_healthy
      broker-service:
        condition: service_started
      metadata-db:
        condition: service_healthy
    logging:
      driver: json-file

  query-service:
    restart: on-failure
    container_name: dbrepo-query-service
    hostname: query-service
    image: dbrepo/query-service:1.1
    networks:
      public:
      userdb:
    ports:
      - "9093:9093"
    environment:
      METADATA_DB: ${METADATA_DB}
      METADATA_USERNAME: ${METADATA_USERNAME}
      METADATA_PASSWORD: ${METADATA_PASSWORD}
      BROKER_USERNAME: ${BROKER_USERNAME}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
    volumes:
      - ${SHARED_FILESYSTEM}:/tmp
    depends_on:
      table-service:
        condition: service_healthy
      authentication-service:
        condition: service_healthy
    logging:
      driver: json-file

  table-service:
    restart: on-failure
    container_name: dbrepo-table-service
    hostname: table-service
    image: dbrepo/table-service:1.1
    networks:
      public:
      userdb:
    ports:
      - "9094:9094"
    environment:
      multipart.location: ${SHARED_FILESYSTEM}
      METADATA_DB: ${METADATA_DB}
      METADATA_USERNAME: ${METADATA_USERNAME}
      METADATA_PASSWORD: ${METADATA_PASSWORD}
      BROKER_USERNAME: ${BROKER_USERNAME}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHARED_FILESYSTEM}:/tmp
    depends_on:
      authentication-service:
        condition: service_healthy
      search-service:
        condition: service_started
      broker-service:
        condition: service_started
    logging:
      driver: json-file

  identifier-service:
    restart: on-failure
    container_name: dbrepo-identifier-service
    hostname: identifier-service
    image: dbrepo/identifier-service:1.1
    networks:
      public:
    ports:
      - "9096:9096"
    environment:
      METADATA_DB: ${METADATA_DB}
      METADATA_USERNAME: ${METADATA_USERNAME}
      METADATA_PASSWORD: ${METADATA_PASSWORD}
    depends_on:
      query-service:
        condition: service_healthy
      authentication-service:
        condition: service_healthy
    logging:
      driver: json-file

  analyse-service:
    restart: on-failure
    container_name: dbrepo-analyse-service
    hostname: analyse-service
    image: dbrepo/analyse-service:1.1
    networks:
      public:
      userdb:
    command: sh -c "/wait && flask run" # docker-compose should not test the implementation
    ports:
      - "5000:5000"
    volumes:
      - ${SHARED_FILESYSTEM}:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      discovery-service:
        condition: service_healthy
    logging:
      driver: json-file

  units-service:
    restart: on-failure
    container_name: dbrepo-units-service
    hostname: units-service
    image: dbrepo/units-service:1.1
    networks:
      public:
    ports:
      - "5010:5010"
    volumes:
      - ${SHARED_FILESYSTEM}:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      discovery-service:
        condition: service_healthy
    logging:
      driver: json-file

  broker-service:
    restart: on-failure
    container_name: dbrepo-broker-service
    hostname: broker-service
    image: dbrepo/broker-service:1.1
    networks:
      public:
    ports:
      - "5672:5672"
      - "9098:9098"
      - "15672:15672"
    environment:
      METADATA_DB: ${METADATA_DB}
      METADATA_USERNAME: ${METADATA_USERNAME}
      METADATA_PASSWORD: ${METADATA_PASSWORD}
      BROKER_USERNAME: ${BROKER_USERNAME}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${BROKER_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASSWORD}
    depends_on:
      discovery-service:
        condition: service_healthy
    volumes:
      - broker-service-data:/var/lib/rabbitmq/
    logging:
      driver: json-file

  search-service:
    restart: always
    container_name: dbrepo-search-service
    hostname: search-service
    image: elasticsearch:7.13.4
    command: [ "elasticsearch" ]
    networks:
      public:
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - logger.level=WARN
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - search-service-data:/usr/share/elasticsearch/data
    logging:
      driver: json-file

  ui:
    restart: on-failure
    container_name: dbrepo-ui
    hostname: ui
    image: dbrepo/ui:1.1
    networks:
      public:
    ports:
      - "3000:3000"
    volumes:
      - ${SHARED_FILESYSTEM}:/tmp
    depends_on:
      identifier-service:
        condition: service_healthy
      database-service:
        condition: service_healthy
    environment:
      BROKER_USERNAME: ${BROKER_USERNAME}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      SHARED_FILESYSTEM: ${SHARED_FILESYSTEM}
    logging:
      driver: json-file
