version: "3.6"

volumes:
  metadata-db-data:
  data-db-data:
  auth-db-data:
  broker-service-data:
  upload-service-data:
  search-db-data:
  storage-service-data:

services:
  dbrepo-metadata-db:
    restart: "no"
    container_name: dbrepo-metadata-db
    hostname: metadata-db
    image: dbrepo-metadata-db:latest
    build:
      context: ./dbrepo-metadata-db
      network: host
    volumes:
      - metadata-db-data:/bitnami/mariadb
      - ./dbrepo-metadata-db/setup-data.sql:/docker-entrypoint-initdb.d/setup-schema_local.sql
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: "${METADATA_DB:-dbrepo}"
      MARIADB_ROOT_PASSWORD: "${METADATA_PASSWORD:-dbrepo}"
    healthcheck:
      test: mysqladmin ping --user="${METADATA_USERNAME:-root}" --password="${METADATA_PASSWORD:-dbrepo}" --silent
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-data-db:
    restart: "no"
    container_name: dbrepo-data-db
    hostname: data-db
    image: docker.io/bitnami/mariadb-galera:11.2.2-debian-11-r0
    volumes:
      - data-db-data:/bitnami/mariadb
      - "${SHARED_VOLUME:-/tmp}:/tmp"
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${USER_DB_PASSWORD:-dbrepo}"
      MARIADB_GALERA_MARIABACKUP_PASSWORD: "${USER_DB_BACKUP_PASSWORD:-dbrepo}"
    healthcheck:
      test: mysqladmin ping --user="${USER_DB_USERNAME:-root}" --password="${USER_DB_PASSWORD:-dbrepo}" --silent
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-auth-db:
    restart: "no"
    container_name: dbrepo-auth-db
    hostname: auth-db
    image: docker.io/bitnami/mariadb:11.2.2-debian-11-r0
    volumes:
      - auth-db-data:/bitnami/mariadb
    ports:
      - "3308:3306"
    environment:
      MARIADB_DATABASE: "${AUTH_DB:-keycloak}"
      MARIADB_ROOT_PASSWORD: "${AUTH_PASSWORD:-dbrepo}"
    healthcheck:
      test: mysqladmin ping --user="${AUTH_USERNAME:-root}" --password="${AUTH_PASSWORD:-dbrepo}" --silent
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-auth-service:
    restart: "no"
    container_name: dbrepo-auth-service
    hostname: auth-service
    image: dbrepo-auth-service:latest
    ports:
      - "8080:8080"
    build:
      context: ./dbrepo-auth-service
      network: host
    healthcheck:
      test: curl -sSL 'http://0.0.0.0:8080/realms/dbrepo' | grep "dbrepo" || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    environment:
      AUTH_DB: "${AUTH_DB:-keycloak}"
      KC_DB_USERNAME: "${AUTH_USERNAME:-root}"
      KC_DB_PASSWORD: "${AUTH_PASSWORD:-dbrepo}"
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN:-fda}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD:-fda}"
    depends_on:
      dbrepo-auth-db:
        condition: service_healthy
    logging:
      driver: json-file

  dbrepo-metadata-service:
    restart: "no"
    container_name: dbrepo-metadata-service
    hostname: metadata-service
    image: dbrepo-metadata-service:latest
    build:
      context: ./dbrepo-metadata-service
      network: host
    ports:
      - "9099:8080"
    volumes:
      - "${SHARED_VOLUME:-/tmp}:/tmp"
    environment:
      ADMIN_EMAIL: "${ADMIN_EMAIL:-noreply@localhost}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
      ADMIN_USERNAME: "${ADMIN_USERNAME:-admin}"
      ANALYSE_SERVICE_ENDPOINT: "${ANALYSE_SERVICE_ENDPOINT:-http://gateway-service}"
      AUTH_SERVICE_ADMIN: ${AUTH_SERVICE_ADMIN:-fda}
      AUTH_SERVICE_ADMIN_PASSWORD: ${AUTH_SERVICE_ADMIN_PASSWORD:-fda}
      AUTH_SERVICE_CLIENT: ${AUTH_SERVICE_CLIENT:-dbrepo-client}
      AUTH_SERVICE_CLIENT_SECRET: ${AUTH_SERVICE_CLIENT:-MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG}
      AUTH_SERVICE_ENDPOINT: ${AUTH_SERVICE_ENDPOINT:-http://gateway-service/api/auth}
      BASE_URL: "${BASE_URL:-http://localhost}"
      BROKER_EXCHANGE_NAME: ${BROKER_EXCHANGE_NAME:-dbrepo}
      BROKER_QUEUE_NAME: ${BROKER_QUEUE_NAME:-dbrepo}
      BROKER_HOST: "${BROKER_ENDPOINT:-broker-service}"
      BROKER_PASSWORD: ${BROKER_PASSWORD:-fda}
      BROKER_PORT: ${BROKER_PORT:-5672}
      BROKER_SERVICE_ENDPOINT: ${BROKER_SERVICE_ENDPOINT:-http://gateway-service/admin/broker}
      BROKER_USERNAME: ${BROKER_USERNAME:-fda}
      BROKER_VIRTUALHOST: "${BROKER_VIRTUALHOST:-dbrepo}"
      DATA_SERVICE_ENDPOINT: ${DATA_SERVICE_ENDPOINT:-http://data-service:8080}
      DELETED_RECORD: "${DELETED_RECORD:-persistent}"
      GRANULARITY: "${GRANULARITY:-YYYY-MM-DDThh:mm:ssZ}"
      JWT_PUBKEY: "${JWT_PUBKEY:-MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqqnHQ2BWWW9vDNLRCcxD++xZg/16oqMo/c1l+lcFEjjAIJjJp/HqrPYU/U9GvquGE6PbVFtTzW1KcKawOW+FJNOA3CGo8Q1TFEfz43B8rZpKsFbJKvQGVv1Z4HaKPvLUm7iMm8Hv91cLduuoWx6Q3DPe2vg13GKKEZe7UFghF+0T9u8EKzA/XqQ0OiICmsmYPbwvf9N3bCKsB/Y10EYmZRb8IhCoV9mmO5TxgWgiuNeCTtNCv2ePYqL/U0WvyGFW0reasIK8eg3KrAUj8DpyOgPOVBn3lBGf+3KFSYi+0bwZbJZWqbC/Xlk20Go1YfeJPRIt7ImxD27R/lNjgDO/MwIDAQAB}"
      LOG_LEVEL: trace
      METADATA_DB: "${METADATA_DB:-dbrepo}"
      METADATA_HOST: "${METADATA_HOST:-metadata-db}"
      METADATA_JDBC_EXTRA_ARGS: "${METADATA_JDBC_EXTRA_ARGS:-}"
      METADATA_USERNAME: "${METADATA_USERNAME:-root}"
      METADATA_PASSWORD: "${METADATA_PASSWORD:-dbrepo}"
      PID_BASE: ${PID_BASE:-http://localhost/pid/}
      REPOSITORY_NAME: "${REPOSITORY_NAME:-Database Repository}"
      SEARCH_SERVICE_ENDPOINT: "${SEARCH_SERVICE_ENDPOINT:-http://gateway-service}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID:-seaweedfsadmin}"
      S3_ENDPOINT: "${S3_ENDPOINT:-http://storage-service:9000}"
      S3_EXPORT_BUCKET: "${S3_EXPORT_BUCKET:-dbrepo-download}"
      S3_IMPORT_BUCKET: "${S3_IMPORT_BUCKET:-dbrepo-upload}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:-seaweedfsadmin}"
      SPARQL_CONNECTION_TIMEOUT: "${SPARQL_CONNECTION_TIMEOUT:-10000}"
    healthcheck:
      test: curl -sSL localhost:8080/actuator/health/liveness | grep 'UP' || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    depends_on:
      dbrepo-auth-service:
        condition: service_healthy
      dbrepo-broker-service:
        condition: service_healthy
      dbrepo-data-service:
        condition: service_healthy
      dbrepo-metadata-db:
        condition: service_healthy
    logging:
      driver: json-file

  dbrepo-analyse-service:
    restart: "no"
    container_name: dbrepo-analyse-service
    hostname: analyse-service
    image: dbrepo-analyse-service:latest
    build:
      context: ./dbrepo-analyse-service
      network: host
    ports:
      - "5000:8080"
    environment:
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
      ADMIN_USERNAME: "${ADMIN_USERNAME:-admin}"
      AUTH_SERVICE_CLIENT: ${AUTH_SERVICE_CLIENT:-dbrepo-client}
      AUTH_SERVICE_CLIENT_SECRET: ${AUTH_SERVICE_CLIENT:-MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG}
      AUTH_SERVICE_ENDPOINT: ${AUTH_SERVICE_ENDPOINT:-http://auth-service:8080}
      GATEWAY_SERVICE_ENDPOINT: ${GATEWAY_SERVICE_ENDPOINT:-http://gateway-service}
      JWT_PUBKEY: "${JWT_PUBKEY:-MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqqnHQ2BWWW9vDNLRCcxD++xZg/16oqMo/c1l+lcFEjjAIJjJp/HqrPYU/U9GvquGE6PbVFtTzW1KcKawOW+FJNOA3CGo8Q1TFEfz43B8rZpKsFbJKvQGVv1Z4HaKPvLUm7iMm8Hv91cLduuoWx6Q3DPe2vg13GKKEZe7UFghF+0T9u8EKzA/XqQ0OiICmsmYPbwvf9N3bCKsB/Y10EYmZRb8IhCoV9mmO5TxgWgiuNeCTtNCv2ePYqL/U0WvyGFW0reasIK8eg3KrAUj8DpyOgPOVBn3lBGf+3KFSYi+0bwZbJZWqbC/Xlk20Go1YfeJPRIt7ImxD27R/lNjgDO/MwIDAQAB}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID:-seaweedfsadmin}"
      S3_ENDPOINT: "${S3_ENDPOINT:-http://storage-service:9000}"
      S3_EXPORT_BUCKET: "${S3_EXPORT_BUCKET:-dbrepo-download}"
      S3_IMPORT_BUCKET: "${S3_IMPORT_BUCKET:-dbrepo-upload}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:-seaweedfsadmin}"
    volumes:
      - "${SHARED_FILESYSTEM:-/tmp}:/tmp"
    healthcheck:
      test: curl -sSL localhost:8080/health | grep 'UP' || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-broker-service:
    restart: "no"
    container_name: dbrepo-broker-service
    hostname: broker-service
    image: docker.io/bitnami/rabbitmq:3.12-debian-12
    volumes:
      - ./dbrepo-broker-service/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./dbrepo-broker-service/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./dbrepo-broker-service/cert.pem:/app/cert.pem
      - ./dbrepo-broker-service/pubkey.pem:/app/pubkey.pem
      - ./dbrepo-broker-service/definitions.json:/app/definitions.json
      - broker-service-data:/bitnami/rabbitmq/mnesia
    depends_on:
      dbrepo-auth-service:
        condition: service_healthy
    healthcheck:
      test: rabbitmq-diagnostics -q is_running | grep 'is fully booted and running'
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-search-db:
    restart: "no"
    container_name: dbrepo-search-db
    hostname: search-db
    image: dbrepo-search-db:latest
    build:
      context: ./dbrepo-search-db
      network: host
    healthcheck:
      test: curl -sSL localhost:9200/_plugins/_security/health | jq .status | grep UP
      interval: 10s
      timeout: 5s
      retries: 12
    environment:
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
      logger.level: "WARN"
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - "9200:9200"
    volumes:
      - search-db-data:/usr/share/elasticsearch/data
    logging:
      driver: json-file

  dbrepo-search-service:
    restart: "no"
    container_name: dbrepo-search-service
    hostname: search-service
    image: dbrepo-search-service:latest
    build:
      context: ./dbrepo-search-service
      network: host
    ports:
      - "4000:8080"
    environment:
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
      ADMIN_USERNAME: "${ADMIN_USERNAME:-admin}"
      AUTH_SERVICE_CLIENT: ${AUTH_SERVICE_CLIENT:-dbrepo-client}
      AUTH_SERVICE_CLIENT_SECRET: ${AUTH_SERVICE_CLIENT:-MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG}
      AUTH_SERVICE_ENDPOINT: ${AUTH_SERVICE_ENDPOINT:-http://auth-service:8080}
      COLLECTION: ${COLLECTION:-['database','table','column','identifier','unit','concept','user','view']}
      OPENSEARCH_HOST: ${OPENSEARCH_HOST:-search-db}
      OPENSEARCH_PORT: ${OPENSEARCH_PORT:-9200}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-admin}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-admin}
      LOG_LEVEL: ${LOG_LEVEL:-info}

  dbrepo-data-db-sidecar:
    restart: "no"
    container_name: dbrepo-data-db-sidecar
    hostname: data-db-sidecar
    image: dbrepo-data-db-sidecar:latest
    build:
      context: ./dbrepo-data-db/sidecar
      network: host
    ports:
      - "3305:8080"
    environment:
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID:-seaweedfsadmin}"
      S3_ENDPOINT: "${S3_ENDPOINT:-http://storage-service:9000}"
      S3_EXPORT_BUCKET: "${S3_EXPORT_BUCKET:-dbrepo-download}"
      S3_FILE_PATH: "${S3_FILE_PATH:-/tmp}"
      S3_IMPORT_BUCKET: "${S3_IMPORT_BUCKET:-dbrepo-upload}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:-seaweedfsadmin}"
    volumes:
      - "${SHARED_FILESYSTEM:-/tmp}:/tmp"
    healthcheck:
      test: curl -sSL localhost:8080/health | grep 'UP' || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-ui:
    restart: "no"
    container_name: dbrepo-ui
    hostname: ui
    image: dbrepo-ui:latest
    build:
      context: ./dbrepo-ui
      args:
        APP_VERSION: ${APP_VERSION:-latest}
        COMMIT: ${CI_COMMIT_SHA:-}
      network: host
    depends_on:
      dbrepo-search-service:
        condition: service_started
      dbrepo-storage-service:
        condition: service_healthy
    healthcheck:
      test: wget -qO- localhost:3000 | grep "Database Repository" || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-gateway-service:
    restart: "no"
    container_name: dbrepo-gateway-service
    hostname: gateway-service
    image: docker.io/nginx:1.25-alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dbrepo-gateway-service/dbrepo.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      dbrepo-analyse-service:
        condition: service_healthy
      dbrepo-auth-service:
        condition: service_healthy
      dbrepo-broker-service:
        condition: service_healthy
      dbrepo-metadata-service:
        condition: service_healthy
      dbrepo-search-db:
        condition: service_healthy
      dbrepo-ui:
        condition: service_healthy
    logging:
      driver: json-file

  # service not part of dbrepo system (but for developing)
  dbrepo-search-db-dashboard:
    restart: "no"
    container_name: dbrepo-search-db-dashboard
    hostname: search-db-dashboard
    image: docker.io/opensearchproject/opensearch-dashboards:2.10.0
    ports:
      - "5601:5601"
    volumes:
      - ./dbrepo-search-db/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    depends_on:
      dbrepo-search-db:
        condition: service_healthy
    logging:
      driver: json-file

  dbrepo-search-service-init:
    restart: "no"
    container_name: dbrepo-search-service-init
    hostname: search-service-init
    image: dbrepo-search-service-init:latest
    build:
      context: ./dbrepo-search-service/init
      network: host
    environment:
      GATEWAY_SERVICE_ENDPOINT: ${GATEWAY_SERVICE_ENDPOINT:-http://gateway-service}
      OPENSEARCH_HOST: ${OPENSEARCH_HOST:-search-db}
      OPENSEARCH_PORT: ${OPENSEARCH_PORT:-9200}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-admin}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-admin}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    depends_on:
      dbrepo-search-db:
        condition: service_healthy
    logging:
      driver: json-file

  dbrepo-storage-service:
    restart: "no"
    container_name: dbrepo-storage-service
    hostname: storage-service
    image: docker.io/chrislusf/seaweedfs:3.59
    command: [ "server", "-dir=/data", "-s3", "-s3.port=9000", "-s3.config=/app/s3_config.json", "-metricsPort=9091" ]
    volumes:
      - ./dbrepo-storage-service/s3_config.json:/app/s3_config.json
      - storage-service-data:/data
    ports:
      - "9000:9000"
    healthcheck:
      test: echo "cluster.check" | weed shell | grep "checking master.*ok" || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-storage-service-init:
    restart: "no"
    container_name: dbrepo-storage-service-init
    hostname: storage-service-init
    image: dbrepo-storage-service-init:latest
    build:
      context: ./dbrepo-storage-service/init
      network: host
    environment:
      SEAWEEDFS_ENDPOINT: "${STORAGE_SEAWEEDFS_ENDPOINT:-storage-service:9333}"
    depends_on:
      dbrepo-storage-service:
        condition: service_healthy
    logging:
      driver: json-file

  dbrepo-upload-service:
    restart: "no"
    container_name: dbrepo-upload-service
    hostname: upload-service
    image: docker.io/tusproject/tusd:v2.4.0
    command:
      - "--base-path=/api/upload/files/"
      - "-s3-endpoint=${STORAGE_ENDPOINT:-http://storage-service:9000}"
      - "-s3-bucket=dbrepo-upload"
    environment:
      AWS_ACCESS_KEY_ID: "${STORAGE_USERNAME:-seaweedfsadmin}"
      AWS_SECRET_ACCESS_KEY: "${STORAGE_PASSWORD:-seaweedfsadmin}"
      AWS_REGION: "${STORAGE_REGION_NAME:-default}"
    depends_on:
      dbrepo-storage-service:
        condition: service_healthy
    healthcheck:
      test: wget -qO- localhost:8080/metrics | grep "tusd" || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: json-file

  dbrepo-data-service:
    restart: "no"
    container_name: dbrepo-data-service
    hostname: data-service
    image: dbrepo-data-service:latest
    build:
      context: ./dbrepo-data-service
      network: host
    ports:
      - "9093:8080"
    volumes:
      - "${SHARED_VOLUME:-/tmp}:/tmp"
    environment:
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}"
      ADMIN_USERNAME: "${ADMIN_USERNAME:-admin}"
      AUTH_SERVICE_ADMIN: ${AUTH_SERVICE_ADMIN:-fda}
      AUTH_SERVICE_ADMIN_PASSWORD: ${AUTH_SERVICE_ADMIN_PASSWORD:-fda}
      AUTH_SERVICE_CLIENT: ${AUTH_SERVICE_CLIENT:-dbrepo-client}
      AUTH_SERVICE_CLIENT_SECRET: ${AUTH_SERVICE_CLIENT:-MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG}
      AUTH_SERVICE_ENDPOINT: ${AUTH_SERVICE_ENDPOINT:-http://auth-service:8080}
      BROKER_EXCHANGE_NAME: ${BROKER_EXCHANGE_NAME:-dbrepo}
      BROKER_QUEUE_NAME: ${BROKER_QUEUE_NAME:-dbrepo}
      BROKER_HOST: "${BROKER_ENDPOINT:-broker-service}"
      BROKER_PASSWORD: ${BROKER_PASSWORD:-fda}
      BROKER_PORT: ${BROKER_PORT:-5672}
      BROKER_SERVICE_ENDPOINT: ${BROKER_SERVICE_ENDPOINT:-http://gateway-service/admin/broker}
      BROKER_USERNAME: ${BROKER_USERNAME:-fda}
      BROKER_VIRTUALHOST: "${BROKER_VIRTUALHOST:-dbrepo}"
      CONNECTION_TIMEOUT: ${CONNECTION_TIMEOUT:-60000}
      EXCHANGE_NAME: ${EXCHANGE_NAME:-dbrepo}
      METADATA_SERVICE_ENDPOINT: ${METADATA_SERVICE_ENDPOINT:-http://gateway-service}
      GRANT_DEFAULT_READ: "${GRANT_DEFAULT_READ:-SELECT}"
      GRANT_DEFAULT_WRITE: "${GRANT_DEFAULT_WRITE:-SELECT, CREATE, CREATE VIEW, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, INDEX, TRIGGER, INSERT, UPDATE, DELETE}"
      JWT_PUBKEY: "${JWT_PUBKEY:-MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqqnHQ2BWWW9vDNLRCcxD++xZg/16oqMo/c1l+lcFEjjAIJjJp/HqrPYU/U9GvquGE6PbVFtTzW1KcKawOW+FJNOA3CGo8Q1TFEfz43B8rZpKsFbJKvQGVv1Z4HaKPvLUm7iMm8Hv91cLduuoWx6Q3DPe2vg13GKKEZe7UFghF+0T9u8EKzA/XqQ0OiICmsmYPbwvf9N3bCKsB/Y10EYmZRb8IhCoV9mmO5TxgWgiuNeCTtNCv2ePYqL/U0WvyGFW0reasIK8eg3KrAUj8DpyOgPOVBn3lBGf+3KFSYi+0bwZbJZWqbC/Xlk20Go1YfeJPRIt7ImxD27R/lNjgDO/MwIDAQAB}"
      LOG_LEVEL: ${LOG_LEVEL:-trace}
      MIN_CONCURRENT_CONSUMERS: ${MIN_CONCURRENT_CONSUMERS:-1}
      MAX_CONCURRENT_CONSUMERS: ${MAX_CONCURRENT_CONSUMERS:-5}
      QUEUE_NAME: ${QUEUE_NAME:-dbrepo}
      REQUEUE_REJECTED: ${REQUEUE_REJECTED:-false}
      ROUTING_KEY: "${ROUTING_KEY:-dbrepo.#}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID:-seaweedfsadmin}"
      S3_ENDPOINT: "${S3_ENDPOINT:-http://storage-service:9000}"
      S3_EXPORT_BUCKET: "${S3_EXPORT_BUCKET:-dbrepo-download}"
      S3_FILE_PATH: "${S3_FILE_PATH:-/tmp}"
      S3_IMPORT_BUCKET: "${S3_IMPORT_BUCKET:-dbrepo-upload}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:-seaweedfsadmin}"
    healthcheck:
      test: curl -sSL localhost:8080/actuator/health/liveness | grep 'UP' || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
    depends_on:
      dbrepo-data-db:
        condition: service_healthy
    logging:
      driver: json-file
