site_name: Database Repository
site_url: https://www.ifs.tuwien.ac.at/infrastructures/dbrepo/1.4.5/
repo_url: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
repo_name: fda-services
site_author: Research Unit Data Science, Technische Universit&auml;t Wien
copyright: CC-BY 4.0 Technische Universit&auml;t Wien & Universit&auml;t Wien
docs_dir: .docs
nav:
  - Get Started:
    - Welcome to DBRepo: index.md
    - Why use DBRepo: why.md
    - Help with DBRepo: help.md
    - Installation: installation.md
    - Kubernetes: kubernetes.md
    - Migration Guide: migration.md
    - contributing.md
  - Concepts:
    - Overview: concepts/index.md
    - Authentication: concepts/authentication.md
    - Databases: concepts/databases.md
    - Messaging: concepts/messaging.md
    - Monitoring: concepts/monitoring.md
    - Persistent Identifier: concepts/pid.md
    - Search: concepts/search.md
    - Storage: concepts/storage.md
    - User Interface: concepts/ui.md
  - API:
    - Overview: api/index.md
    - Databases:
      - Data Database: api/data-db.md
      - Metadata Database: api/metadata-db.md
    - SDK:
      - Python Library: api/python.md
      - Swagger / OpenAPI: api/open-api.md
    - Services:
      - Analyse Service: api/analyse-service.md
      - Auth Service: api/auth-service.md
      - Broker Service: api/broker-service.md
      - Data Service: api/data-service.md
      - Gateway Service: api/gateway-service.md
      - Identity Service: api/identity-service.md
      - Metadata Service: api/metadata-service.md
      - Search Service: api/search-service.md
      - Storage Service: api/storage-service.md
      - Upload Service: api/upload-service.md
    - UI:
      - Customization: api/ui.md
  - Examples:
    - Air Quality Data: examples/air.md
    - COVID-19 Data: examples/covid-19.md
    - Hazard Data: examples/hazard.md
    - Industry 4.0 Power Data: examples/power.md
    - Survey Data: examples/survey.md
    - Music-ML Data: examples/music.md
    - Transportation Data: examples/transportation.md
    - XPS Data: examples/xps-data.md
  - publications.md
  - contact.md
extra_css:
  - stylesheets/extra.css
theme:
  favicon: images/favicon.ico
  custom_dir: .docs/overrides
  font:
    text: IBM Plex Serif
    code: IBM Plex Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - content.code.annotate
    - content.code.copy
    - content.tooltips
  icon:
    logo: material/database-search
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      font:
        code: Roboto Mono
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      font:
        code: Roboto Mono
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: True
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - .docs/overrides/.icons
extra:
  homepage: https://www.ifs.tuwien.ac.at/infrastructures/dbrepo/
  version:
    default: 1.4.3
    provider: mike
  social:
    - icon: simple/artifacthub
      link: https://artifacthub.io/packages/helm/dbrepo/dbrepo
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/search?q=dbrepo
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/dbrepo/
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
