site_name: Database Repository
repo_url: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
repo_name: fda-services
site_author: Research Unit Data Science, Technische Universit&auml;t Wien
copyright: CC-BY 4.0 Technische Universit&auml;t Wien & Universit&auml;t Wien
docs_dir: .docs
nav:
  - Home: index.md
  - Deployment:
    - Docker Compose: deployment-docker-compose.md
    - Kubernetes: deployment-helm.md
  - System:
    - Overview: system-overview.md
    - Services:
      - Analyse Service: system-services-analyse.md
      - Authentication Service: system-services-authentication.md
      - Broker Service: system-services-broker.md
      - Data Service: system-services-data.md
      - Gateway Service: system-services-gateway.md
      - Metadata Service: system-services-metadata.md
      - Search Service: system-services-search.md
      - Storage Service: system-services-storage.md
      - Upload Service: system-services-upload.md
    - Databases:
      - Authentication Database: system-databases-authentication.md
      - Data Database: system-databases-data.md
      - Metadata Database: system-databases-metadata.md
      - Search Database: system-databases-search.md
    - Other:
      - User Interface: system-other-ui.md
      - Search Database Dashboard: system-other-search-dashboard.md
    - Operation:
      - Actuator: operation-actuator.md
      - Prometheus: operation-prometheus.md
  - Usage:
    - Overview: usage-overview.md
    - Python Library: usage-python.md
    - Services:
      - Authentication Service: usage-authentication.md
      - Storage Service: usage-storage.md
      - Upload Service: usage-upload.md
  - Development:
    - Overview: dev-overview.md
    - Application Guide: dev-guide-app.md
    - Infrastructure Guide: dev-guide-infra.md
  - publications.md
  - contact.md
extra_css:
  - stylesheets/extra.css
theme:
  favicon: images/favicon.ico
  custom_dir: .docs/overrides
  font:
    text: IBM Plex Serif
    code: IBM Plex Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - content.code.annotate
    - content.code.copy
    - content.tooltips
  icon:
    logo: material/database-search
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      font:
        code: Roboto Mono
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      font:
        code: Roboto Mono
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: True
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - .docs/overrides/.icons
extra:
  homepage: https://www.ifs.tuwien.ac.at/infrastructures/dbrepo/
  version:
    default: 1.4.3
    provider: mike
  social:
    - icon: simple/artifacthub
      link: https://artifacthub.io/packages/helm/dbrepo/dbrepo
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/search?q=dbrepo
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/dbrepo/
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
