application:
  title: DBRepo
  version: '@project.version@'
spring:
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: "${METADATA_DB:dbrepo}"
        jdbc:
          time_zone: UTC
  application:
    name: upload-service
  main:
    banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
server:
  port: 8080
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: "${LOG_LEVEL:info}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
