hostname: s155.datalab.tuwien.ac.at
gateway: https://s155.datalab.tuwien.ac.at

metadatadb:
  enabled: true
  rootUser:
    user: root
    password: da19c7cf5c0deba7bd47c174a0eb273b
  galera:
    mariabackup:
      user: mariabackup
      password: 9e447eeaf3e4b6aa26ea01582f0e8a54
  persistence:
    enabled: true

authservice:
  enabled: true
  auth:
    adminUser: admin
    adminPassword: ea72038fa14b968fc0ed09e182ecf624
  postgresql:
    auth:
      postgresPassword: 129d5b888b8df271fa482da39f15c513
  jwt:
    pubkey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqqnHQ2BWWW9vDNLRCcxD++xZg/16oqMo/c1l+lcFEjjAIJjJp/HqrPYU/U9GvquGE6PbVFtTzW1KcKawOW+FJNOA3CGo8Q1TFEfz43B8rZpKsFbJKvQGVv1Z4HaKPvLUm7iMm8Hv91cLduuoWx6Q3DPe2vg13GKKEZe7UFghF+0T9u8EKzA/XqQ0OiICmsmYPbwvf9N3bCKsB/Y10EYmZRb8IhCoV9mmO5TxgWgiuNeCTtNCv2ePYqL/U0WvyGFW0reasIK8eg3KrAUj8DpyOgPOVBn3lBGf+3KFSYi+0bwZbJZWqbC/Xlk20Go1YfeJPRIt7ImxD27R/lNjgDO/MwIDAQAB"
  client:
    id: dbrepo-client
    secret: MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG
  setupJob:
    image:
      name: registry.datalab.tuwien.ac.at/dbrepo/auth-service-init:1.6.3rc7
  persistence:
    enabled: true

brokerservice:
  enabled: true
  ldap:
    bindpw: b8534187c9adf9618e7bd1c79c7f4639

identityservice:
  enabled: true
  global:
    adminUser: admin
    adminPassword: b8534187c9adf9618e7bd1c79c7f4639
  users: admin
  userPasswords: ea72038fa14b968fc0ed09e182ecf624

datadb:
  enabled: true
  rootUser:
    user: root
    password: fdf8578499b2083eb3aa03a861ac7912
  galera:
    mariabackup:
      user: mariabackup
      password: ef60e32e3217525474635cd28422c829
  replicaCount: 3
  persistence:
    enabled: true

searchdb:
  enabled: true
  security:
    enabled: false
  extraEnvs:
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"
  persistence:
    enabled: true

analyseservice:
  enabled: true
  image:
    name: registry.datalab.tuwien.ac.at/dbrepo/analyse-service:1.6.3rc7

metadataservice:
  enabled: true
  image:
    name: registry.datalab.tuwien.ac.at/dbrepo/metadata-service:1.6.3rc7
  admin:
    email: noreply@example.com
  deletedRecord: permanent
  repositoryName: Database Repository
  granularity: YYYY-MM-DDThh:mm:ssZ
  datacite:
    enabled: false
    url: https://api.datacite.org
    prefix: ""
    username: ""
    password: ""

dataservice:
  enabled: true
  image:
    name: registry.datalab.tuwien.ac.at/dbrepo/data-service:1.6.3rc7
  rabbitmq:
    consumer:
      username: admin
      password: ea72038fa14b968fc0ed09e182ecf624
  s3:
    auth:
      username: a45e7a77607a8906e92237f00ea72f58
      password: e2c4303dcbfd3a2c606fe30d19fcb82b
    filePath: /s3

searchservice:
  enabled: true
  image:
    name: registry.datalab.tuwien.ac.at/dbrepo/search-service:1.6.3rc7
  init:
    image:
      name: registry.datalab.tuwien.ac.at/dbrepo/search-service-init:1.6.3rc7

storageservice:
  enabled: true
  init:
    image:
      name: registry.datalab.tuwien.ac.at/dbrepo/storage-service-init:1.6.3rc7

uploadservice:
  enabled: true

dashboardservice:
  enabled: true

metricdb:
  enabled: true
  server:
    rbac:
      create: false

ui:
  enabled: true
  image:
    name: registry.datalab.tuwien.ac.at/dbrepo/ui:1.6.3rc9
  public:
    api:
      client: https://s155.datalab.tuwien.ac.at
      server: https://s155.datalab.tuwien.ac.at
    title: "Database Repository"
    logo: "https://ec.tuwien.ac.at/~weise/images/DS_white_hiRes.png"
    icon: "https://ec.tuwien.ac.at/~weise/images/favicon.ico"
    touch: "https://ec.tuwien.ac.at/~weise/images/DS-icon_white_hiRes.png"
    broker:
      host: s155.datalab.tuwien.ac.at
      extra: "128.130.0.0/15"
    database:
      extra: "128.130.0.0/15"
    pid:
      default:
        publisher: "TU Wien"
    doi:
      enabled: false
      endpoint: https://doi.org
  extraVolumes: [ ]
  #  - name: images-map
  #    configMap:
  #      name: ui-config
  extraVolumeMounts: [ ]
  #  - name: images-map
  #    mountPath: /static/logo.svg
  #    subPath: logo.svg

gatewayservice:
  enabled: true

ingress:
  enabled: true
  className: nginx
  tls:
    enabled: true
    secretName: ingress-cert
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
#    nginx.ingress.kubernetes.io/whitelist-source-range: 128.130.0.0/15
