#!/bin/sh
mysql --user="root" --password="${METADATA_PASSWORD}" --database="${METADATA_DB}" << EOF
CREATE USER '${MARIADB_USERNAME}' IDENTIFIED BY '${MARIADB_PASSWORD}';
GRANT ALL PRIVILEGES ON '${METADATA_DB}' TO '${MARIADB_USERNAME}';
EOF