#!/bin/sh
mysql --user="root" --password="${METADATA_PASSWORD}" --database="${METADATA_DB}" << EOF
CREATE USER '${MARIADB_USERNAME}' IDENTIFIED BY '${MARIADB_PASSWORD}';
GRANT SELECT ON ${METADATA_DB}.* TO '${MARIADB_USERNAME}';
FLUSH PRIVILEGES;
EOF