{{- if .Values.analyseService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyse-service
  namespace: {{ .Values.namespace }}
  labels:
    app: analyse-service
    service: analyse-service
spec:
  replicas: {{ .Values.analyseService.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: analyse-service
      service: analyse-service
  template:
    metadata:
      labels:
        app: analyse-service
        service: analyse-service
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
      containers:
        - name: analyse-service
          image: {{ .Values.analyseService.image.name }}
          imagePullPolicy: {{ .Values.analyseService.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            seccompProfile:
              type: {{ .Values.analyseService.profileType | default "RuntimeDefault" }}
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: analyse-service-secret
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:8080/health | grep 'UP' || exit 1"
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:8080/health | grep 'UP' || exit 1"
            initialDelaySeconds: 10
            periodSeconds: 30
{{- end }}
