{{- if .Values.analyseservice.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyse-service
  namespace: {{ .Values.namespace }}
  labels:
    app: analyse-service
    service: analyse-service
spec:
  replicas: {{ .Values.analyseservice.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: analyse-service
      service: analyse-service
  template:
    metadata:
      labels:
        app: analyse-service
        service: analyse-service
    spec:
      {{- if .Values.analyseservice.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.analyseservice.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: analyse-service
          image: {{ .Values.analyseservice.image.name }}
          imagePullPolicy: {{ .Values.analyseservice.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.analyseservice.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.analyseservice.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: analyse-service-secret
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:8080/health | grep 'UP' || exit 1"
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:8080/health | grep 'UP' || exit 1"
            initialDelaySeconds: 10
            periodSeconds: 30
          {{- if .Values.analyseservice.resources }}
          resources: {{- toYaml .Values.analyseservice.resources | nindent 12 }}
          {{- end }}
{{- end }}
