{{- if .Values.analyseService.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: analyse-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  ADMIN_USERNAME: "{{ .Values.admin.username }}"
  ADMIN_PASSWORD: "{{ .Values.admin.password }}"
  AUTH_SERVICE_ADMIN: "{{ .Values.authservice.auth.adminUser }}"
  AUTH_SERVICE_ADMIN_PASSWORD: "{{ .Values.authservice.auth.adminPassword }}"
  AUTH_SERVICE_CLIENT: "{{ .Values.authservice.client.id }}"
  AUTH_SERVICE_CLIENT_SECRET: "{{ .Values.authservice.client.secret }}"
  AUTH_SERVICE_HOST: "{{ .Values.authservice.endpoint }}"
  GATEWAY_SERVICE_ENDPOINT: "{{ .Values.gateway }}"
  JWT_PUBKEY: "{{ .Values.authservice.jwt.pubkey }}"
  LOG_LEVEL: "{{ ternary "DEBUG" "INFO" .Values.analyseService.image.debug }}"
  S3_ACCESS_KEY_ID: "{{ .Values.storageservice.s3.auth.username }}"
  S3_ENDPOINT: "{{ .Values.analyseService.s3.endpoint }}"
  S3_EXPORT_BUCKET: "{{ .Values.storageservice.s3.bucket.export }}"
  S3_IMPORT_BUCKET: "{{ .Values.storageservice.s3.bucket.import }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.storageservice.s3.auth.password }}"
{{- end }}
