{{- if .Values.analyseservice.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: analyse-service
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    service: analyse-service
spec:
  type: ClusterIP
  ports:
    - name: "flask"
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    service: analyse-service
{{- end }}
