{{- if .Values.authservice.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  AUTH_SERVICE_ADMIN: "{{ .Values.authservice.auth.adminUser }}"
  AUTH_SERVICE_ADMIN_PASSWORD: "{{ .Values.authservice.auth.adminPassword }}"
  AUTH_SERVICE_ENDPOINT: "{{ .Values.authservice.endpoint }}"
  IDENTITY_SERVICE_ENDPOINT: "{{ .Values.identityservice.endpoint }}"
  IDENTITY_SERVICE_ADMIN_DN: "cn={{ .Values.identityservice.global.adminUser }},{{ .Values.identityservice.global.ldapDomain }}"
  IDENTITY_SERVICE_ADMIN_PASSWORD: "{{ .Values.identityservice.global.adminPassword }}"
  IDENTITY_SERVICE_ROOT: "{{ .Values.identityservice.global.ldapDomain }}"
  KC_LOG: "console,file"
  KC_LOG_FILE_JSON_FORMAT: "ecs"
  KC_LOG_FILE_LEVEL: "debug"
  KC_LOG_FILE_OUTPUT: "json"
  KEYCLOAK_HOSTNAME: "{{ .Values.gateway }}"
  KEYCLOAK_HOSTNAME_ADMIN: "{{ .Values.gateway }}"
  KEYCLOAK_PROXY_HEADERS: "xforwarded"
  LDAP_ROOT: "{{ .Values.identityservice.global.ldapDomain }}"
  LDAP_ADMIN_DN: "cn={{ .Values.identityservice.global.adminUser }},{{ .Values.identityservice.global.ldapDomain }}"
  LDAP_ADMIN_PASSWORD: "{{ .Values.identityservice.global.adminPassword }}"
  METADATA_DB: "{{ .Values.metadatadb.db.name }}"
  METADATA_DB_PASSWORD: "{{ .Values.metadatadb.rootUser.password }}"
  METADATA_USERNAME: "{{ .Values.metadatadb.rootUser.user }}"
  READONLY_USERNAME: "{{ .Values.datadb.db.user }}"
  READONLY_PASSWORD: "{{ .Values.datadb.db.password }}"
  SYSTEM_USERNAME: "{{ .Values.identityservice.users }}"
  SYSTEM_PASSWORD: "{{ .Values.identityservice.userPasswords }}"
{{- end }}
