{{- if .Values.authservice.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: auth-db-appuser-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  username: "{{ .Values.authservice.externalDatabase.user }}"
  password: "{{ .Values.authservice.externalDatabase.password }}"
{{- end }}
