{{- if .Values.authservice.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  db-host: "{{ .Values.authdb.host }}"
  db-port: "{{ .Values.authdb.port }}"
  db-name: "{{ .Values.authdb.postgresql.database }}"
  db-username: "{{ .Values.authdb.postgresql.username }}"
  db-password: "{{ .Values.authdb.postgresql.password }}"
{{- end }}
