{{- if .Values.authservice.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: auth-service-setup-job
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  backoffLimit: {{ .Values.authservice.setupJob.backoffLimit | default "10" }}
  template:
    metadata:
      name: auth-service-setup-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: {{ .Values.authservice.setupJob.image.name }}
          imagePullPolicy: {{ .Values.authservice.setupJob.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.authservice.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.authservice.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: auth-service-secret
          {{- if .Values.authservice.setupJob.resources }}
          resources: {{- toYaml .Values.authservice.setupJob.resources | nindent 12 }}
          {{- else if ne .Values.authservice.setupJob.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.authservice.setupJob.resourcesPreset) | nindent 12 }}
          {{- end }}
{{- end }}
