{{ if .Values.authservice.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: auth-db
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  instances: {{ .Values.authservice.externalDatabase.replicaCount }}
  imageName: {{ .Values.authservice.externalDatabase.image }}
  bootstrap:
    initdb:
      # app is an unprivileged user
      database: {{ .Values.authservice.externalDatabase.database }}
      owner: {{ .Values.authservice.externalDatabase.user }}
      secret:
        name: auth-db-appuser-secret
  postgresql:
    parameters:
      shared_buffers: "1GB"
  resources:
    requests:
      cpu: 50m
      memory: 1Gi
    limits:
      cpu: 200m
      memory: 4Gi
  storage:
    size: 1Gi
{{- end }}