{{- if .Values.brokerservice.enabled }}
{{- if .Values.global.loggingSidecar.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-service-config
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush                 5
        Daemon                Off
        Log_Level             debug
        Parsers_File          /opt/bitnami/fluent-bit/conf/parsers.conf
    [INPUT]
        Name                  tail
        Tag                   *
        Path                  /opt/bitnami/rabbitmq/var/log/rabbitmq/*.log
        Parser                rabbitmq
        Mem_Buf_Limit         5MB
        Buffer_Chunk_size     32k
        Buffer_Max_size       32k
    [FILTER]
        Name                  modify
        Match                 *
        Rename                time @timestamp
        Rename                level log.level
        Rename                pid process.pid
        Rename                msg message
        Add                   service.name broker-service
    {{- include "dbrepo.logging.sidecarOpensearchOutput" . | nindent 4 }}
    {{- include "dbrepo.logging.sidecarMetricsOutput" . | nindent 4 }}
  parsers.conf: |-
    [PARSER]
        Name                  rabbitmq
        Format                json
        Time_Key              time
        Time_Format           %Y-%m-%d %H:%M:%S.%L
        Time_Keep             On
{{- end }}
{{- end }}