{{- if .Values.brokerservice.enabled }}
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: broker-service
  namespace: {{ include "common.names.namespace" . | quote }}
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "dbrepo"
spec:
  replicas: {{ .Values.brokerservice.replicaCount }}
  rabbitmq:
    additionalConfig: |
      default_user = {{ .Values.brokerservice.auth.username }}
      default_pass = {{ .Values.brokerservice.auth.password }}
  {{- if .Values.brokerservice.resources }}
  resources:
    {{- .Values.brokerservice.resources | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.brokerservice.persistence.enabled }}
  persistence:
    storage: {{ .Values.brokerservice.persistence.size }}
  {{- end }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: dbrepo
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  name: {{ .Values.brokerservice.virtualHost }}
  rabbitmqClusterReference:
    name: broker-service
    namespace: {{ include "common.names.namespace" . | quote }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: dbrepo-exchange
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  name: {{ .Values.brokerservice.exchangeName }}
  type: topic
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: broker-service
    namespace: {{ include "common.names.namespace" . | quote }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: dbrepo-queue
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  name: {{ .Values.brokerservice.queueName }}
  type: quorum
  vhost: {{ .Values.brokerservice.virtualHost }}
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: broker-service
    namespace: {{ include "common.names.namespace" . | quote }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: dbrepo-exchange-queue-binding
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  source: {{ .Values.brokerservice.exchangeName }}
  destination: {{ .Values.brokerservice.queueName }}
  destinationType: queue
  routingKey: {{ .Values.brokerservice.routingKey }}
  rabbitmqClusterReference:
    name: broker-service
    namespace: {{ include "common.names.namespace" . | quote }}
{{- end }}
