{{- if .Values.brokerservice.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: broker-service-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  default_user.conf: |
    default_user = {{ .Values.brokerservice.auth.username }}
    default_pass = {{ .Values.brokerservice.auth.password }}
    password: {{ .Values.brokerservice.auth.username }}
    username: {{ .Values.brokerservice.auth.password }}
{{- end }}
