---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-service-definitions
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  definitions.json: |-
    {
      "bindings": [
        {
          "arguments": {},
          "destination": "dbrepo",
          "destination_type": "queue",
          "routing_key": "{{ .Values.brokerservice.routingKey }}",
          "source": "{{ .Values.brokerservice.exchangeName }}",
          "vhost": "{{ .Values.brokerservice.virtualHost }}"
        }
      ],
      "exchanges": [
        {
          "arguments": {},
          "auto_delete": false,
          "durable": true,
          "name": "{{ .Values.brokerservice.exchangeName }}",
          "type": "topic",
          "vhost": "{{ .Values.brokerservice.virtualHost }}"
        }
      ],
      "global_parameters": [],
      "parameters": [],
      "permissions": [
        {
          "user": "{{ .Values.brokerservice.auth.username }}",
          "vhost": "{{ .Values.brokerservice.virtualHost }}",
          "configure": ".*",
          "read": ".*",
          "write": ".*"
        }
      ],
      "policies": [],
      "queues": [
        {
          "arguments": {
            "x-queue-type": "quorum"
          },
          "auto_delete": false,
          "durable": true,
          "name": "dbrepo",
          "type": "quorum",
          "vhost": "{{ .Values.brokerservice.virtualHost }}"
        }
      ],
      "rabbit_version": "3.10.25",
      "rabbitmq_version": "3.10.25",
      "topic_permissions": [],
      "users": [
        {
          "name": "{{ .Values.brokerservice.auth.username }}",
          "password_hash": "{{ .Values.brokerservice.auth.passwordHash }}",
          "tags": [
            "administrator"
          ]
        }
      ],
      "vhosts": [
        {
          "limits": [],
          "metadata": {
            "description": "Default virtual host",
            "tags": []
          },
          "name": "{{ .Values.brokerservice.virtualHost }}"
        }
      ]
    }
