{{- if .Values.consumerservice.enabled }}
{{ $issuerUri := printf "%s/realms/dbrepo" .Values.hostname }}
{{ $jwkUri := printf "%s/realms/dbrepo/protocol/openid-connect/certs" .Values.hostname }}
---
apiVersion: v1
kind: Secret
metadata:
  name: consumer-service-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  AUTH_SERVICE_ADMIN: "{{ .Values.authservice.auth.adminUser }}"
  AUTH_SERVICE_ADMIN_PASSWORD: "{{ .Values.authservice.auth.adminPassword }}"
  AUTH_SERVICE_CLIENT: "{{ .Values.authservice.client.id }}"
  AUTH_SERVICE_CLIENT_SECRET: "{{ .Values.authservice.client.secret }}"
  AUTH_SERVICE_ENDPOINT: "{{ .Values.authservice.endpoint }}"
  BROKER_EXCHANGE_NAME: "{{ .Values.brokerservice.exchangeName }}"
  BROKER_HOST: "{{ .Values.brokerservice.host }}"
  BROKER_QUEUE_NAME: "{{ .Values.brokerservice.queueName }}"
  BROKER_PASSWORD: "{{ .Values.brokerservice.auth.password }}"
  BROKER_PORT: "{{ .Values.brokerservice.port }}"
  BROKER_SERVICE_ENDPOINT: "{{ .Values.brokerservice.endpoint }}"
  BROKER_USERNAME: "{{ .Values.brokerservice.auth.username }}"
  BROKER_VIRTUALHOST: "{{ .Values.brokerservice.virtualHost }}"
  CACHE_DB_PROVIDER: "{{ .Values.cachedb.flavor }}"
  CACHE_DB_HOST: "{{ .Values.cachedb.endpoint}}"
  CACHE_DB_PASSWORD: "{{ .Values.cachedb.auth.password }}"
  {{- if .Values.consumerservice.image.debug }}
  LOG_APPLICATION_LEVEL: "{{ ternary "DEBUG" "INFO" .Values.consumerservice.image.debug }}"
  {{- else }}
  LOG_APPLICATION_LEVEL: "INFO"
  {{- end }}
  OAUTH_ISSUER_URI: "{{ .Values.authservice.issuerUri | default $issuerUri }}"
  OAUTH_JWK_SET_URI: "{{ .Values.authservice.jwkUri | default $jwkUri }}"
  SYSTEM_USERNAME: "{{ .Values.username }}"
  SYSTEM_PASSWORD: "{{ .Values.password }}"
{{- end }}
