{{- if .Values.dataservice.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app: data-service
    service: data-service
spec:
  replicas: {{ .Values.dataservice.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: data-service
      service: data-service
  template:
    metadata:
      annotations:
        {{- if .Values.dataservice.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.dataservice.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels:
        app: data-service
        service: data-service
    spec:
      {{- if .Values.dataservice.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.dataservice.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: data-service
          image: {{ .Values.dataservice.image.name }}
          imagePullPolicy: {{ .Values.dataservice.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.dataservice.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.dataservice.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: empty-dir
              mountPath: /var/log/app/service/data
          envFrom:
            - secretRef:
                name: data-service-secret
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:8080/actuator/health/readiness | grep 'UP' || exit 1"
            initialDelaySeconds: 150
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:8080/actuator/health/liveness | grep 'UP' || exit 1"
            initialDelaySeconds: 30
            periodSeconds: 10
          {{- if .Values.dataservice.resources }}
          resources: {{- toYaml .Values.dataservice.resources | nindent 12 }}
          {{- else if ne .Values.dataservice.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.dataservice.resourcesPreset) | nindent 12 }}
          {{- end }}
        {{- if .Values.global.loggingSidecar.enabled }}
        - name: logging-agent
          image: {{ .Values.global.loggingSidecar.image.name }}
          imagePullPolicy: {{ .Values.metadataservice.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.metadataservice.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.metadataservice.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: logging-config
              mountPath: /opt/bitnami/fluent-bit/conf/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: empty-dir
              mountPath: /var/log/app/service/data
          livenessProbe:
            httpGet:
              port: 2021
            initialDelaySeconds: 150
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 2021
            initialDelaySeconds: 30
            periodSeconds: 10
          resources: {{- include "common.resources.preset" (dict "type" .Values.global.loggingSidecar.resourcesPreset) | nindent 12 }}
        {{- end }}
      volumes:
        {{- if .Values.global.loggingSidecar.enabled }}
        - name: logging-config
          configMap:
            name: data-service-config
        {{- end }}
        - name: empty-dir
          emptyDir: { }
{{- end }}
