{{ if .Values.datadb.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: data-db
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  instances: {{ .Values.datadb.replicaCount }}
  imageName: {{ .Values.datadb.image }}
  bootstrap:
    initdb:
      database: {{ .Values.datadb.appUser.user }}
      owner: {{ .Values.datadb.appUser.user }}
      secret:
        name: data-db-appuser-secret
  managed:
    roles:
      - name: {{ .Values.datadb.appUser.user }}
        ensure: present
        login: true
        superuser: true
        createdb: true
        createrole: true
  storage:
    size: 8Gi
{{- end }}