{{- if .Values.dataservice.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    service: data-service
spec:
  type: ClusterIP
  ports:
    - name: "data-service"
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    service: data-service
{{- end }}
