{{- if .Values.datadb.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: data-db-appuser-secret
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    cnpg.io/reload: "true"
stringData:
  username: "{{ .Values.datadb.appUser.user }}"
  password: "{{ .Values.datadb.appUser.password }}"
{{- end }}
