---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  ADMIN_EMAIL: "{{ .Values.metadataservice.admin.email }}"
  AUTH_SERVICE_ADMIN: "{{ .Values.authservice.auth.adminUser }}"
  AUTH_SERVICE_ADMIN_PASSWORD: "{{ .Values.authservice.auth.adminPassword }}"
  AUTH_SERVICE_CLIENT: "{{ .Values.authservice.client.id }}"
  AUTH_SERVICE_CLIENT_SECRET: "{{ .Values.authservice.client.secret }}"
  AUTH_SERVICE_ENDPOINT: "{{ .Values.authservice.endpoint }}"
  BROKER_EXCHANGE_NAME: "{{ .Values.brokerservice.exchangeName }}"
  BROKER_HOST: "{{ .Values.brokerservice.host }}"
  BROKER_QUEUE_NAME: "{{ .Values.brokerservice.queueName }}"
  BROKER_PASSWORD: "{{ .Values.dataservice.rabbitmq.consumer.password }}"
  BROKER_PORT: "{{ .Values.brokerservice.port }}"
  BROKER_ROUTING_KEY: "{{ .Values.brokerservice.routingKey }}"
  BROKER_SERVICE_ENDPOINT: "{{ .Values.brokerservice.endpoint }}"
  BROKER_USERNAME: "{{ .Values.dataservice.rabbitmq.consumer.username }}"
  BROKER_VIRTUALHOST: "{{ .Values.brokerservice.virtualHost }}"
  CONNECTION_TIMEOUT: "{{ .Values.brokerservice.connectionTimeout }}"
  GATEWAY_SERVICE_ENDPOINT: "{{ .Values.gateway }}"
  GRANT_DEFAULT_READ: "{{ .Values.dataservice.grant.read }}"
  GRANT_DEFAULT_WRITE: "{{ .Values.dataservice.grant.write }}"
  JWT_PUBKEY: "{{ .Values.authservice.jwt.pubkey }}"
  LOG_LEVEL: "{{ ternary "trace" "info" .Values.dataservice.image.debug }}"
  METADATA_SERVICE_ENDPOINT: "{{ .Values.metadataservice.endpoint }}"
  MIN_CONCURRENT_CONSUMERS: "{{ .Values.dataservice.rabbitmq.consumerConcurrentMin }}"
  MAX_CONCURRENT_CONSUMERS: "{{ .Values.dataservice.rabbitmq.consumerConcurrentMax }}"
  REQUEUE_REJECTED: "{{ .Values.dataservice.rabbitmq.requeueRejected }}"
  S3_ACCESS_KEY_ID: "{{ .Values.dataservice.s3.auth.username }}"
  S3_ENDPOINT: "{{ .Values.dataservice.s3.endpoint }}"
  S3_FILE_PATH: "{{ .Values.dataservice.s3.filePath }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.dataservice.s3.auth.password }}"
  S3_BUCKET: "{{ .Values.dataservice.s3.bucket }}"
  SYSTEM_USERNAME: "{{ .Values.identityservice.users }}"
  SYSTEM_PASSWORD: "{{ .Values.identityservice.userPasswords }}"
