---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  ADMIN_EMAIL: "{{ .Values.metadataservice.admin.email }}"
  ADMIN_USERNAME: "{{ .Values.admin.username }}"
  ADMIN_PASSWORD: "{{ .Values.admin.password }}"
  AUTH_SERVICE_ADMIN: "{{ .Values.authservice.auth.adminUser }}"
  AUTH_SERVICE_ADMIN_PASSWORD: "{{ .Values.authservice.auth.adminPassword }}"
  AUTH_SERVICE_CLIENT: "{{ .Values.authservice.client.id }}"
  AUTH_SERVICE_CLIENT_SECRET: "{{ .Values.authservice.client.secret }}"
  AUTH_SERVICE_HOST: "{{ .Values.authservice.endpoint }}"
  BROKER_EXCHANGE_NAME: "{{ .Values.brokerservice.exchangeName }}"
  BROKER_HOST: "{{ .Values.brokerservice.host }}"
  BROKER_QUEUE_NAME: "{{ .Values.brokerservice.queueName }}"
  BROKER_PASSWORD: "{{ .Values.brokerservice.auth.password }}"
  BROKER_PORT: "{{ .Values.brokerservice.port }}"
  BROKER_ROUTING_KEY: "{{ .Values.brokerservice.routingKey }}"
  BROKER_SERVICE_ENDPOINT: "{{ .Values.brokerservice.url }}"
  BROKER_USERNAME: "{{ .Values.brokerservice.auth.username }}"
  BROKER_VIRTUALHOST: "{{ .Values.brokerservice.virtualHost }}"
  CONNECTION_TIMEOUT: "{{ .Values.brokerservice.connectionTimeout }}"
  GATEWAY_SERVICE_ENDPOINT: "{{ .Values.gateway }}"
  GRANT_DEFAULT_READ: "{{ .Values.dataservice.grant.read }}"
  GRANT_DEFAULT_WRITE: "{{ .Values.dataservice.grant.write }}"
  DEFAULT_DATE_FORMAT_ID: "{{ .Values.dataservice.default.date }}"
  DEFAULT_TIME_FORMAT_ID: "{{ .Values.dataservice.default.time }}"
  DEFAULT_TIMESTAMP_FORMAT_ID: "{{ .Values.dataservice.default.timestamp }}"
  JWT_PUBKEY: "{{ .Values.authservice.jwt.pubkey }}"
  LOG_LEVEL: "{{ ternary "debug" "info" .Values.dataservice.image.debug }}"
  METADATA_SERVICE_ENDPOINT: "{{ .Values.metadataservice.endpoint }}"
  MIN_CONCURRENT_CONSUMERS: "{{ .Values.dataservice.consumerConcurrentMin }}"
  MAX_CONCURRENT_CONSUMERS: "{{ .Values.dataservice.consumerConcurrentMax }}"
  REQUEUE_REJECTED: "{{ .Values.dataservice.requeueRejected }}"
  S3_ACCESS_KEY_ID: "{{ .Values.dataservice.s3.auth.username }}"
  S3_ENDPOINT: "{{ .Values.dataservice.s3.endpoint }}"
  S3_EXPORT_BUCKET: "{{ .Values.dataservice.s3.bucket.export }}"
  S3_FILE_PATH: "{{ .Values.dataservice.s3.filePath }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.dataservice.s3.auth.password }}"
  S3_IMPORT_BUCKET: "{{ .Values.dataservice.s3.bucket.import }}"
