{{- if .Values.datadb.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: datadb-db-superuser-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  username: "{{ .Values.datadb.superUser.user }}"
  password: "{{ .Values.datadb.superUser.password }}"
{{- end }}
