{{- if .Values.datadb.enabled }}
{{- if .Values.datadb.pooler.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: data-db-pooler-rw
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  cluster:
    name: data-db
  instances: {{ .Values.datadb.pooler.replicaCount }}
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
{{- end }}
{{- end }}
