{{- if .Values.datadb.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-db-setup
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  1_grant-user.sql: |-
    GRANT SELECT ON *.* TO `{{ .Values.datadb.db.user }}`@`%`;
{{- end }}