{{- if .Values.datadb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: data-db-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  S3_ACCESS_KEY_ID: "{{ .Values.storageservice.s3.auth.adminAccessKeyId }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.storageservice.s3.auth.adminSecretAccessKey }}"
{{- end }}
