{{- if .Values.gatewayservice.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-setup
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  dbrepo.conf: |
    # This is required to proxy Grafana Live WebSocket connections.
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }

    server {
        listen 8080 default_server;
        server_name _;

        location /dashboard/ {
            rewrite  ^/dashboard/(.*)  /$1 break;
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://dashboard-service:3000;
            proxy_read_timeout      90;
        }

        # Proxy Grafana Live WebSocket connections.
        location /dashboard/api/live/ {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_set_header        Upgrade $http_upgrade;
            proxy_set_header        Connection $connection_upgrade;
            proxy_http_version      1.1;
            proxy_pass              http://dashboard-service:3000;
            proxy_read_timeout      90;
        }

        location /realms {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              https://auth-service;
            proxy_read_timeout      90;
        }

        location /resources {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              https://auth-service;
            proxy_read_timeout      90;
        }

        location /api/search {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://search-service;
            proxy_read_timeout      90;
        }

        location /api/upload {
    #         allow 128.130.0.0/16;
    #         deny all;
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_set_header        X-Forwarded-Host $host;
            proxy_pass              http://upload-service;
            proxy_read_timeout      90;
            # Disable request and response buffering
            proxy_request_buffering off;
            proxy_buffering         off;
            proxy_http_version      1.1;
        }

        location /api/analyse {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://analyse-service;
            proxy_read_timeout      90;
        }

        location ~ /api/database/([0-9]+)/table/([0-9]+)/(data|history|export) {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://data-service;
            proxy_read_timeout      90;
        }

        location ~ /api/database/([0-9]+)/view/([0-9]+)/(data|export) {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://data-service;
            proxy_read_timeout      90;
        }

        location ~ /api/database/([0-9]+)/view {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://metadata-service;
            proxy_read_timeout      90;
        }

        location ~ /api/database/([0-9]+)/subset {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://data-service;
            proxy_read_timeout      600;
        }

        location ~ /api/(database|concept|container|identifier|image|message|license|oai|ontology|unit|user) {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://metadata-service;
            proxy_read_timeout      90;
        }

        location ~ /pid/([0-9]+) {
            rewrite /pid/(.*) /api/identifier/$1 break;
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://metadata-service;
            proxy_read_timeout      90;
        }

        location /assets {
            root /etc/nginx/assets;
        }

        location / {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://ui;
            proxy_read_timeout      90;
        }
    }
{{- end }}