{{- if .Values.gatewayservice.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-setup
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  {{ (.Files.Glob "files/dbrepo.conf").AsConfig | nindent 2 }}
{{- end }}