{{- if .Values.gatewayservice.enabled }}
{{- if .Values.global.loggingSidecar.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  fluent-bit.conf: |-
    {{- include "dbrepo.logging.sidecarOpensearchService" . | nindent 4 }}
    [INPUT]
        Name                  tail
        Tag                   *
        Path                  /var/log/nginx/*.log
        Parser                docker
        Mem_Buf_Limit         5MB
        Buffer_Chunk_size     32k
        Buffer_Max_size       32k
    {{- include "dbrepo.logging.sidecarOpensearchOutput" . | nindent 4 }}
    {{- include "dbrepo.logging.sidecarMetricsOutput" . | nindent 4 }}
{{- end }}
{{- end }}