{{- if .Values.identityservice.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-service-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  LDAP_ADMIN_USERNAME: "{{ .Values.identityservice.global.adminUser }}"
  LDAP_ADMIN_PASSWORD: "{{ .Values.identityservice.global.adminPassword }}"
  LDAP_USERS: "{{ .Values.username }}"
  LDAP_PASSWORDS: "{{ .Values.password }}"
  LDAP_GROUP: ""
  LDAP_ROOT:  "{{ .Values.identityservice.global.ldapDomain }}"
  LDAP_ADMIN_DN: "cn={{ .Values.identityservice.global.adminUser }},{{ .Values.identityservice.global.ldapDomain }}"
{{- end }}
