---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbrepo-ingress-basic
  annotations: {{ toYaml .Values.ingress.annotations.basic | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /api/analyse
            pathType: Prefix
            backend:
              service:
                name: analyse-service
                port:
                  number: 80
          - path: /api/search
            pathType: Prefix
            backend:
              service:
                name: search-service
                port:
                  number: 80
          - path: /api/database/([0-9]+)/subset
            pathType: ImplementationSpecific
            backend:
              service:
                name: data-service
                port:
                  number: 80
          - path: /api/database/[0-9]+/table/[0-9]+/data
            pathType: ImplementationSpecific
            backend:
              service:
                name: data-service
                port:
                  number: 80
          - path: /api/database/[0-9]+/table/[0-9]+/history
            pathType: ImplementationSpecific
            backend:
              service:
                name: data-service
                port:
                  number: 80
          - path: /api/database/[0-9]+/table/[0-9]+/export
            pathType: ImplementationSpecific
            backend:
              service:
                name: data-service
                port:
                  number: 80
          - path: /api/database/[0-9]+/view/[0-9]+/data
            pathType: ImplementationSpecific
            backend:
              service:
                name: data-service
                port:
                  number: 80
          - path: /api/database/[0-9]+/view
            pathType: ImplementationSpecific
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/database
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/concept
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/container
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/identifier
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/image
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/message
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/license
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/oai
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/ontology
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/unit
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/upload
            pathType: Prefix
            backend:
              service:
                name: upload-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbrepo-ingress-admin
  annotations: {{ toYaml .Values.ingress.annotations.rewriteApi | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /api/broker
            pathType: Prefix
            backend:
              service:
                name: broker-service
                port:
                  number: 15672
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbrepo-ingress-rewrite-root
  annotations: {{ toYaml .Values.ingress.annotations.rewriteRoot | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /api/broker/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: broker-service
                port:
                  number: 15672
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbrepo-ingress-rewrite-root-secure
  annotations: {{ toYaml .Values.ingress.annotations.rewriteRootSecure | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /api/auth/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbrepo-ingress-pid
  annotations: {{ toYaml .Values.ingress.annotations.rewritePid | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /pid/[0-9]+
            pathType: ImplementationSpecific
            backend:
              service:
                name: metadata-service
                port:
                  number: 80