{{- if .Values.metadataservice.enabled }}
{{ $pidBase := printf "https://%s/pid/" .Values.hostname }}
---
apiVersion: v1
kind: Secret
metadata:
  name: metadata-service-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  ADMIN_EMAIL: "{{ .Values.metadataservice.admin.email }}"
  ANALYSE_SERVICE_ENDPOINT: "{{ .Values.analyseservice.endpoint }}"
  AUTH_SERVICE_ADMIN: "{{ .Values.authservice.auth.adminUser }}"
  AUTH_SERVICE_ADMIN_PASSWORD: "{{ .Values.authservice.auth.adminPassword }}"
  AUTH_SERVICE_CLIENT: "{{ .Values.authservice.client.id }}"
  AUTH_SERVICE_CLIENT_SECRET: "{{ .Values.authservice.client.secret }}"
  AUTH_SERVICE_ENDPOINT: "{{ .Values.authservice.endpoint }}"
  BASE_URL: "{{ .Values.gateway }}"
  BROKER_EXCHANGE_NAME: "{{ .Values.brokerservice.exchangeName }}"
  BROKER_HOST: "{{ .Values.brokerservice.host }}"
  BROKER_QUEUE_NAME: "{{ .Values.brokerservice.queueName }}"
  BROKER_PASSWORD: "{{ .Values.brokerservice.auth.password }}"
  BROKER_PORT: "{{ .Values.brokerservice.port }}"
  BROKER_SERVICE_ENDPOINT: "{{ .Values.brokerservice.endpoint }}"
  BROKER_USERNAME: "{{ .Values.brokerservice.auth.username }}"
  BROKER_VIRTUALHOST: "{{ .Values.brokerservice.virtualHost }}"
  CROSSREF_ENDPOINT: "{{ .Values.metadataservice.crossref.endpoint}}"
  DASHBOARD_SERVICE_ENDPOINT: "{{ .Values.dashboardservice.endpoint }}"
  DATA_SERVICE_ENDPOINT: "{{ .Values.dataservice.endpoint }}"
  DATACITE_URL: "{{ .Values.metadataservice.datacite.url }}"
  DATACITE_PREFIX: "{{ .Values.metadataservice.datacite.prefix | toString }}"
  DATACITE_USERNAME: "{{ .Values.metadataservice.datacite.username }}"
  DATACITE_PASSWORD: "{{ .Values.metadataservice.datacite.password }}"
  DELETED_RECORD: "{{ .Values.metadataservice.deletedRecord }}"
  GRANULARITY: "{{ .Values.metadataservice.granularity }}"
  JWT_PUBKEY: "{{ .Values.authservice.jwt.pubkey }}"
  {{- if .Values.metadataservice.image.debug }}
  LOG_LEVEL: "{{ ternary "DEBUG" "INFO" .Values.metadataservice.image.debug }}"
  {{- else }}
  LOG_LEVEL: "INFO"
  {{- end }}
  METADATA_DB: "{{ .Values.metadatadb.db.name }}"
  METADATA_HOST: "{{ .Values.metadatadb.host }}"
  METADATA_JDBC_EXTRA_ARGS: "{{ .Values.metadatadb.jdbcExtraArgs }}"
  METADATA_USERNAME: "{{ .Values.metadatadb.rootUser.user }}"
  METADATA_DB_PASSWORD: "{{ .Values.metadatadb.rootUser.password }}"
  PID_BASE: "{{ $pidBase }}"
  REPOSITORY_NAME: "{{ .Values.metadataservice.repositoryName }}"
  ROR_ENDPOINT: "{{ .Values.metadataservice.ror.endpoint}}"
  SEARCH_SERVICE_ENDPOINT: "{{ .Values.searchservice.endpoint }}"
  SPARQL_CONNECTION_TIMEOUT: "{{ .Values.metadataservice.sparql.connectionTimeout }}"
  SPRING_PROFILES_ACTIVE: "{{ ternary "doi" "" .Values.metadataservice.datacite.enabled }}"
  S3_ENDPOINT: "{{ .Values.metadataservice.s3.endpoint }}"
  S3_ACCESS_KEY_ID: "{{ .Values.storageservice.s3.auth.adminAccessKeyId }}"
  S3_BUCKET: "{{ .Values.metadataservice.s3.bucket }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.storageservice.s3.auth.adminSecretAccessKey }}"
  SYSTEM_USERNAME: "{{ .Values.identityservice.users }}"
  SYSTEM_PASSWORD: "{{ .Values.identityservice.userPasswords }}"
{{- end }}
