{{- if .Values.metadatadb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: metadata-db-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  METADATA_DB_PASSWORD: "{{ .Values.metadatadb.rootUser.password }}"
  METADATA_DB_REPL_PASSWORD: "{{ .Values.metadatadb.replication.password }}"
{{- end }}
