{{- if .Values.metadatadb.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-db-initdb-scripts
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  {{ (.Files.Glob "files/01-setup-schema.sql").AsConfig | nindent 2 }}
  {{- if .Values.datadb.enabled }}
  02-setup-data.sql: |-
    BEGIN;
    INSERT INTO mdb_containers (id, name, internal_name, image_id, host, port, privileged_username,
                                  privileged_password, readonly_username, readonly_password)
    VALUES ('6cfb3b8e-1792-4e46-871a-f3d103527203', 'registry.datalab.tuwien.ac.at/cloudnative-pg/postgresql:17.9', 'postgresql:17.9',
            'd79cb089-363c-488b-9717-649e44d8fcc5', 'metadata-db-rw', 5432, '{{ .Values.datadb.superUser.user }}',
            '{{ .Values.datadb.superUser.password }}', '{{ .Values.datadb.appUser.user }}',
            '{{ .Values.datadb.appUser.password }}');
    COMMIT;
  {{- end }}
{{- end }}
