{{- if .Values.metadataservice.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app: metadata-service
    service: metadata-service
spec:
  replicas: {{ .Values.metadataservice.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: metadata-service
      service: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
        service: metadata-service
    spec:
      {{- if .Values.metadataservice.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.metadataservice.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: metadata-service
          image: {{ .Values.metadataservice.image.name }}
          imagePullPolicy: {{ .Values.metadataservice.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.metadataservice.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.metadataservice.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: metadata-service-secret
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:8080/actuator/health/readiness | grep 'UP' || exit 1"
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:8080/actuator/health/liveness | grep 'UP' || exit 1"
            initialDelaySeconds: 30
            periodSeconds: 10
          {{- if .Values.metadataservice.resources }}
          resources: {{- toYaml .Values.metadataservice.resources | nindent 12 }}
          {{- end }}
{{- end }}
