{{- if .Values.metadatadb.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-db-setup
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  {{- with .Values.metadatadb.extraInitDbScripts }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
  {{ (.Files.Glob "files/01-setup-schema.sql").AsConfig | nindent 2 }}
  02-setup-data.sql: |
    BEGIN;
    INSERT INTO `mdb_containers` (name, internal_name, image_id, host, port, privileged_username, privileged_password)
    VALUES ('mariadb-galera:11.3.2-debian-12-r9', 'mariadb-galera:11.3.2-debian-12-r9', 1, 'data-db', 3306, '{{ .Values.datadb.rootUser.user }}', '{{ .Values.datadb.rootUser.password }}');
    COMMIT;
  {{ (.Files.Glob "files/my.cnf").AsConfig | nindent 2 }}
{{- end }}
