{{ if .Values.metadatadb.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: metadata-db
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  instances: {{ .Values.metadatadb.replicaCount }}
  imageName: {{ .Values.metadatadb.image }}
  bootstrap:
    initdb:
      # app is an unprivileged user
      database: dbrepo
      owner: {{ .Values.metadatadb.appUser.user }}
      secret:
        name: metadata-db-appuser-secret
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: metadata-db-initdb-scripts
            key: 01-setup-schema.sql
          - name: metadata-db-initdb-scripts
            key: 02-setup-data.sql
          - name: metadata-db-initdb-scripts
            key: 03-change-owner.sql
  storage:
    size: 1Gi
{{- end }}