{{- if .Values.metadataservice.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  namespace: {{ $.Values.namespace }}
  labels:
    service: metadata-service
spec:
  type: ClusterIP
  ports:
    - name: "metadata-service"
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    service: metadata-service
{{- end }}
