{{- if .Values.replicationservice.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: replication-service-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  BASE_URL: "https://{{ .Values.hostname }}"
  DATA_SERVICE_ENDPOINT: "{{ .Values.dataservice.endpoint }}"
  {{- if .Values.replicationservice.image.debug }}
  LOG_APPLICATION_LEVEL: "{{ ternary "DEBUG" "INFO" .Values.replicationservice.image.debug }}"
  {{- else }}
  LOG_APPLICATION_LEVEL: "INFO"
  {{- end }}
  METADATA_SERVICE_ENDPOINT: "{{ .Values.metadataservice.endpoint }}"
  REPLICATION_OUTBOX_BATCH_SIZE: "{{ .Values.replicationservice.outbox.batchSize }}"
  REPLICATION_OUTBOX_MAX_ATTEMPTS: "{{ .Values.replicationservice.outbox.maxAttempts }}"
  REPLICATION_OUTBOX_MAX_RETRY_DELAY_SECONDS: "{{ .Values.replicationservice.outbox.maxRetryDelaySeconds }}"
  REPLICATION_OUTBOX_PATH: "{{ .Values.replicationservice.outbox.path }}"
  REPLICATION_OUTBOX_RETRY_DELAY_MS: "{{ .Values.replicationservice.outbox.retryDelayMs }}"
  REPLICATION_OUTBOX_RETRY_DELAY_SECONDS: "{{ .Values.replicationservice.outbox.retryDelaySeconds }}"
  SYSTEM_USERNAME: "{{ .Values.username }}"
  SYSTEM_PASSWORD: "{{ .Values.password }}"
{{- end }}
