{{- if .Values.replicationservice.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: replication-service-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  BASE_URL: "https://{{ .Values.hostname }}"
  DATA_SERVICE_ENDPOINT: "{{ .Values.dataservice.endpoint }}"
  {{- if .Values.replicationservice.image.debug }}
  LOG_APPLICATION_LEVEL: "{{ ternary "DEBUG" "INFO" .Values.replicationservice.image.debug }}"
  {{- else }}
  LOG_APPLICATION_LEVEL: "INFO"
  {{- end }}
  METADATA_SERVICE_ENDPOINT: "{{ .Values.metadataservice.endpoint }}"
  SYSTEM_USERNAME: "{{ .Values.username }}"
  SYSTEM_PASSWORD: "{{ .Values.password }}"
{{- end }}
