{{- if .Values.searchservice.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: search-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  ADMIN_USERNAME: "{{ .Values.identityservice.users }}"
  ADMIN_PASSWORD: "{{ .Values.identityservice.userPasswords }}"
  AUTH_SERVICE_ADMIN: "{{ .Values.authservice.auth.adminUser }}"
  AUTH_SERVICE_ADMIN_PASSWORD: "{{ .Values.authservice.auth.adminPassword }}"
  AUTH_SERVICE_CLIENT: "{{ .Values.authservice.client.id }}"
  AUTH_SERVICE_CLIENT_SECRET: "{{ .Values.authservice.client.secret }}"
  AUTH_SERVICE_ENDPOINT: "{{ .Values.authservice.endpoint }}"
  GATEWAY_SERVICE_ENDPOINT: "{{ .Values.gateway }}"
  JWT_PUBKEY: "{{ .Values.authservice.jwt.pubkey }}"
  LOG_LEVEL: "{{ ternary "DEBUG" "INFO" .Values.searchservice.image.debug }}"
  OPENSEARCH_HOST: "{{ .Values.searchdb.host }}"
  OPENSEARCH_PORT: "{{ .Values.searchdb.port }}"
  OPENSEARCH_USERNAME: "{{ .Values.searchdb.security.adminUsername }}"
  OPENSEARCH_PASSWORD: "{{ .Values.searchdb.security.adminPassword }}"
{{- end }}
