{{- if .Values.searchservice.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app: search-service
    service: search-service
spec:
  replicas: {{ .Values.searchservice.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: search-service
      service: search-service
  template:
    metadata:
      annotations:
        {{- if .Values.searchservice.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.searchservice.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels:
        app: search-service
        service: search-service
    spec:
      {{- if .Values.searchservice.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.searchservice.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: search-service
          image: {{ .Values.searchservice.image.name }}
          imagePullPolicy: {{ .Values.searchservice.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.searchservice.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.searchservice.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: search-service-secret
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
            - name: empty-dir
              mountPath: /var/log/app/service/search
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:8080/health | grep 'UP' || exit 1"
            initialDelaySeconds: 150
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:8080/health | grep 'UP' || exit 1"
            initialDelaySeconds: 30
            periodSeconds: 10
          {{- if .Values.searchservice.resources }}
          resources: {{- toYaml .Values.searchservice.resources | nindent 12 }}
          {{- else if ne .Values.searchservice.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.searchservice.resourcesPreset) | nindent 12 }}
          {{- end }}
      volumes:
        - name: empty-dir
          emptyDir: { }
{{- end }}
