---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: ingress-cert
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDaTCCAlGgAwIBAgIUYxgRGsKNKfiSV85hfTqO7Fe2EJIwDQYJKoZIhvcNAQEL
    BQAwOTELMAkGA1UEBhMCQVQxEzARBgNVBAoMCkFjbWUsIEluYy4xFTATBgNVBAMM
    DEFjbWUgUm9vdCBDQTAeFw0yNDA0MDgwODA5MDRaFw0yNTA0MDgwODA5MDRaMDUx
    CzAJBgNVBAYTAkFUMQ8wDQYDVQQKDAZEQlJlcG8xFTATBgNVBAMMDGRicmVwby5s
    b2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJheX3oMZ9VnAj0u
    ta4mAQmoEDVu//N5jDZi3F2L1gItBXTZP46d37iaCNgAkKO6ct8KIO7zAm/Hdhtz
    1DB/5UJqJSvikGQKBidjw0lenqE7aqt2qbWk45yXxIEQbmpMkdUrsyJVLLaKLAaA
    Nx9m3bdb4Kaxtu6QKtrrifz8+dpUcJPmvzzDB+39kKHchj7HjtSNhIy+nG3EiLRM
    nG6qpWMlVEnK2SU1YT1p2s3WaA9sl8djVy3L6MKg+I0lchXjV9udnGs8GzPmHKrz
    KpTMpmkkNQZaULXyes9lZ0jPMvVrrGQzsZDjGtdpCBUhdeIoZ+EkdbZPtXtGM6oO
    PFWHWvECAwEAAaNtMGswKQYDVR0RBCIwIIIMZGJyZXBvLmxvY2FsghB3d3cuZGJy
    ZXBvLmxvY2FsMB0GA1UdDgQWBBR3+I9W+gtANK3PM7ex24aD2fKb9TAfBgNVHSME
    GDAWgBR1+iIlDzeK4jVdxyDwzkY02tdXQDANBgkqhkiG9w0BAQsFAAOCAQEAGeI2
    RaUqMuorjl6xeo5iB5jrr0w6ixPYYH7L7rbcJaUfYLo2oeUxU3hxOKxRktxKRtpa
    Inv81K7HwtruGYH1w9u0d3Le73WdesrLrq0yJgagkkEyuX+o7NH25rMjZdcrhSOl
    Rx3rbAARN4mt4CSPZY2+6HPi7YnTKO14QK/fnJazWJz1Y5ECYEabdhj/HTyZg2ea
    ZsZFq2DkBbmm8yGUWPfISABvrkwb9ustY9ei7aCy3edgExyRNmDo0bVQYz+LM0CD
    j2+OSsWAzsjPMIhp4cl4kFiPntVOUPo1nQmxhyGm2O24cuddUKQhMo1EWgye2+ag
    TyOmunmGfT3NQbF5JQ==
    -----END CERTIFICATE-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUzCCAjugAwIBAgIUU7IwC5g71hQaIaYa7DoE0lMfCqcwDQYJKoZIhvcNAQEL
    BQAwOTELMAkGA1UEBhMCQVQxEzARBgNVBAoMCkFjbWUsIEluYy4xFTATBgNVBAMM
    DEFjbWUgUm9vdCBDQTAeFw0yNDA0MDgwODA5MDRaFw0yNTA0MDgwODA5MDRaMDkx
    CzAJBgNVBAYTAkFUMRMwEQYDVQQKDApBY21lLCBJbmMuMRUwEwYDVQQDDAxBY21l
    IFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDP39vc/O3l
    DS37eTLGqEDROrJPC3ajNc3u/y/4XKsTwbTGC7pctkJ4juwmEMVKLDBIYgeEj+LU
    FFAC/sz9SmocPLm+vgIFtimKquqDQQaXbxcU5R86nS+sWsATwU+W8pOGdHLlE1ff
    e9yetOFrTX1bJvtAb6cF3wa56uvolTgXX2ivPu4Nen15740SqHy7Nt/ZEE6lKrwD
    umAf5i8+aTAYidVjtg14ON1SLCy+WCp8z32q+rij5MCtRft6XFN222x3vZnrSSdL
    JZ92l6+a8Lorz+ZHV59Rcbe8rQcjp5U50B8VMZzQwDp+M57TvdxIoeIzBzOE8h2G
    LbiDYk8bHch1AgMBAAGjUzBRMB0GA1UdDgQWBBR1+iIlDzeK4jVdxyDwzkY02tdX
    QDAfBgNVHSMEGDAWgBR1+iIlDzeK4jVdxyDwzkY02tdXQDAPBgNVHRMBAf8EBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBvFMB9MKO8TNJ7zHuCupuYF7hgGXs/P/9x
    PlfmDI+4r1GugRgW1lSpMCtoMJwQ7inVOv9qqxSQXwerfJxadkf3tMcZdD3DiYSP
    kk+7TNvfmZB8GBGcvYkga8lGOqSAQyeZ+NVOeemjP4cHgnWvo+UqwQoyEZmlR7B5
    M1J7JSftE/JAu9O0ECEDhP/xHqF4GEB81U+Lpsb/uqUscUYsFwU0O8hf3ZTEtoUF
    FMf89u+xw2tPOjGZ2MTJmsPzMDfq0RNqLdVOZ/Gua+xZkkmG0B68YcD9XUM4Be+J
    OJy2Rz6yROMLh+Lvj4pz3rRbmZdK16fCtvZymr+vDACSrfGnSFLW
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCYXl96DGfVZwI9
    LrWuJgEJqBA1bv/zeYw2Ytxdi9YCLQV02T+Ond+4mgjYAJCjunLfCiDu8wJvx3Yb
    c9Qwf+VCaiUr4pBkCgYnY8NJXp6hO2qrdqm1pOOcl8SBEG5qTJHVK7MiVSy2iiwG
    gDcfZt23W+CmsbbukCra64n8/PnaVHCT5r88wwft/ZCh3IY+x47UjYSMvpxtxIi0
    TJxuqqVjJVRJytklNWE9adrN1mgPbJfHY1cty+jCoPiNJXIV41fbnZxrPBsz5hyq
    8yqUzKZpJDUGWlC18nrPZWdIzzL1a6xkM7GQ4xrXaQgVIXXiKGfhJHW2T7V7RjOq
    DjxVh1rxAgMBAAECggEAQuMO07OVc1NkYrpaDAhn5TbPYr2HA3lkqU1Nwo0L1emw
    nwJtiaxZVR7dagEZfZ5wJeQ639pyw+ISQWvgBqhmWnjhN3oee6QA3pLHXDJ6vXmp
    UnrldjVbq9bd7vBpICXb0PH9kcFFPx65w+LOD+1mwELHhDW4gdJs1ayXZyUgg4xn
    c6H6tfzba/cFqiJKBqE6Gy+xrVFb/2StMzYKLwxirb5iKs5GsEys1/msASxQ+E6z
    Wcvsh+xtpWbfQUh2e1a+/tDTw/NtLeCsoH56162OJE/QjB84R4yrCFqQndOekQXr
    aMixrS3Gh4/hl5Ht4mGqsekjPTINM87twPV5PcM2bwKBgQDH0vZEaqHiNPlo7/CX
    qJqPuXc/jEIOAf50HaAC3MUWoI6yLE8ornyv17i2OOSUIek+w5qTtH/XFn5UhDGD
    2rd0v+dHPJZ93LyfXNmQvCRQN6YcQxW8oOrR6ygbTkDpwCB7qrbukMAXZolVgTL4
    4vWpyd5176GJ25H1cQ3UePTg+wKBgQDDNB2D+Rg22V75evB5IAtBpxFwYGobeYv6
    YlB9bHuu+tD4rR/qp1IgErcOVmC0ONTRurRTX83Il5I3HkVyF7EcFWaEw3J/Qcxs
    Bwqk9FdT+7hvcRk2oTJUszIN1Xl0uoKuSW4TTfLQWkprCS4VvPMnjrZn3ZdGpRKy
    tiLzncyoAwKBgQC0FzyeMqBNl8LEwaLLfEg4ikWf/0+1AjUK/3wruD7kgrW4fNim
    6IM1k61EhYf0vY9SYsXYow+okPwwPafGlwNKdH4DpOZY7u0Mj4kBuZ7csRrDU+6u
    PzUDFfXijidQxDhCXHxcDBcjv+S8LCH9T8dqS6Z0EhE7hqlIVKjLOmwwqwKBgQCk
    hxqRj7RvFovMb2icTvvt3CkAtOL6QVpQMelxrawZ8eGMmC8ckubPjbao6PkdLgGC
    vIEc/NTvy4E739HctkdbSlZcdHfe9tCcBNtd6WxppvLvSz5bI0bOyTLZIiL61fEr
    gUy8DKkqH9A1o0kqnVW887aemNDWhG/cHVQcTdafjQKBgFlrd+bDq1e+QVkkq6Lm
    IbNQvs4Oab/gFduj4+YNEsh2h6tBOHOuLP5+V0RRci9u2leBMVNXjcx/r7q/HUQJ
    DEDLIkO1m9mOf73e2sbWijQPr1yRi2JWwqTBOrsR1wrzXpNieCkhtTxI86WYOln/
    vIZCvz34aOw/2/fApGuBVid1
    -----END PRIVATE KEY-----
