{{- if .Values.storageservice.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-service-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  S3_BUCKET: "{{ .Values.storageservice.s3.bucket }}"
  STORAGE_ENDPOINT: "{{ .Values.storageservice.init.s3.endpoint }}"
  admin_access_key_id: "{{ .Values.storageservice.s3.auth.adminAccessKeyId }}"
  admin_secret_access_key: "{{ .Values.storageservice.s3.auth.adminSecretAccessKey }}"
  read_access_key_id: "{{ .Values.storageservice.s3.auth.readAccessKeyId }}"
  read_secret_access_key: "{{ .Values.storageservice.s3.auth.readSecretAccessKey }}"
  config.json: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": "{{ .Values.storageservice.s3.auth.adminAccessKeyId }}",
              "secretKey": "{{ .Values.storageservice.s3.auth.adminSecretAccessKey }}"
            }
          ],
          "actions": [
            "Read",
            "Write",
            "List",
            "Tagging",
            "Admin"
          ]
        }
      ]
    }
{{- end }}