{{- if .Values.storageservice.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: storage-service-create-buckets-job
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  template:
    metadata:
      name: storage-service-create-buckets-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: {{ .Values.storageservice.init.image.name }}
          imagePullPolicy: {{ .Values.storageservice.init.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: WEED_CLUSTER_DEFAULT
              value: "sw"
            - name: WEED_CLUSTER_SW_MASTER
              value: "storage-service-master:9333"
            - name: WEED_CLUSTER_SW_FILER
              value: "storage-service-filer:8888"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: storage-service-secret
                  key: S3_BUCKET
            - name: SEAWEEDFS_FULLNAME
              value: "storage-service"
          volumeMounts:
            - name: config-users
              mountPath: /etc/sw
              readOnly: true
          ports:
            - containerPort: 9333
              name: swfs-master
            - containerPort: 19333
              #name: swfs-master-grpc
          {{- if .Values.storageservice.init.resources }}
          resources: {{- toYaml .Values.storageservice.init.resources | nindent 12 }}
          {{- else if ne .Values.storageservice.init.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.storageservice.init.resourcesPreset) | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-users
          secret:
            defaultMode: 420
            secretName: storage-service-secret
{{- end }}
