{{- if .Values.ui.enabled }}
{{ $uploadEndpoint := printf "%s/api/upload/files" .Values.gateway }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ui-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  NUXT_PUBLIC_API_CLIENT: "{{ .Values.ui.public.api.client | default .Values.gateway }}"
  NUXT_PUBLIC_API_SERVER: "{{ .Values.ui.public.api.server | default .Values.gateway }}"
  NUXT_PUBLIC_TITLE: "{{ .Values.ui.public.title }}"
  NUXT_PUBLIC_LOGO: "{{ .Values.ui.public.logo }}"
  NUXT_PUBLIC_ICON: "{{ .Values.ui.public.icon }}"
  NUXT_PUBLIC_TOUCH: "{{ .Values.ui.public.touch }}"
  NUXT_PUBLIC_BROKER_HOST: "{{ .Values.ui.public.broker.host }}"
  NUXT_PUBLIC_BROKER_PORT: {{ .Values.ui.public.broker.port | toJson | quote }}
  NUXT_PUBLIC_BROKER_EXTRA: "{{ .Values.ui.public.broker.extra }}"
  NUXT_PUBLIC_DATABASE_EXTRA: "{{ .Values.ui.public.database.extra }}"
  NUXT_PUBLIC_DOI_ENABLED: "{{ .Values.ui.public.doi.enabled }}"
  NUXT_PUBLIC_DOI_ENDPOINT: "{{ .Values.ui.public.doi.endpoint }}"
  NUXT_PUBLIC_LINKS_KEYCLOAK_HREF: "{{ .Values.ui.public.links.keycloak.href }}"
  NUXT_PUBLIC_LINKS_KEYCLOAK_TEXT: "{{ .Values.ui.public.links.keycloak.text }}"
  NUXT_PUBLIC_LINKS_RABBITMQ_HREF: "{{ .Values.ui.public.links.rabbitmq.href }}"
  NUXT_PUBLIC_LINKS_RABBITMQ_TEXT: "{{ .Values.ui.public.links.rabbitmq.text }}"
  NUXT_PUBLIC_PID_DEFAULT_PUBLISHER: "{{ .Values.ui.public.pid.default.publisher }}"
  NUXT_PUBLIC_UPLOAD_CLIENT: "{{ .Values.ui.public.upload.client | default $uploadEndpoint }}"
{{- end }}
