{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    service: ui
spec:
  type: ClusterIP
  ports:
    - name: ""
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    service: ui
{{- end }}
