{{- if .Values.ui.enabled }}
{{ $gateway := printf "https://%s" .Values.hostname }}
{{ $uploadEndpoint := printf "%s/api/upload/files" $gateway }}
{{ $dashboardEndpoint := printf "%s/dashboard" $gateway }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ui-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  NUXT_STORAGE_OIDC_HOST: "{{ .Values.cachedb.endpoint }}"
  NUXT_STORAGE_OIDC_USERNAME: "{{ .Values.cachedb.auth.username | default "default" }}"
  NUXT_STORAGE_OIDC_PASSWORD: "{{ .Values.cachedb.auth.password }}"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_AUTHORIZATION_URL: "{{ $gateway }}/realms/dbrepo/protocol/openid-connect/auth"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL: "{{ $gateway }}/realms/dbrepo"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID: "{{ .Values.authservice.client.id }}"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_SECRET: "{{ .Values.authservice.client.secret }}"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_LOGOUT_REDIRECT_URI: "{{ $gateway }}"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_LOGOUT_URL: "{{ $gateway }}/realms/dbrepo/protocol/openid-connect/logout"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_REDIRECT_URI: "{{ $gateway }}/auth/keycloak/callback"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_TOKEN_URL: "{{ $gateway }}/realms/dbrepo/protocol/openid-connect/token"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_USER_INFO_URL: "{{ $gateway }}/realms/dbrepo/protocol/openid-connect/userinfo"
  NUXT_OIDC_SESSION_SECRET: "{{ .Values.ui.oidc.sessionSecret }}"
  NUXT_OIDC_TOKEN_KEY: "{{ .Values.ui.oidc.tokenKey }}"
  NUXT_OIDC_AUTH_SESSION_SECRET: "{{ .Values.ui.oidc.authSessionSecret }}"
  NUXT_PUBLIC_API_CLIENT: "{{ .Values.ui.public.api.client | default $gateway }}"
  NUXT_PUBLIC_API_SERVER: "{{ .Values.ui.public.api.server | default $gateway }}"
  NUXT_PUBLIC_TITLE: "{{ .Values.ui.public.title }}"
  NUXT_PUBLIC_LOGO: "{{ .Values.ui.public.logo }}"
  NUXT_PUBLIC_ICON: "{{ .Values.ui.public.icon }}"
  NUXT_PUBLIC_TOUCH: "{{ .Values.ui.public.touch }}"
  NUXT_PUBLIC_BROKER_HOST: "{{ .Values.ui.public.broker.host }}"
  NUXT_PUBLIC_BROKER_PORT: {{ .Values.ui.public.broker.port | toJson | quote }}
  NUXT_PUBLIC_BROKER_EXTRA: "{{ .Values.ui.public.broker.extra }}"
  NUXT_PUBLIC_DASHBOARD_URL: "{{ .Values.ui.public.dashboard.url | default $dashboardEndpoint }}"
  NUXT_PUBLIC_DATABASE_EXTRA: "{{ .Values.ui.public.database.extra }}"
  NUXT_PUBLIC_DOI_ENABLED: "{{ .Values.ui.public.doi.enabled }}"
  NUXT_PUBLIC_DOI_ENDPOINT: "{{ .Values.ui.public.doi.endpoint }}"
  NUXT_PUBLIC_PID_DEFAULT_PUBLISHER: "{{ .Values.ui.public.pid.default.publisher }}"
  NUXT_PUBLIC_UPLOAD_CLIENT: "{{ .Values.ui.public.upload.client | default $uploadEndpoint }}"
  NUXT_PUBLIC_BROKER_CONNECTIONS: "{{ include "dbrepo.broker.connections" . }}"
  NUXT_PUBLIC_ABOUT_CONTENT: "{{ .Values.ui.public.about.content }}"
  NUXT_PUBLIC_POLICIES_CONTENT: "{{ .Values.ui.public.policies.content }}"
  NUXT_PUBLIC_TERMS_CONTENT: "{{ .Values.ui.public.terms.content }}"
{{- end }}
