{{- if .Values.uploadservice.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    service: upload-service
spec:
  type: ClusterIP
  ports:
    - name: "upload-service"
      port: 80
      targetPort: 1080
      protocol: TCP
  selector:
    service: upload-service
{{- end }}
