---
apiVersion: v1
kind: Secret
metadata:
  name: upload-service-secret
  namespace: {{ include "common.names.namespace" . | quote }}
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.storageservice.s3.auth.adminAccessKeyId }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.storageservice.s3.auth.adminSecretAccessKey }}"
  AWS_REGION: "{{ .Values.storageservice.s3.region | default "default" }}"
