annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
name: dbrepo
description: Helm Chart for installing DBRepo
sources:
  - https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
type: application
version: "1.6.0"
appVersion: "1.6.0"
keywords:
  - dbrepo
maintainers:
  - name: Martin Weise
    email: martin.weise@tuwien.ac.at
home: https://www.ifs.tuwien.ac.at/infrastructures/dbrepo/1.6/
icon: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services/-/raw/master/dbrepo-ui/public/favicon.png
dependencies:
  - name: opensearch
    alias: searchdb
    version: 1.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: searchdb.enabled
  - name: keycloak
    alias: authservice
    version: 21.6.1  # app version: 24.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: authservice.enabled
  - name: mariadb-galera
    alias: datadb
    version: 13.2.7
    repository: https://charts.bitnami.com/bitnami
    condition: datadb.enabled
  - name: mariadb-galera
    alias: metadatadb
    version: 13.2.7
    repository: https://charts.bitnami.com/bitnami
    condition: metadatadb.enabled
  - name: rabbitmq
    alias: brokerservice
    version: 14.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: brokerservice.enabled
  - name: seaweedfs
    alias: storageservice
    version: 4.2.1
    repository: file://../seaweedfs
    condition: storageservice.enabled
  - name: grafana
    alias: dashboardservice
    version: 11.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: dashboardservice.enabled
  - name: prometheus
    alias: metricdb
    version: 1.3.22
    repository: https://charts.bitnami.com/bitnami
    condition: metricdb.enabled
  - name: nginx
    alias: gatewayservice
    version: 18.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: gatewayservice.enabled