annotations:
  category: Infrastructure
  images: |
    - name: openldap
      image: docker.io/bitnamilegacy/openldap:2.6.8-debian-12-r1
    - name: metadata-service
      image: ghcr.io/dbrepo-project/dbrepo/metadata-service:1.13.4
    - name: data-service
      image: ghcr.io/dbrepo-project/dbrepo/data-service:1.13.4
    - name: search-service
      image: ghcr.io/dbrepo-project/dbrepo/search-service:1.13.4
    - name: search-service-init
      image: ghcr.io/dbrepo-project/dbrepo/search-service-init:1.13.4
    - name: storage-service-init
      image: ghcr.io/dbrepo-project/dbrepo/storage-service-init:1.13.4
    - name: storage-service-init
      image: ghcr.io/dbrepo-project/dbrepo/storage-service-init:1.13.4
    - name: ui
      image: ghcr.io/dbrepo-project/dbrepo/ui:1.13.4
    - name: dashboard-service-init
      image: ghcr.io/dbrepo-project/dbrepo/dashboard-service-init:1.13.4
  licenses: Apache-2.0
apiVersion: v2
name: dbrepo
description: Helm Chart for installing DBRepo
sources:
  - https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
type: application
version: "1.13.4"
appVersion: "1.13.4"
keywords:
  - dbrepo
maintainers:
  - name: Martin Weise
    email: martin.weise@tuwien.ac.at
home: https://www.ifs.tuwien.ac.at/infrastructures/dbrepo/1.13/
icon: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services/-/raw/master/dbrepo-ui/public/favicon.png
dependencies:
  - name: opensearch
    alias: searchdb
    version: 1.4.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: searchdb.enabled
  - name: keycloak
    alias: authservice
    version: 25.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: authservice.enabled
  - name: nginx
    alias: gatewayservice
    version: 20.0.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: gatewayservice.enabled
  - name: mariadb-galera
    alias: datadb
    version: 13.2.7
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: datadb.enabled
  - name: mariadb-galera
    alias: metadatadb
    version: 13.2.7
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: metadatadb.enabled
  - name: rabbitmq
    alias: brokerservice
    version: 14.7.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: brokerservice.enabled
  - name: seaweedfs
    alias: storageservice
    version: 4.8.7
    repository: file://../seaweedfs
    condition: storageservice.enabled
  - name: grafana
    alias: dashboardui
    version: 11.4.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: dashboardui.enabled
  - name: prometheus
    alias: metricdb
    version: 1.3.22
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: metricdb.enabled
  - name: postgresql
    alias: dashboarddb
    version: 16.1.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: dashboarddb.enabled
  - name: valkey
    alias: cachedb
    version: 6.1.11
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: cachedb.enabled
