package at.tuwien.mapper;

import at.tuwien.InsertTableRawQuery;
import at.tuwien.api.database.query.*;
import at.tuwien.api.database.table.TableCsvDeleteDto;
import at.tuwien.api.database.table.TableCsvDto;
import at.tuwien.api.database.table.TableCsvUpdateDto;
import at.tuwien.entities.database.Database;
import at.tuwien.entities.database.table.columns.TableColumnType;
import at.tuwien.exception.TableMalformedException;
import at.tuwien.querystore.Query;
import at.tuwien.entities.database.table.Table;
import at.tuwien.entities.database.table.columns.TableColumn;
import at.tuwien.exception.ImageNotSupportedException;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;
import org.mapstruct.Named;
import org.mariadb.jdbc.MariaDbBlob;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.text.Normalizer;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.*;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

@Mapper(componentModel = "spring")
public interface QueryMapper {

    org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(QueryMapper.class);

    @Deprecated
    @Mappings({
            @Mapping(source = "query", target = "statement")
    })
    ExecuteStatementDto queryDtoToExecuteStatementDto(QueryDto data);

    ExecuteStatementDto saveStatementDtoToExecuteStatementDto(SaveStatementDto data);

    QueryDto queryToQueryDto(Query data);

    List<QueryDto> queryListToQueryDtoList(List<Query> data);

    @Named("internalMapping")
    default String nameToInternalName(String data) {
        if (data == null || data.length() == 0) {
            return data;
        }
        final Pattern NONLATIN = Pattern.compile("[^\\w-]");
        final Pattern WHITESPACE = Pattern.compile("[\\s]");
        String nowhitespace = WHITESPACE.matcher(data).replaceAll("_");
        String normalized = Normalizer.normalize(nowhitespace, Normalizer.Form.NFD);
        String slug = NONLATIN.matcher(normalized).replaceAll("");
        return slug.toLowerCase(Locale.ENGLISH);
    }

    default QueryResultDto resultListToQueryResultDto(List<TableColumn> columns, List<?> result) {
        final Iterator<?> iterator = result.iterator();
        final List<Map<String, Object>> resultList = new LinkedList<>();
        log.trace("result has {} columns and {} rows", columns.size(), result.size());
        while (iterator.hasNext()) {
            /* map the result set to the columns through the stored metadata in the metadata database */
            int[] idx = new int[]{0};
            final Object[] data;
            if (columns.size() == 1) {
                data = new Object[]{iterator.next()};
            } else {
                data = (Object[]) iterator.next();
            }
            final Map<String, Object> map = new HashMap<>();
            columns
                    .forEach(column -> map.put(column.getName(),
                            dataColumnToObject(data[idx[0]++], column)));
            resultList.add(map);
        }
        return QueryResultDto.builder()
                .result(resultList)
                .build();
    }

    default InsertTableRawQuery pathToRawInsertQuery(Table table, ImportDto data) {
        final StringBuilder query = new StringBuilder("LOAD DATA LOCAL INFILE '")
                .append(data.getLocation())
                .append("' INTO TABLE `")
                .append(table.getDatabase().getInternalName())
                .append("`.`")
                .append(table.getInternalName())
                .append("` CHARACTER SET utf8 FIELDS TERMINATED BY '")
                .append(table.getSeparator())
                .append("'");
        if (table.getQuote() != null) {
            query.append(" OPTIONALLY ENCLOSED BY '")
                    .append(table.getQuote())
                    .append("'");
        }
        query.append(table.getSkipLines() != null ? (" IGNORE " + table.getSkipLines() + " LINES") : "")
                .append(" (");
        final StringBuilder set = new StringBuilder();
        int[] idx = new int[]{0};
        table.getColumns()
                .forEach(column -> {
                    if (column.getAutoGenerated()) {
                        return;
                    }
                    query.append(idx[0] != 0 ? "," : "");
                    /* format as variable */
                    query.append("@")
                            .append(column.getInternalName());
                    if (column.getDateFormat() != null) {
                        /* reformat dates */
                        columnToDateSet(table, column, set);
                    } else if (column.getColumnType().equals(TableColumnType.BOOLEAN)) {
                        /* reformat booleans */
                        columnToBoolSet(table, column, set);
                    } else {
                        /* reformat others */
                        columnToTextSet(table, column, set);
                    }
                    idx[0]++;
                });
        query.append(")")
                .append(set.length() != 0 ? (" SET " + set) : "")
                .append(";");
        log.debug("import csv {} for table {}", data.getLocation(), table);
        log.trace("raw import query: [{}]", query);
        return InsertTableRawQuery.builder()
                .query(query.toString())
                .build();
    }

    default void columnToBoolSet(Table table, TableColumn column, StringBuilder set) {
        set.append(set.length() != 0 ? ", " : "")
                .append("`")
                .append(column.getInternalName())
                .append("` = ");
        if (table.getNullElement() != null) {
            set.append("IF(!STRCMP(@")
                    .append(column.getInternalName())
                    .append(",'")
                    .append(table.getNullElement())
                    .append("'),NULL,");
            columnToBoolSet2(table, column, set);
            set.append(")");
            return;
        }
        columnToBoolSet2(table, column, set);
    }

    default void columnToBoolSet2(Table table, TableColumn column, StringBuilder set) {
        if (table.getTrueElement() != null) {
            set.append("IF(!STRCMP(@")
                    .append(column.getInternalName())
                    .append(",'")
                    .append(table.getTrueElement())
                    .append("'),TRUE,");
            if (table.getFalseElement() != null) {
                /* can map both true/false */
                set.append("IF(!STRCMP(@")
                        .append(column.getInternalName())
                        .append(",'")
                        .append(table.getFalseElement())
                        .append("'),FALSE,@")
                        .append(column.getInternalName())
                        .append("))");
            } else {
                /* can only map true */
                set.append("@")
                        .append(column.getInternalName())
                        .append(")");
            }
//            set.append(")");
            return;
        }
        if (table.getFalseElement() != null) {
            set.append("IF(!STRCMP(@")
                    .append(column.getInternalName())
                    .append(",'")
                    .append(table.getFalseElement())
                    .append("'),FALSE,");
            if (table.getTrueElement() != null) {
                /* can map both true/false */
                set.append("IF(!STRCMP(@")
                        .append(column.getInternalName())
                        .append(",'")
                        .append(table.getTrueElement())
                        .append("'),TRUE,@")
                        .append(column.getInternalName())
                        .append("))");
            } else {
                /* can only map true */
                set.append("@")
                        .append(column.getInternalName())
                        .append(")");
            }
//            set.append(")");
            return;
        }
        set.append("@")
                .append(column.getInternalName());
//                .append(")");
    }

    default void columnToTextSet(Table table, TableColumn column, StringBuilder set) {
        set.append(set.length() != 0 ? ", " : "")
                .append("`")
                .append(column.getInternalName())
                .append("` = ");
        if (table.getNullElement() != null) {
            set.append("IF(STRCMP(@")
                    .append(column.getInternalName())
                    .append(",'")
                    .append(table.getNullElement())
                    .append("'), @")
                    .append(column.getInternalName())
                    .append(", NULL)");
            return;
        }
        set.append("@")
                .append(column.getInternalName());
    }

    default void columnToDateSet(Table table, TableColumn column, StringBuilder set) {
        set.append(set.length() != 0 ? ", " : "")
                .append("`")
                .append(column.getInternalName())
                .append("` = STR_TO_DATE(");
        if (table.getNullElement() != null) {
            set.append("IF(STRCMP(@")
                    .append(column.getInternalName())
                    .append(",'")
                    .append(table.getNullElement())
                    .append("'), @")
                    .append(column.getInternalName())
                    .append(", NULL), '")
                    .append(column.getDateFormat()
                            .getDatabaseFormat())
                    .append("')");
            return;
        }
        set.append("@")
                .append(column.getInternalName())
                .append(", '")
                .append(column.getDateFormat()
                        .getDatabaseFormat())
                .append("')");
    }

    default String tableToRawExportQuery(Table table, Instant timestamp, String filename) {
        final StringBuilder query = new StringBuilder("SELECT ");
        int[] idx = new int[]{0};
        table.getColumns()
                .forEach(column -> {
                    query.append(idx[0] != 0 ? "," : "")
                            .append("`")
                            .append(column.getInternalName())
                            .append("`");
                    idx[0]++;
                });
        query.append("FROM `")
                .append(table.getInternalName())
                .append("` INTO OUTFILE '/tmp/")
                .append(filename)
                .append("' CHARACTER SET utf8 FIELDS TERMINATED BY '")
                .append(table.getSeparator())
                .append("'");
        if (table.getQuote() != null) {
            query.append(" OPTIONALLY ENCLOSED BY '")
                    .append(table.getQuote())
                    .append("'");
        }
        if (timestamp != null) {
            query.append(" FOR SYSTEM_TIME AS OF TIMESTAMP'")
                    .append(LocalDateTime.ofInstant(timestamp, ZoneId.of("Europe/Vienna")))
                    .append("'");
        }
        query.append(";");
        return query.toString();
    }

    default String queryToRawExportQuery(Query query, String filename) {
        if (query.getQuery().contains(";")) {
            log.trace("Remove ending ; from statement [{}]", query.getQuery());
            query.setQuery(query.getQuery().substring(0, query.getQuery().indexOf(";")));
        }
        final StringBuilder statement = new StringBuilder(query.getQuery())
                .append(" FOR SYSTEM_TIME AS OF TIMESTAMP'")
                .append(LocalDateTime.ofInstant(query.getExecution(), ZoneId.of("Europe/Vienna")))
                .append("' INTO OUTFILE '/tmp/")
                .append(filename)
                .append("' CHARACTER SET utf8 FIELDS TERMINATED BY ',';");
        log.trace("raw export query: [{}]", statement);
        return statement.toString();
    }

    default InsertTableRawQuery tableCsvDtoToRawInsertQuery(Table table, TableCsvDto data)
            throws TableMalformedException, ImageNotSupportedException {
        if (table.getColumns().size() == 0) {
            log.error("Column size is zero");
            throw new TableMalformedException("Columns are not known");
        }
        /* check image */
        if (!table.getDatabase().getContainer().getImage().getRepository().equals("mariadb")) {
            log.error("Currently only MariaDB is supported");
            throw new ImageNotSupportedException("Image not supported.");
        }
        /* parameterized query for prepared statement */
        final StringBuilder query = new StringBuilder("INSERT INTO `")
                .append(table.getInternalName())
                .append("` (")
                .append(table.getColumns()
                        .stream()
                        .filter(column -> !column.getAutoGenerated())
                        .map(column -> "`" + column.getInternalName() + "`")
                        .collect(Collectors.joining(",")))
                .append(") VALUES (?1);");
        /* debug */
        final Collection<Object> values = table.getColumns()
                .stream()
                .filter(c -> !c.getAutoGenerated())
                .map(c -> data.getData()
                        .entrySet()
                        .stream()
                        .filter(d -> d.getKey().equals(c.getInternalName()))
                        .findFirst()
                        .get()
                        .getValue())
                .collect(Collectors.toList());
        log.trace("raw insert query: [{}] with data {}", query, values);
        return InsertTableRawQuery.builder()
                .query(query.toString())
                .data(values)
                .build();
    }

    default String tableCsvDtoToRawDeleteQuery(Table table, TableCsvDeleteDto data)
            throws TableMalformedException, ImageNotSupportedException {
        if (table.getColumns().size() == 0) {
            log.error("Column size is zero");
            throw new TableMalformedException("Columns are not known");
        }
        /* check image */
        if (!table.getDatabase().getContainer().getImage().getRepository().equals("mariadb")) {
            log.error("Currently only MariaDB is supported");
            throw new ImageNotSupportedException("Image not supported.");
        }
        /* parameterized query for prepared statement */
        final StringBuilder query = new StringBuilder("DELETE FROM `")
                .append(table.getInternalName())
                .append("` WHERE ");
        final int[] idx = new int[]{0};
        data.getKeys()
                .forEach((key, value) -> query.append(idx[0] == 0 ? "" : ", ")
                        .append("`")
                        .append(key)
                        .append("` = ?")
                        .append(idx[0]++));
        /* debug */
        log.trace("raw delete query: [{}] with data {}", query, data.getKeys().values());
        return query.toString();
    }

    default InsertTableRawQuery tableCsvDtoToRawUpdateQuery(Table table, TableCsvUpdateDto data)
            throws TableMalformedException, ImageNotSupportedException {
        if (table.getColumns().size() == 0) {
            log.error("Column size is zero");
            throw new TableMalformedException("Columns are not known");
        }
        /* check image */
        if (!table.getDatabase().getContainer().getImage().getRepository().equals("mariadb")) {
            log.error("Currently only MariaDB is supported");
            throw new ImageNotSupportedException("Image not supported.");
        }
        /* parameterized query for prepared statement */
        final StringBuilder query = new StringBuilder("UPDATE `")
                .append(table.getInternalName())
                .append("` SET ");
        final int[] idx = new int[]{0};
        data.getData()
                .forEach((key, value) -> {
                    query.append(idx[0] == 0 ? "" : ", ")
                            .append("`")
                            .append(key)
                            .append("` = ?")
                            .append(idx[0]);
                    idx[0]++;
                });
        query.append(" WHERE ");
        final int[] jdx = new int[]{0};
        data.getKeys()
                .forEach((key, value) -> {
                    query.append(jdx[0] == 0 ? "" : ", ")
                            .append("`")
                            .append(key)
                            .append("` = '")
                            .append(value)
                            .append("'");
                    jdx[0]++;
                });
        query.append(";");
        /* debug */
        log.trace("raw update query: [{}] with data {}", query, data.getData().values());
        return InsertTableRawQuery.builder()
                .query(query.toString())
                .data(data.getData().values())
                .build();
    }

    default String tableToRawCountAllQuery(Table table, Instant timestamp) throws ImageNotSupportedException {
        /* check image */
        if (!table.getDatabase().getContainer().getImage().getRepository().equals("mariadb")) {
            log.error("Currently only MariaDB is supported");
            throw new ImageNotSupportedException("Image not supported.");
        }
        if (timestamp == null) {
            timestamp = Instant.now();
        }
        return "SELECT COUNT(*) FROM `" + nameToInternalName(table.getName()) +
                "` FOR SYSTEM_TIME AS OF TIMESTAMP '" +
                LocalDateTime.ofInstant(timestamp, ZoneId.of("Europe/Vienna")) +
                "';";
    }

    default String queryToRawTimestampedCountQuery(String query, Database database, Instant timestamp)
            throws ImageNotSupportedException {
        /* param check */
        if (!database.getContainer().getImage().getRepository().equals("mariadb")) {
            throw new ImageNotSupportedException("Currently only MariaDB is supported");
        }
        if (timestamp == null) {
            throw new IllegalArgumentException("Timestamp must be provided");
        }
        final StringBuilder sb = new StringBuilder();
        sb.append("SELECT COUNT(*) FROM");
        if (query.contains("where")) {
            sb.append(query.toLowerCase(Locale.ROOT).split("from ")[1].split("where")[0]);
        } else {
            sb.append(query.toLowerCase(Locale.ROOT).split("from ")[1]);
        }
        sb.append("FOR SYSTEM_TIME AS OF TIMESTAMP '");
        sb.append(LocalDateTime.ofInstant(timestamp, ZoneId.of("Europe/Vienna")));
        sb.append("' ");
        if (query.contains("where")) {
            sb.append("where ");
            sb.append(query.toLowerCase(Locale.ROOT).split("from ")[1].split("where")[1]);
        }
        sb.append(";");
        log.debug(sb.toString());
        return sb.toString();
    }

    default String queryToRawTimestampedQuery(String query, Database database, Instant timestamp, Long page, Long size)
            throws ImageNotSupportedException {
        /* param check */
        if (!database.getContainer().getImage().getRepository().equals("mariadb")) {
            throw new ImageNotSupportedException("Currently only MariaDB is supported");
        }
        if (timestamp == null) {
            throw new IllegalArgumentException("Please provide a timestamp before");
        }
        final StringBuilder sb = new StringBuilder();
        if (query.contains("where")) {
            sb.append(query.toLowerCase(Locale.ROOT).split("where")[0]);
        } else {
            sb.append(query.toLowerCase(Locale.ROOT));
        }
        sb.append("FOR SYSTEM_TIME AS OF TIMESTAMP '");
        sb.append(LocalDateTime.ofInstant(timestamp, ZoneId.of("Europe/Vienna")));
        sb.append("' ");
        if (query.contains("where")) {
            sb.append("where");
            sb.append(query.toLowerCase(Locale.ROOT).split("from ")[1].split("where")[1]);
        }
        if (size != null && page != null && size > 0 && page >= 0) {
            sb.append(" LIMIT " + size + " OFFSET " + (page * size));
        }
        sb.append(";");

        log.debug(sb.toString());

        return sb.toString();

    }


    default String tableToRawFindAllQuery(Table table, Instant timestamp, Long size, Long page)
            throws ImageNotSupportedException {
        /* param check */
        if (!table.getDatabase().getContainer().getImage().getRepository().equals("mariadb")) {
            throw new ImageNotSupportedException("Currently only MariaDB is supported");
        }
        if (timestamp == null) {
            timestamp = Instant.now();
            log.debug("no timestamp provided, default to {}", timestamp);
        } else {
            log.debug("timestamp provided {}", timestamp);
        }
        final int[] idx = new int[]{0};
        final StringBuilder query = new StringBuilder("SELECT ");
        table.getColumns()
                .forEach(column -> query.append(idx[0]++ > 0 ? "," : "")
                        .append("`")
                        .append(column.getInternalName())
                        .append("`"));
        query.append(" FROM `")
                .append(nameToInternalName(table.getName()))
                .append("` FOR SYSTEM_TIME AS OF TIMESTAMP '")
                .append(LocalDateTime.ofInstant(timestamp, ZoneId.of("Europe/Vienna")))
                .append("'");
        if (size != null && page != null) {
            log.trace("pagination size/limit of {}", size);
            query.append(" LIMIT ")
                    .append(size);
            log.trace("pagination page/offset of {}", page);
            query.append(" OFFSET ")
                    .append(page * size)
                    .append(";");

        }
        log.trace("raw select table query: [{}]", query);
        return query.toString();
    }

    default QueryResultDto queryTableToQueryResultDto(List<?> result, Table table) throws DateTimeException {
        final Iterator<?> iterator = result.iterator();
        final List<Map<String, Object>> queryResult = new LinkedList<>();
        while (iterator.hasNext()) {
            /* map the result set to the columns through the stored metadata in the metadata database */
            int[] idx = new int[]{0};
            final Object[] data = (Object[]) iterator.next();
            final Map<String, Object> map = new HashMap<>();
            table.getColumns()
                    .forEach(column -> map.put(column.getInternalName(), dataColumnToObject(data[idx[0]++], column)));
            queryResult.add(map);
        }
        log.info("Selected {} records from table id {}", queryResult.size(), table.getId());
        log.trace("table {} contains {} records", table, queryResult.size());
        return QueryResultDto.builder()
                .result(queryResult)
                .build();
    }

    @Transactional
    default Object dataColumnToObject(Object data, TableColumn column) throws DateTimeException {
        if (data == null) {
            return null;
        }
        log.trace("map data {} to table column {}", data, column);
        switch (column.getColumnType()) {
            case BLOB:
                log.trace("mapping {} to blob", data);
                return new MariaDbBlob((byte[]) data);
            case DATE:
                if (column.getDateFormat() == null) {
                    log.error("Missing date format for column {} of table {}", column.getId(),
                            column.getTable().getId());
                    throw new IllegalArgumentException("Missing date format");
                }
                log.trace("mapping {} to date with format '{}'", data, column.getDateFormat());
                final DateTimeFormatter formatter = new DateTimeFormatterBuilder()
                        .parseCaseInsensitive() /* case insensitive to parse JAN and FEB */
                        .appendPattern(column.getDateFormat().getUnixFormat())
                        .toFormatter(Locale.ENGLISH);
                final LocalDate date = LocalDate.parse(String.valueOf(data), formatter);
                return date.atStartOfDay(ZoneId.of("UTC"))
                        .toInstant();
            case TIMESTAMP:
                if (column.getDateFormat() == null) {
                    log.error("Missing date format for column {} of table {}", column.getId(),
                            column.getTable().getId());
                    throw new IllegalArgumentException("Missing date format");
                }
                log.trace("mapping {} to timestamp with format '{}'", data, column.getDateFormat());
                return Timestamp.valueOf(data.toString())
                        .toInstant();
            case ENUM:
            case TEXT:
            case STRING:
                log.trace("mapping {} to character array", data);
                return String.valueOf(data);
            case NUMBER:
                log.trace("mapping {} to non-decimal number", data);
                return new BigInteger(String.valueOf(data));
            case DECIMAL:
                log.trace("mapping {} to decimal number", data);
                return Double.valueOf(String.valueOf(data));
            case BOOLEAN:
                log.trace("mapping {} to boolean", data);
                return Boolean.valueOf(String.valueOf(data));
            default:
                throw new IllegalArgumentException("Column type not known");
        }
    }

    @Named("EscapedString")
    default String stringToEscapedString(String name) throws ImageNotSupportedException {
        if (name != null && !name.startsWith("`") && !name.endsWith("`")) {
            final String escaped = "`" + name + "`";
            log.trace("mapped non-escaped string [{}] to escaped string: [{}]", name, escaped);
            return escaped;
        }
        return name;
    }

}
