app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: jdbc:mariadb://localhost:3306/fda
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dbrepo
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: fda
        jdbc:
          time_zone: UTC
  application:
    name: authentication-service
  cloud:
    loadbalancer.ribbon.enabled: false
  rabbitmq:
    host: localhost
    username: fda
    password: fda
  mail:
    default-encoding: UTF-8
    host: ""
    port: 0
    username: ""
    password: ""
    properties.mail.smtp:
      timeout: 5000
      auth: true
      starttls.enable: true
management.endpoints.web.exposure.include: health,info,prometheus
server:
  port: 9097
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: trace
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  instance.hostname: authentication-service
  client.serviceUrl.defaultZone: http://localhost:9090/eureka/
fda:
  ready.path: ./ready
  website: localhost:3000
  gateway.endpoint: http://localhost:9095/api/broker
  token.max: 100
  default_roles: ROLE_RESEARCHER
  superusers: dev1
  mail:
    prefix: /
    from: Nobody
    replyto: Nobody
    verify: false
jwt:
  issuer: dbrepo
  secret: dbrepo
  expiration.ms: 100000000