{{- if .Values.searchService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: {{ .Values.namespace }}
  labels:
    app: search-service
    service: search-service
spec:
  replicas: {{ .Values.searchService.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: search-service
      service: search-service
  template:
    metadata:
      labels:
        app: search-service
        service: search-service
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: search-service
          image: {{ .Values.searchService.image.name }}
          imagePullPolicy: {{ .Values.searchService.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 4000
              protocol: TCP
          env:
            - name: OPENSEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: search-service-secret
                  key: opensearch-host
            - name: OPENSEARCH_PORT
              valueFrom:
                secretKeyRef:
                  name: search-service-secret
                  key: opensearch-port
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: search-service-secret
                  key: opensearch-username
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: search-service-secret
                  key: opensearch-password
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: search-service-secret
                  key: log-level
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:4000/health | grep 'UP' || exit 1"
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:4000/health | grep 'UP' || exit 1"
            initialDelaySeconds: 10
            periodSeconds: 30
          volumeMounts: []
      volumes: []
{{- end }}
