---
apiVersion: v1
kind: Secret
metadata:
  name: search-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  opensearch-host: "{{ index .Values "search-db" "host" }}"
  opensearch-port: "{{ index .Values "search-db" "port" }}"
  opensearch-username: "{{ index .Values "search-db" "username" }}"
  opensearch-password: "{{ index .Values "search-db" "password" }}"
  log-level: "{{ ternary "DEBUG" "INFO" .Values.searchService.image.debug }}"
