---
apiVersion: v1
kind: Secret
metadata:
  name: search-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  opensearch-host: "{{ .Values.searchdb.host }}"
  opensearch-port: "{{ .Values.searchdb.port }}"
  opensearch-username: "{{ .Values.searchdb.username }}"
  opensearch-password: "{{ .Values.searchdb.password }}"
  log-level: "{{ ternary "DEBUG" "INFO" .Values.searchService.image.debug }}"
