---
apiVersion: v1
kind: Secret
metadata:
  name: search-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  opensearch-host: "{{ .Values.searchDb.host }}"
  opensearch-port: "{{ .Values.searchDb.port }}"
  opensearch-username: "{{ .Values.searchDb.username }}"
  opensearch-password: "{{ .Values.searchDb.password }}"
  log-level: "{{ ternary "DEBUG" "INFO" .Values.searchService.image.debug }}"
