/*
 * Database Repository Table Service API
 * Service that manages the tables
 *
 * OpenAPI spec version: 1.1.0-alpha
 * Contact: andreas.rauber@tuwien.ac.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ColumnSemanticsUpdateDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-12T12:29:06.419178+01:00[Europe/Vienna]")
public class ColumnSemanticsUpdateDto {
  @SerializedName("concept_uri")
  private String conceptUri = null;

  @SerializedName("unit_uri")
  private String unitUri = null;

  public ColumnSemanticsUpdateDto conceptUri(String conceptUri) {
    this.conceptUri = conceptUri;
    return this;
  }

   /**
   * Get conceptUri
   * @return conceptUri
  **/
  @Schema(description = "")
  public String getConceptUri() {
    return conceptUri;
  }

  public void setConceptUri(String conceptUri) {
    this.conceptUri = conceptUri;
  }

  public ColumnSemanticsUpdateDto unitUri(String unitUri) {
    this.unitUri = unitUri;
    return this;
  }

   /**
   * Get unitUri
   * @return unitUri
  **/
  @Schema(description = "")
  public String getUnitUri() {
    return unitUri;
  }

  public void setUnitUri(String unitUri) {
    this.unitUri = unitUri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ColumnSemanticsUpdateDto columnSemanticsUpdateDto = (ColumnSemanticsUpdateDto) o;
    return Objects.equals(this.conceptUri, columnSemanticsUpdateDto.conceptUri) &&
        Objects.equals(this.unitUri, columnSemanticsUpdateDto.unitUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conceptUri, unitUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ColumnSemanticsUpdateDto {\n");
    
    sb.append("    conceptUri: ").append(toIndentedString(conceptUri)).append("\n");
    sb.append("    unitUri: ").append(toIndentedString(unitUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
