/*
 * Database Repository Container Service API
 * Service that manages the containers
 *
 * OpenAPI spec version: 1.1.0-alpha
 * Contact: andreas.rauber@tuwien.ac.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * ImageDateDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-12T11:48:18.502846+01:00[Europe/Vienna]")
public class ImageDateDto {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("example")
  private String example = null;

  @SerializedName("database_format")
  private String databaseFormat = null;

  @SerializedName("unix_format")
  private String unixFormat = null;

  @SerializedName("has_time")
  private Boolean hasTime = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  public ImageDateDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ImageDateDto example(String example) {
    this.example = example;
    return this;
  }

   /**
   * Get example
   * @return example
  **/
  @Schema(example = "30.01.2022", required = true, description = "")
  public String getExample() {
    return example;
  }

  public void setExample(String example) {
    this.example = example;
  }

  public ImageDateDto databaseFormat(String databaseFormat) {
    this.databaseFormat = databaseFormat;
    return this;
  }

   /**
   * Get databaseFormat
   * @return databaseFormat
  **/
  @Schema(example = "%d.%c.%Y", required = true, description = "")
  public String getDatabaseFormat() {
    return databaseFormat;
  }

  public void setDatabaseFormat(String databaseFormat) {
    this.databaseFormat = databaseFormat;
  }

  public ImageDateDto unixFormat(String unixFormat) {
    this.unixFormat = unixFormat;
    return this;
  }

   /**
   * Get unixFormat
   * @return unixFormat
  **/
  @Schema(example = "dd.MM.YYYY", required = true, description = "")
  public String getUnixFormat() {
    return unixFormat;
  }

  public void setUnixFormat(String unixFormat) {
    this.unixFormat = unixFormat;
  }

  public ImageDateDto hasTime(Boolean hasTime) {
    this.hasTime = hasTime;
    return this;
  }

   /**
   * Get hasTime
   * @return hasTime
  **/
  @Schema(example = "false", required = true, description = "")
  public Boolean isHasTime() {
    return hasTime;
  }

  public void setHasTime(Boolean hasTime) {
    this.hasTime = hasTime;
  }

  public ImageDateDto createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageDateDto imageDateDto = (ImageDateDto) o;
    return Objects.equals(this.id, imageDateDto.id) &&
        Objects.equals(this.example, imageDateDto.example) &&
        Objects.equals(this.databaseFormat, imageDateDto.databaseFormat) &&
        Objects.equals(this.unixFormat, imageDateDto.unixFormat) &&
        Objects.equals(this.hasTime, imageDateDto.hasTime) &&
        Objects.equals(this.createdAt, imageDateDto.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, example, databaseFormat, unixFormat, hasTime, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageDateDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    example: ").append(toIndentedString(example)).append("\n");
    sb.append("    databaseFormat: ").append(toIndentedString(databaseFormat)).append("\n");
    sb.append("    unixFormat: ").append(toIndentedString(unixFormat)).append("\n");
    sb.append("    hasTime: ").append(toIndentedString(hasTime)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
