app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: fda
        jdbc:
          time_zone: UTC
  application:
    name: gateway-service
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
management.endpoints.web.exposure.include: health,info,prometheus,gateway
server:
  port: 9095
  ssl:
    enabled: true
    key-alias: server
    key-store: "./server.keystore"
    key-store-type: jks
    key-store-password: password
    key-password: password
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: info
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  instance:
    hostname: gateway-service
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 9095
  client.serviceUrl.defaultZone: http://discovery-service:9090/eureka/
fda:
  ready.path: ./ready