spring:
  main.banner-mode: off
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  application:
    name: gateway-service
  cloud:
    loadbalancer.ribbon.enabled: false
management.endpoints.web.exposure.include: health,info,prometheus
server:
  port: 9095
  ssl:
    enabled: true
    key-alias: "${KEY_ALIAS}"
    key-store: "${KEY_STORE}"
    key-store-type: jks
    key-store-password: "${KEY_STORE_PASS}"
    key-password: "${KEY_PASS}"
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: "${LOG_LEVEL}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  instance:
    hostname: gateway-service
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 9095
  client.serviceUrl.defaultZone: http://discovery-service:9090/eureka/
fda:
  ready.path: /ready