app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Vienna
  application:
    name: fda-document-service
  cloud:
    loadbalancer.ribbon.enabled: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
server.port: 9099
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
    at.tuwien.gateway.: trace
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  instance.hostname: fda-document-service
  client.serviceUrl.defaultZone: http://localhost:9090/eureka/
fda:
  mount.path: /tmp
  ready.path: ./ready
  gateway.endpoint: "${GATEWAY_ENDPOINT}"
  document.endpoint: "${DOCUMENT_ENDPOINT}"