ALTER TABLE mdb_view_columns
    DROP SYSTEM VERSIONING;
ALTER TABLE mdb_view_columns
    CHANGE column_type column_type ENUM ('CHAR','VARCHAR','BINARY','VARBINARY','TINYBLOB','TINYTEXT','TEXT','BLOB','MEDIUMTEXT','MEDIUMBLOB','LONGTEXT','LONGBLOB','ENUM','SET','BIT','TINYINT','BOOL','SMALLINT','MEDIUMINT','INT','BIGINT','FLOAT','DOUBLE','DECIMAL','DATE','DATETIME','TIMESTAMP','TIME','YEAR','SERIAL') NOT NULL;
ALTER TABLE mdb_view_columns
    ADD SYSTEM VERSIONING;
ALTER TABLE mdb_columns
    DROP SYSTEM VERSIONING;
ALTER TABLE mdb_columns
    CHANGE Datatype Datatype ENUM ('CHAR','VARCHAR','BINARY','VARBINARY','TINYBLOB','TINYTEXT','TEXT','BLOB','MEDIUMTEXT','MEDIUMBLOB','LONGTEXT','LONGBLOB','ENUM','SET','BIT','TINYINT','BOOL','SMALLINT','MEDIUMINT','INT','BIGINT','FLOAT','DOUBLE','DECIMAL','DATE','DATETIME','TIMESTAMP','TIME','YEAR','SERIAL') NOT NULL;
ALTER TABLE mdb_columns
    ADD SYSTEM VERSIONING;