name: "Feature Request"
description: "Suggest a new feature or enhancement"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you're missing.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        If this issue requests multiple changes consider using checkboxes or lists.
    validations:
      required: false
