{
 "title": "DBRepo - Overview",
 "tags": [
  "provisioned",
  "dbrepo"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "tl;dr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QoS",
   "type": "stat",
   "description": "Quality of Service",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)*100/count(up)", "legendFormat": "Services Running" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(process_uptime_seconds)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dbrepo_database_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Datasources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dbrepo_view_count", "legendFormat": "__auto" },
    { "expr": "dbrepo_subset_count", "legendFormat": "__auto" },
    { "expr": "dbrepo_table_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dbrepo_volume_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Popular Data Sources",
   "type": "piechart",
   "description": "Top 10 by number of accesses",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, dbrepo_datasource_data_get_total)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  { "title": "UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "UI Response Time (avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(page_render_time)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UI Event Lag (avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_mean_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UI Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_active_handles{type=\"Server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UI Sockets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_active_handles{type=\"Socket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_active_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UI Response Time per Path (avg)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "page_render_time", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "NodeJS Heap Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes",
     "legendFormat": "{{space}}"
    }
   ]
  },
  { "title": "AMPQ / MQTT API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Broker Service QoS",
   "type": "stat",
   "description": "Quality of Service",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_channels*100/rabbitmq_channel_consumers",
     "legendFormat": "Services Running"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_connection_channels", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_channel_consumers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Persistent Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_persistent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready Messages",
   "type": "stat",
   "description": "Ready and unacknowledged messages stored in memory",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ram", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unacked Messages",
   "type": "stat",
   "description": "Messages delivered to consumers but not yet acknowledged",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Messages for received protocol messages",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_global_messages_received_total[$__range])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "process_open_fds\n", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Service QoS",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "description": "Heap and non-heap memory summed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (jvm_memory_used_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Popular Datasources",
   "type": "piechart",
   "description": "Top 10 by frequency of access",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, rate(dbrepo_table_data_get_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed API Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status!~\"200|201|202\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{instance}} ({{status}})"
    }
   ]
  }
 ]
}