<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>at.ac.tuwien.ifs.dbrepo</groupId>
        <artifactId>metadata-service</artifactId>
        <version>1.10.3</version>
    </parent>

    <name>report</name>
    <artifactId>report</artifactId>
    <version>1.10.3</version>

    <dependencies>
        <dependency>
            <groupId>at.ac.tuwien.ifs.dbrepo</groupId>
            <artifactId>rest-service</artifactId>
            <version>1.10.3</version>
        </dependency>
        <dependency>
            <groupId>at.ac.tuwien.ifs.dbrepo</groupId>
            <artifactId>services</artifactId>
            <version>1.10.3</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <executions>
                    <execution>
                        <id>report-aggregate</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>