FROM docker.io/jupyter/datascience-notebook:python-3.11 AS runtime
LABEL org.opencontainers.image.authors="martin.weise@tuwien.ac.at"
LABEL org.opencontainers.image.source="https://github.com/DBRepo-Project/dbrepo"

COPY ./environment.yml ./environment.yml
