{{ $pidBase := printf "https://%s/pid/" .Values.hostname }}
{{ $jwtIssuer := printf "https://%s/api/auth/realms/dbrepo" .Values.hostname }}
---
apiVersion: v1
kind: Secret
metadata:
  name: metadata-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  admin-email: "{{ .Values.metadataService.adminEmail }}"
  base-url: "{{ .Values.hostname }}"
  broker-endpoint: "{{ .Values.brokerService.url }}"
  broker-host: "{{ .Values.brokerService.host }}"
  broker-port: "{{ .Values.brokerService.port }}"
  gateway-endpoint: "{{ .Values.hostname }}"
  website: "{{ .Values.metadataService.website }}"
  search-username: "{{ .Values.searchdb.username }}"
  search-password: "{{ .Values.searchdb.password }}"
  broker-username: "{{ .Values.brokerService.auth.username }}"
  broker-password: "{{ .Values.brokerService.auth.password }}"
  log-level: "{{ ternary "trace" "info" .Values.metadataService.image.debug }}"
  metadata-db: "{{ .Values.metadataDb.db.name }}"
  metadata-host: "{{ .Values.metadataDb.host }}"
  metadata-username: "{{ .Values.metadataDb.rootUser.user }}"
  metadata-password: "{{ .Values.metadataDb.rootUser.password }}"
  metadata-jdbc-extra-args: "{{ .Values.metadataDb.jdbcExtraArgs }}"
  keycloak-host: "{{ .Values.metadataService.authService.url }}"
  keycloak-admin: "{{ .Values.authService.auth.adminUser }}"
  keycloak-admin-password: "{{ .Values.authService.auth.adminPassword }}"
  keycloak-client-secret: "{{ .Values.authService.client.secret }}"
  datacite-url: "{{ .Values.metadataService.datacite.url }}"
  datacite-prefix: "{{ .Values.metadataService.datacite.prefix | toString }}"
  datacite-username: "{{ .Values.metadataService.datacite.username }}"
  datacite-password: "{{ .Values.metadataService.datacite.password }}"
  repository-name: "{{ .Values.metadataService.repositoryName }}"
  pid-base: "{{ $pidBase }}"
  jwt-issuer: "{{ $jwtIssuer }}"
  broker-virtualhost: "{{ .Values.brokerService.virtualHost }}"
  queue-name: "{{ .Values.brokerService.queueName }}"
  exchange-name: "{{ .Values.brokerService.exchangeName }}"
  routing-key: "{{ .Values.brokerService.routingKey }}"
  connection-timeout: "{{ .Values.brokerService.connectionTimeout }}"
  min-concurrent-consumers: "{{ .Values.dataService.consumerConcurrentMin }}"
  max-concurrent-consumers: "{{ .Values.dataService.consumerConcurrentMax }}"
  requeue-rejected: "{{ .Values.dataService.requeueRejected }}"
  s3-storage-endpoint: http://storage-service-s3:9000
  s3-access-key-id: "{{ .Values.storageservice.s3.auth.username }}"
  s3-secret-access-key: "{{ .Values.storageservice.s3.auth.password }}"
  s3-import-bucket: "dbrepo-upload"
  s3-export-bucket: "dbrepo-download"
  delete-stale-files-rate: {{ .Values.metadataService.rates.deleteStaleFiles | quote }}
  mirror-rate: {{ .Values.metadataService.rates.mirror | quote }}
  obtain-metadata-rate: {{ .Values.metadataService.rates.obtainMetadata | quote }}
  delete-stale-queries-rate: {{ .Values.metadataService.rates.deleteStaleQueries | quote }}
