{{ $pidBase := printf "https://%s/pid/" .Values.hostname }}
{{ $jwtIssuer := printf "https://%s/api/auth/realms/dbrepo" .Values.hostname }}
---
apiVersion: v1
kind: Secret
metadata:
  name: metadata-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  admin-email: "{{ .Values.metadataService.adminEmail }}"
  base-url: "{{ .Values.hostname }}"
  broker-endpoint: "{{ index .Values "broker-service" "url" }}"
  broker-host: "{{ index .Values "broker-service" "host" }}"
  broker-port: "{{ index .Values "broker-service" "port" }}"
  gateway-endpoint: "{{ .Values.hostname }}"
  website: "{{ .Values.metadataService.website }}"
  search-username: "{{ index .Values "search-db" "username" }}"
  search-password: "{{ index .Values "search-db" "password" }}"
  broker-username: "{{ index .Values "broker-service" "auth" "username" }}"
  broker-password: "{{ index .Values "broker-service" "auth" "password" }}"
  log-level: "{{ ternary "trace" "info" .Values.metadataService.image.debug }}"
  metadata-db: "{{ index .Values "metadata-db" "db" "name" }}"
  metadata-host: "{{ index .Values "metadata-db" "host" }}"
  metadata-username: "{{ index .Values "metadata-db" "rootUser" "user" }}"
  metadata-password: "{{ index .Values "metadata-db" "rootUser" "password" }}"
  metadata-jdbc-extra-args: "{{ index .Values "metadata-db" "jdbcExtraArgs" }}"
  keycloak-host: "{{ .Values.metadataService.authService.url }}"
  keycloak-admin: "{{ index .Values "auth-service" "auth" "adminUser" }}"
  keycloak-admin-password: "{{ index .Values "auth-service" "auth" "adminPassword" }}"
  datacite-url: "{{ .Values.metadataService.datacite.url }}"
  datacite-prefix: "{{ .Values.metadataService.datacite.prefix | toString }}"
  datacite-username: "{{ .Values.metadataService.datacite.username }}"
  datacite-password: "{{ .Values.metadataService.datacite.password }}"
  repository-name: "{{ .Values.metadataService.repositoryName }}"
  pid-base: "{{ $pidBase }}"
  jwt-issuer: "{{ $jwtIssuer }}"
  broker-virtualhost: "{{ index .Values "broker-service" "virtualHost" }}"
  queue-name: "{{ index .Values "broker-service" "queueName" }}"
  exchange-name: "{{ index .Values "broker-service" "exchangeName" }}"
  routing-key: "{{ index .Values "broker-service" "routingKey" }}"
  connection-timeout: "{{ index .Values "broker-service" "connectionTimeout" }}"
  min-concurrent-consumers: "{{ .Values.dataService.consumerConcurrentMin }}"
  max-concurrent-consumers: "{{ .Values.dataService.consumerConcurrentMax }}"
  requeue-rejected: "{{ .Values.dataService.requeueRejected }}"
  s3-storage-endpoint: http://storage-service-s3:9000
  s3-access-key-id: seaweedfsadmin
  s3-secret-access-key: seaweedfsadmin
  s3-import-bucket: dbrepo-upload
  s3-export-bucket: dbrepo-download
  mirror-rate: {{ .Values.metadataService.rates.mirror | quote }}
  obtain-metadata-rate: {{ .Values.metadataService.rates.obtainMetadata | quote }}
  delete-stale-queries-rate: {{ .Values.metadataService.rates.deleteStaleQueries | quote }}
