{{- if .Values.analyseService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyse-service
  namespace: {{ .Values.namespace }}
  labels:
    app: analyse-service
    service: analyse-service
spec:
  replicas: {{ .Values.analyseService.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: analyse-service
      service: analyse-service
  template:
    metadata:
      labels:
        app: analyse-service
        service: analyse-service
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: analyse-service
          image: {{ .Values.analyseService.image.name }}
          imagePullPolicy: {{ .Values.analyseService.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: {{ .Values.analyseService.profileType | default "RuntimeDefault" }}
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: analyse-service-secret
                  key: log-level
            - name: S3_STORAGE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: analyse-service-secret
                  key: s3-storage-endpoint
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: analyse-service-secret
                  key: s3-access-key-id
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: analyse-service-secret
                  key: s3-secret-access-key
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:5000/health | grep 'UP' || exit 1"
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - "curl -sSL localhost:5000/health | grep 'UP' || exit 1"
            initialDelaySeconds: 10
            periodSeconds: 30
{{- end }}
