{{- if .Values.analyseService.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: analyse-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  log-level: "{{ ternary "DEBUG" "INFO" .Values.analyseService.image.debug }}"
  s3-storage-endpoint: "http://storage-service-s3:9000"
  s3-access-key-id: "seaweedfsadmin"
  s3-secret-access-key: "seaweedfsadmin"
{{- end }}
