# coding: utf-8

"""
    Database Repository Authentication Service API

    Service that manages the authentication  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserTokenModifyDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'invenio_token': 'str'
    }

    attribute_map = {
        'invenio_token': 'invenio_token'
    }

    def __init__(self, invenio_token=None):  # noqa: E501
        """UserTokenModifyDto - a model defined in Swagger"""  # noqa: E501
        self._invenio_token = None
        self.discriminator = None
        self.invenio_token = invenio_token

    @property
    def invenio_token(self):
        """Gets the invenio_token of this UserTokenModifyDto.  # noqa: E501


        :return: The invenio_token of this UserTokenModifyDto.  # noqa: E501
        :rtype: str
        """
        return self._invenio_token

    @invenio_token.setter
    def invenio_token(self, invenio_token):
        """Sets the invenio_token of this UserTokenModifyDto.


        :param invenio_token: The invenio_token of this UserTokenModifyDto.  # noqa: E501
        :type: str
        """
        if invenio_token is None:
            raise ValueError("Invalid value for `invenio_token`, must not be `None`")  # noqa: E501

        self._invenio_token = invenio_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserTokenModifyDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserTokenModifyDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
