app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: jdbc:mariadb://localhost:3306/fda
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dbrepo
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: fda
        jdbc:
          time_zone: UTC
  application:
    name: container-service
  cloud:
    loadbalancer.ribbon.enabled: false
management.endpoints.web.exposure.include: health,info,prometheus
springdoc.swagger-ui.enabled: true
server.port: 9091
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: trace
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  instance.hostname: container-service
  client.serviceUrl.defaultZone: http://localhost:9090/eureka/
fda:
  network: userdb
  mount.path: /tmp
  ready.path: ./ready
  gateway.endpoint: http://localhost:9095