---

_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      # Either enables or disables anonymous authentication. When true, HTTP authenticators try to find user credentials in
      # the HTTP request. If credentials are found, the user is authenticated. If none are found, the user is authenticated
      # as an “anonymous” user. This user then has the username “anonymous” and one role named “anonymous_backendrole”.
      # When you enable anonymous authentication, all defined HTTP authenticators are non-challenging. Also see The
      # challenge setting.
      anonymous_auth_enabled: true
      xff:
        enabled: false
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: client_id
            roles_key: roles
            openid_connect_url: http://auth-service:8080/api/auth/realms/dbrepo/.well-known/openid-configuration
        authentication_backend:
          type: noop
