# coding: utf-8

"""
    Database Repository Analyse Service API

    Service that manages the analysis  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DetermineDataTypeRequestDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'filepath': 'str',
        'enum': 'bool',
        'enum_tol': 'object',
        'separator': 'str'
    }

    attribute_map = {
        'filepath': 'filepath',
        'enum': 'enum',
        'enum_tol': 'enum_tol',
        'separator': 'separator'
    }

    def __init__(self, filepath=None, enum=None, enum_tol=None, separator=None):  # noqa: E501
        """DetermineDataTypeRequestDto - a model defined in Swagger"""  # noqa: E501
        self._filepath = None
        self._enum = None
        self._enum_tol = None
        self._separator = None
        self.discriminator = None
        self.filepath = filepath
        if enum is not None:
            self.enum = enum
        if enum_tol is not None:
            self.enum_tol = enum_tol
        if separator is not None:
            self.separator = separator

    @property
    def filepath(self):
        """Gets the filepath of this DetermineDataTypeRequestDto.  # noqa: E501


        :return: The filepath of this DetermineDataTypeRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._filepath

    @filepath.setter
    def filepath(self, filepath):
        """Sets the filepath of this DetermineDataTypeRequestDto.


        :param filepath: The filepath of this DetermineDataTypeRequestDto.  # noqa: E501
        :type: str
        """
        if filepath is None:
            raise ValueError("Invalid value for `filepath`, must not be `None`")  # noqa: E501

        self._filepath = filepath

    @property
    def enum(self):
        """Gets the enum of this DetermineDataTypeRequestDto.  # noqa: E501


        :return: The enum of this DetermineDataTypeRequestDto.  # noqa: E501
        :rtype: bool
        """
        return self._enum

    @enum.setter
    def enum(self, enum):
        """Sets the enum of this DetermineDataTypeRequestDto.


        :param enum: The enum of this DetermineDataTypeRequestDto.  # noqa: E501
        :type: bool
        """

        self._enum = enum

    @property
    def enum_tol(self):
        """Gets the enum_tol of this DetermineDataTypeRequestDto.  # noqa: E501


        :return: The enum_tol of this DetermineDataTypeRequestDto.  # noqa: E501
        :rtype: object
        """
        return self._enum_tol

    @enum_tol.setter
    def enum_tol(self, enum_tol):
        """Sets the enum_tol of this DetermineDataTypeRequestDto.


        :param enum_tol: The enum_tol of this DetermineDataTypeRequestDto.  # noqa: E501
        :type: object
        """

        self._enum_tol = enum_tol

    @property
    def separator(self):
        """Gets the separator of this DetermineDataTypeRequestDto.  # noqa: E501


        :return: The separator of this DetermineDataTypeRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._separator

    @separator.setter
    def separator(self, separator):
        """Sets the separator of this DetermineDataTypeRequestDto.


        :param separator: The separator of this DetermineDataTypeRequestDto.  # noqa: E501
        :type: str
        """

        self._separator = separator

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DetermineDataTypeRequestDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DetermineDataTypeRequestDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
