FROM opensearchproject/opensearch-dashboards:2.8.0
MAINTAINER Martin Weise <martin.weise@tuwien.ac.at>

RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin remove securityDashboards

EXPOSE 5601