app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: jdbc:mariadb://localhost:3306/fda
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dbrepo
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: fda
        jdbc:
          time_zone: UTC
  application:
    name: discovery-service
  rabbitmq:
    host: localhost
    username: fda
    password: fda
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
management.endpoints.web.exposure.include: health,info,prometheus
server:
  port: 9090
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: info
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl.defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: discovery-service
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 9090
fda:
  ready.path: ./ready
  gateway.endpoint: http://localhost:9095