app.version: '@project.version@'
spring:
  main.banner-mode: off
  application:
    name: discovery-service
  cloud:
    loadbalancer.ribbon.enabled: false
  autoconfigure.exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
management.endpoints.web.exposure.include: health,info,prometheus
server.port: 9090
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: info
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  eureka.client.register-with-eureka: false
  eureka.client.fetch-registry: false
  instance.hostname: discovery-service
  client.serviceUrl.defaultZone: http://localhost:9090/eureka/
fda:
  ready.path: ./ready