#!/bin/bash

# set version
TAG=latest

# tear everything down
/bin/bash teardown
echo "Pulling new images ..."
docker pull "dbrepo/analyse-service:${TAG}"
docker pull "dbrepo/authentication-service:${TAG}"
docker pull "dbrepo/metadata-db:${TAG}"
docker pull "dbrepo/ui:${TAG}"
docker pull "dbrepo/ui-proxy:${TAG}"
docker pull "dbrepo/identifier-service:${TAG}"
docker pull "dbrepo/container-service:${TAG}"
docker pull "dbrepo/database-service:${TAG}"
docker pull "dbrepo/discovery-service:${TAG}"
docker pull "dbrepo/gateway-service:${TAG}"
docker pull "dbrepo/query-service:${TAG}"
docker pull "dbrepo/table-service:${TAG}"
docker pull "dbrepo/units-service:${TAG}"
docker pull "dbrepo/broker-service:${TAG}"
docker pull "dbrepo/metadata-service:${TAG}"
echo "Pulled new images"

# deploy dbrepo
echo "Deploy DBRepo ..."
docker compose -f ./docker-compose.yml up -d

# clone tuw specific deployment
if [ ! -d "/home/gitlab-runner/dbrepo-tuw" ]; then
    git clone ssh://git@gitlab.tuwien.ac.at:822/martin.weise/dbrepo-tuw.git || exit 2
fi

# build tuw specific deployment
docker compose -f ./dbrepo-tuw/docker-compose.dbrepo2.yml build || exit 3
docker compose -f ./dbrepo-tuw/docker-compose.dbrepo2.yml up -d || exit 4
echo "Deployed TU Wien specific deployment"