# /opt/bitnami/nginx/conf/stream.conf.d/dbrepo-tcp.conf

stream {
    upstream data_db {
        server dbrepo-data-db:3306;  # internal Docker hostname + port
    }

    server {
        listen 3307 ssl;              # expose as 3307 externally
        proxy_pass data_db;

        # SSL passthrough for encryption if needed (optional)
        ssl_certificate     /app/fullchain.pem;
        ssl_certificate_key /app/privkey.pem;
    }
}
