# coding: utf-8

"""
    Database Repository Table Service API

    Service that manages the tables  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ColumnCreateDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'dfid': 'int',
        'unique': 'bool',
        'references': 'str',
        'primary_key': 'bool',
        'null_allowed': 'bool',
        'check_expression': 'str',
        'foreign_key': 'str',
        'enum_values': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'dfid': 'dfid',
        'unique': 'unique',
        'references': 'references',
        'primary_key': 'primary_key',
        'null_allowed': 'null_allowed',
        'check_expression': 'check_expression',
        'foreign_key': 'foreign_key',
        'enum_values': 'enum_values'
    }

    def __init__(self, name=None, type=None, dfid=None, unique=None, references=None, primary_key=None, null_allowed=None, check_expression=None, foreign_key=None, enum_values=None):  # noqa: E501
        """ColumnCreateDto - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._type = None
        self._dfid = None
        self._unique = None
        self._references = None
        self._primary_key = None
        self._null_allowed = None
        self._check_expression = None
        self._foreign_key = None
        self._enum_values = None
        self.discriminator = None
        self.name = name
        self.type = type
        if dfid is not None:
            self.dfid = dfid
        self.unique = unique
        if references is not None:
            self.references = references
        self.primary_key = primary_key
        self.null_allowed = null_allowed
        if check_expression is not None:
            self.check_expression = check_expression
        if foreign_key is not None:
            self.foreign_key = foreign_key
        if enum_values is not None:
            self.enum_values = enum_values

    @property
    def name(self):
        """Gets the name of this ColumnCreateDto.  # noqa: E501


        :return: The name of this ColumnCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ColumnCreateDto.


        :param name: The name of this ColumnCreateDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this ColumnCreateDto.  # noqa: E501


        :return: The type of this ColumnCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ColumnCreateDto.


        :param type: The type of this ColumnCreateDto.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["ColumnTypeDto.ENUM", "ColumnTypeDto.NUMBER", "ColumnTypeDto.DECIMAL", "ColumnTypeDto.STRING", "ColumnTypeDto.TEXT", "ColumnTypeDto.BOOLEAN", "ColumnTypeDto.DATE", "ColumnTypeDto.TIMESTAMP", "ColumnTypeDto.BLOB"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def dfid(self):
        """Gets the dfid of this ColumnCreateDto.  # noqa: E501


        :return: The dfid of this ColumnCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._dfid

    @dfid.setter
    def dfid(self, dfid):
        """Sets the dfid of this ColumnCreateDto.


        :param dfid: The dfid of this ColumnCreateDto.  # noqa: E501
        :type: int
        """

        self._dfid = dfid

    @property
    def unique(self):
        """Gets the unique of this ColumnCreateDto.  # noqa: E501


        :return: The unique of this ColumnCreateDto.  # noqa: E501
        :rtype: bool
        """
        return self._unique

    @unique.setter
    def unique(self, unique):
        """Sets the unique of this ColumnCreateDto.


        :param unique: The unique of this ColumnCreateDto.  # noqa: E501
        :type: bool
        """
        if unique is None:
            raise ValueError("Invalid value for `unique`, must not be `None`")  # noqa: E501

        self._unique = unique

    @property
    def references(self):
        """Gets the references of this ColumnCreateDto.  # noqa: E501


        :return: The references of this ColumnCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._references

    @references.setter
    def references(self, references):
        """Sets the references of this ColumnCreateDto.


        :param references: The references of this ColumnCreateDto.  # noqa: E501
        :type: str
        """

        self._references = references

    @property
    def primary_key(self):
        """Gets the primary_key of this ColumnCreateDto.  # noqa: E501


        :return: The primary_key of this ColumnCreateDto.  # noqa: E501
        :rtype: bool
        """
        return self._primary_key

    @primary_key.setter
    def primary_key(self, primary_key):
        """Sets the primary_key of this ColumnCreateDto.


        :param primary_key: The primary_key of this ColumnCreateDto.  # noqa: E501
        :type: bool
        """
        if primary_key is None:
            raise ValueError("Invalid value for `primary_key`, must not be `None`")  # noqa: E501

        self._primary_key = primary_key

    @property
    def null_allowed(self):
        """Gets the null_allowed of this ColumnCreateDto.  # noqa: E501


        :return: The null_allowed of this ColumnCreateDto.  # noqa: E501
        :rtype: bool
        """
        return self._null_allowed

    @null_allowed.setter
    def null_allowed(self, null_allowed):
        """Sets the null_allowed of this ColumnCreateDto.


        :param null_allowed: The null_allowed of this ColumnCreateDto.  # noqa: E501
        :type: bool
        """
        if null_allowed is None:
            raise ValueError("Invalid value for `null_allowed`, must not be `None`")  # noqa: E501

        self._null_allowed = null_allowed

    @property
    def check_expression(self):
        """Gets the check_expression of this ColumnCreateDto.  # noqa: E501


        :return: The check_expression of this ColumnCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._check_expression

    @check_expression.setter
    def check_expression(self, check_expression):
        """Sets the check_expression of this ColumnCreateDto.


        :param check_expression: The check_expression of this ColumnCreateDto.  # noqa: E501
        :type: str
        """

        self._check_expression = check_expression

    @property
    def foreign_key(self):
        """Gets the foreign_key of this ColumnCreateDto.  # noqa: E501


        :return: The foreign_key of this ColumnCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._foreign_key

    @foreign_key.setter
    def foreign_key(self, foreign_key):
        """Sets the foreign_key of this ColumnCreateDto.


        :param foreign_key: The foreign_key of this ColumnCreateDto.  # noqa: E501
        :type: str
        """

        self._foreign_key = foreign_key

    @property
    def enum_values(self):
        """Gets the enum_values of this ColumnCreateDto.  # noqa: E501


        :return: The enum_values of this ColumnCreateDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._enum_values

    @enum_values.setter
    def enum_values(self, enum_values):
        """Sets the enum_values of this ColumnCreateDto.


        :param enum_values: The enum_values of this ColumnCreateDto.  # noqa: E501
        :type: list[str]
        """

        self._enum_values = enum_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ColumnCreateDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ColumnCreateDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
