CREATE USER IF NOT EXISTS junit1 IDENTIFIED BY 'junit1';
CREATE USER IF NOT EXISTS junit2 IDENTIFIED BY 'junit2';
CREATE USER IF NOT EXISTS junit3 IDENTIFIED BY 'junit3';
CREATE USER IF NOT EXISTS junit4 IDENTIFIED BY 'junit4';