apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  db-host: "{{ index .Values "auth-db" "host" }}"
  db-port: "{{ index .Values "auth-db" "port" }}"
  db-name: "{{ index .Values "auth-db" "postgresql" "database" }}"
  db-username: "{{ index .Values "auth-db" "postgresql" "username" }}"
  db-password: "{{ index .Values "auth-db" "postgresql" "password" }}"
