apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  db-host: "{{ .Values.authDb.host }}"
  db-port: "{{ .Values.authDb.port }}"
  db-name: "{{ .Values.authDb.postgresql.database }}"
  db-username: "{{ .Values.authDb.postgresql.username }}"
  db-password: "{{ .Values.authDb.postgresql.password }}"
