apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
stringData:
  seaweedfs_s3_config: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": "{{ index .Values "storage-service" "s3" "auth" "username" }}",
              "secretKey": "{{ index .Values "storage-service" "s3" "auth" "password" }}"
            }
          ],
          "actions": [
            "Read",
            "Write",
            "List",
            "Tagging",
            "Admin"
          ]
        }
      ]
    }

