application:
  title: DBRepo
  version: '@project.version@'
spring:
  datasource:
    url: jdbc:h2:mem:fda;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS FDA;NON_KEYWORDS=value
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  rabbitmq:
    host: "${BROKER_HOST:broker-service}"
    virtual-host: "${BROKER_VIRTUALHOST:dbrepo}"
    password: "${BROKER_PASSWORD:fda}"
    username: "${BROKER_USERNAME:fda}"
    port: ${BROKER_PORT:5672}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: fda
        jdbc:
          time_zone: UTC
  application:
    name: data-service
  main:
    banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
server:
  port: 8080
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: "${LOG_LEVEL:info}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
dbrepo:
  endpoints:
    gatewayService: "${GATEWAY_SERVICE_ENDPOINT:http://gateway-service}"
    storageService: "${S3_ENDPOINT:http://storage-service:9000}"
    authService: "${AUTH_SERVICE_HOST:http://auth-service:8080}"
  s3:
    accessKeyId: "${S3_ACCESS_KEY_ID:seaweedfsadmin}"
    secretAccessKey: "${S3_SECRET_ACCESS_KEY:seaweedfsadmin}"
    importBucket: "${S3_IMPORT_BUCKET:dbrepo-upload}"
    exportBucket: "${S3_EXPORT_BUCKET:dbrepo-download}"
    filePath: "${S3_FILE_PATH:/tmp}"
  admin:
    username: "${ADMIN_USERNAME:admin}"
    password: "${ADMIN_PASSWORD:admin}"
  jwt:
    public_key: "${JWT_PUBKEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqqnHQ2BWWW9vDNLRCcxD++xZg/16oqMo/c1l+lcFEjjAIJjJp/HqrPYU/U9GvquGE6PbVFtTzW1KcKawOW+FJNOA3CGo8Q1TFEfz43B8rZpKsFbJKvQGVv1Z4HaKPvLUm7iMm8Hv91cLduuoWx6Q3DPe2vg13GKKEZe7UFghF+0T9u8EKzA/XqQ0OiICmsmYPbwvf9N3bCKsB/Y10EYmZRb8IhCoV9mmO5TxgWgiuNeCTtNCv2ePYqL/U0WvyGFW0reasIK8eg3KrAUj8DpyOgPOVBn3lBGf+3KFSYi+0bwZbJZWqbC/Xlk20Go1YfeJPRIt7ImxD27R/lNjgDO/MwIDAQAB}"
  keycloak:
    username: "${AUTH_SERVICE_ADMIN:fda}"
    password: "${AUTH_SERVICE_ADMIN_PASSWORD:fda}"
    client: "${AUTH_SERVICE_CLIENT:dbrepo-client}"
    clientSecret: "${AUTH_SERVICE_CLIENT_SECRET:MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG}"
  sql:
    forbidden: "${NOT_SUPPORTED_KEYWORDS:\\*,AVG,BIT_AND,BIT_OR,BIT_XOR,COUNT,COUNTDISTINCT,GROUP_CONCAT,JSON_ARRAYAGG,JSON_OBJECTAGG,MAX,MIN,STD,STDDEV,STDDEV_POP,STDDEV_SAMP,SUM,VARIANCE,VAR_POP,VAR_SAMP,--}"
  grant:
    default:
      read: "${GRANT_DEFAULT_READ:SELECT}"
      write: "${GRANT_DEFAULT_WRITE:SELECT, CREATE, CREATE VIEW, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, INDEX, TRIGGER, INSERT, UPDATE, DELETE}"
  minConcurrent: "${MIN_CONCURRENT_CONSUMERS:2}"
  maxConcurrent: "${MAX_CONCURRENT_CONSUMERS:6}"
  requeueRejected: ${REQUEUE_REJECTED:false}
  queueName: "${BROKER_QUEUE_NAME:dbrepo}"
  exchangeName: "${BROKER_EXCHANGE_NAME:dbrepo}"
  routingKey: "${BROKER_ROUTING_KEY:#}"
  connectionTimeout: ${CONNECTION_TIMEOUT:10000}