server:
  port: 18080
dbrepo:
  endpoints:
    metadataService: http://localhost:9099
    storageService: http://localhost:9000
    authService: http://localhost:8080
    computeService: local[*]
logging:
  level:
    at.ac.tuwien.ifs.dbrepo.: trace
