spring:
  main.banner-mode: off
  datasource:
    url: jdbc:mariadb://metadata-db:3306/fda
    driver-class-name: org.mariadb.jdbc.Driver
    username: "${METADATA_USERNAME}"
    password: "${METADATA_PASSWORD}"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  application:
    name: discovery-service
  cloud:
    loadbalancer.ribbon.enabled: false
management.endpoints.web.exposure.include: health,info,prometheus
server:
  port: 9090
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: "${LOG_LEVEL}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl.defaultZone: http://discovery-service:9090/eureka/
  instance:
    hostname: discovery-service
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 9090
fda:
  ready.path: /ready