# coding: utf-8

"""
    Database Repository Document Service API

    Service that manages the documents  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreatorDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role': 'str',
        'affiliations': 'list[AffiliationDto]',
        'person_or_org': 'PersonOrOrganizationDto'
    }

    attribute_map = {
        'role': 'role',
        'affiliations': 'affiliations',
        'person_or_org': 'person_or_org'
    }

    def __init__(self, role=None, affiliations=None, person_or_org=None):  # noqa: E501
        """CreatorDto - a model defined in Swagger"""  # noqa: E501
        self._role = None
        self._affiliations = None
        self._person_or_org = None
        self.discriminator = None
        if role is not None:
            self.role = role
        if affiliations is not None:
            self.affiliations = affiliations
        self.person_or_org = person_or_org

    @property
    def role(self):
        """Gets the role of this CreatorDto.  # noqa: E501


        :return: The role of this CreatorDto.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this CreatorDto.


        :param role: The role of this CreatorDto.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def affiliations(self):
        """Gets the affiliations of this CreatorDto.  # noqa: E501


        :return: The affiliations of this CreatorDto.  # noqa: E501
        :rtype: list[AffiliationDto]
        """
        return self._affiliations

    @affiliations.setter
    def affiliations(self, affiliations):
        """Sets the affiliations of this CreatorDto.


        :param affiliations: The affiliations of this CreatorDto.  # noqa: E501
        :type: list[AffiliationDto]
        """

        self._affiliations = affiliations

    @property
    def person_or_org(self):
        """Gets the person_or_org of this CreatorDto.  # noqa: E501


        :return: The person_or_org of this CreatorDto.  # noqa: E501
        :rtype: PersonOrOrganizationDto
        """
        return self._person_or_org

    @person_or_org.setter
    def person_or_org(self, person_or_org):
        """Sets the person_or_org of this CreatorDto.


        :param person_or_org: The person_or_org of this CreatorDto.  # noqa: E501
        :type: PersonOrOrganizationDto
        """
        if person_or_org is None:
            raise ValueError("Invalid value for `person_or_org`, must not be `None`")  # noqa: E501

        self._person_or_org = person_or_org

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreatorDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreatorDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
