# coding: utf-8

"""
    Database Repository Document Service API

    Service that manages the documents  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateDraftDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access': 'AccessOptionsDto',
        'files': 'FilesOptionsDto',
        'metadata': 'MetadataDto'
    }

    attribute_map = {
        'access': 'access',
        'files': 'files',
        'metadata': 'metadata'
    }

    def __init__(self, access=None, files=None, metadata=None):  # noqa: E501
        """CreateDraftDto - a model defined in Swagger"""  # noqa: E501
        self._access = None
        self._files = None
        self._metadata = None
        self.discriminator = None
        self.access = access
        self.files = files
        self.metadata = metadata

    @property
    def access(self):
        """Gets the access of this CreateDraftDto.  # noqa: E501


        :return: The access of this CreateDraftDto.  # noqa: E501
        :rtype: AccessOptionsDto
        """
        return self._access

    @access.setter
    def access(self, access):
        """Sets the access of this CreateDraftDto.


        :param access: The access of this CreateDraftDto.  # noqa: E501
        :type: AccessOptionsDto
        """
        if access is None:
            raise ValueError("Invalid value for `access`, must not be `None`")  # noqa: E501

        self._access = access

    @property
    def files(self):
        """Gets the files of this CreateDraftDto.  # noqa: E501


        :return: The files of this CreateDraftDto.  # noqa: E501
        :rtype: FilesOptionsDto
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this CreateDraftDto.


        :param files: The files of this CreateDraftDto.  # noqa: E501
        :type: FilesOptionsDto
        """
        if files is None:
            raise ValueError("Invalid value for `files`, must not be `None`")  # noqa: E501

        self._files = files

    @property
    def metadata(self):
        """Gets the metadata of this CreateDraftDto.  # noqa: E501


        :return: The metadata of this CreateDraftDto.  # noqa: E501
        :rtype: MetadataDto
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this CreateDraftDto.


        :param metadata: The metadata of this CreateDraftDto.  # noqa: E501
        :type: MetadataDto
        """
        if metadata is None:
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateDraftDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateDraftDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
