{{- if .Values.uploadService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  namespace: {{ .Values.namespace }}
  labels:
    app: upload-service
    service: upload-service
spec:
  replicas: {{ .Values.uploadService.replicaCount }}
  strategy:
    type: {{ $.Values.strategyType }}
  selector:
    matchLabels:
      app: upload-service
      service: upload-service
  template:
    metadata:
      labels:
        app: upload-service
        service: upload-service
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: upload-service
          image: {{ printf "%s/%s:%s" .Values.uploadService.image.registry .Values.uploadService.image.repository .Values.uploadService.image.tag }}
          imagePullPolicy: {{ .Values.uploadService.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: upload-service-secret
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: upload-service-secret
                  key: aws-secret-access-key
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: upload-service-secret
                  key: aws-region
          args:
            - "--base-path=/api/upload/files/"
            - "-s3-endpoint=http://storage-service-s3:9000"
            - "-s3-bucket=dbrepo-upload"
          ports:
            - containerPort: 1080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 1080
          readinessProbe:
            httpGet:
              port: 1080
            initialDelaySeconds: 10
            periodSeconds: 30
{{- end }}
