{{- if .Values.uploadService.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: upload-service-secret
  namespace: {{ .Values.namespace }}
stringData:
  aws-access-key-id: "{{ .Values.storageService.s3.auth.username }}"
  aws-secret-access-key: "{{ .Values.storageService.s3.auth.password }}"
  aws-region: "default"
{{- end }}