app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: jdbc:mariadb://metadata-db:3306/fda
    driver-class-name: org.mariadb.jdbc.Driver
    username: "${METADATA_USERNAME}"
    password: "${METADATA_PASSWORD}"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: fda
        jdbc:
          time_zone: UTC
  application:
    name: user-service
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
management.endpoints.web.exposure.include: health,info,prometheus
server:
  port: 9098
  ssl:
    enabled: true
    key-alias: "${KEY_ALIAS}"
    key-store: "${KEY_STORE}"
    key-store-type: jks
    key-store-password: "${KEY_STORE_PASS}"
    key-password: "${KEY_PASS}"
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: "${LOG_LEVEL}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  instance:
    hostname: user-service
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 9098
  client.serviceUrl.defaultZone: http://discovery-service:9090/eureka/
fda:
  ready.path: /ready
  gateway.endpoint: "${GATEWAY_ENDPOINT}"
  keycloak:
    username: "${KEYCLOAK_ADMIN}"
    password: "${KEYCLOAK_ADMIN_PASSWORD}"
  jwt:
    issuer: "${JWT_ISSUER}"
    public_key: "${JWT_PUBKEY}"