package at.tuwien.api.database.table.columns;

import at.tuwien.api.container.image.ImageDateDto;
import at.tuwien.api.database.table.columns.concepts.ConceptDto;
import at.tuwien.api.database.table.columns.concepts.UnitDto;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import lombok.extern.jackson.Jacksonized;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;

import java.util.List;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Jacksonized
@ToString
@Document(indexName = "column")
public class ColumnDto {

    @Id
    @NotNull
    private Long id;

    @Id
    @NotNull
    @Field(name = "database_id")
    @JsonProperty("database_id")
    private Long databaseId;

    @Id
    @NotNull
    @Field(name = "table_id")
    @JsonProperty("table_id")
    private Long tableId;

    @NotBlank
    @Schema(example = "Date")
    private String name;

    @NotBlank
    @JsonProperty("internal_name")
    @Field(name = "internal_name")
    @Schema(example = "mdb_date")
    private String internalName;

    @JsonProperty("date_format")
    @Field(name = "date_format")
    private ImageDateDto dateFormat;

    @NotNull
    @JsonProperty("auto_generated")
    @Field(name = "auto_generated")
    @Schema(example = "false")
    private Boolean autoGenerated;

    @NotNull
    @JsonProperty("is_primary_key")
    @Field(name = "is_primary_key")
    @Schema(example = "true")
    private Boolean isPrimaryKey;

    @Field(name = "index_length")
    @JsonProperty("index_length")
    private Integer indexLength;

    @NotNull
    @JsonProperty("column_type")
    @Field(name = "column_type")
    @Schema(example = "string")
    private ColumnTypeDto columnType;

    @Schema(example = "255")
    private Integer size;

    @Schema(example = "0")
    private Integer d;

    private ConceptDto concept;

    private UnitDto unit;

    @NotNull
    @JsonProperty("is_public")
    @Field(name = "is_public")
    @Schema(example = "true")
    private Boolean isPublic;

    @NotNull
    @JsonProperty("is_null_allowed")
    @Field(name = "is_null_allowed")
    @Schema(example = "false")
    private Boolean isNullAllowed;

    @Parameter(description = "enum values, only considered when type = ENUM")
    private List<ColumnEnumDto> enums;

    @Parameter(description = "enum values, only considered when type = ENUM")
    private List<ColumnSetDto> sets;

}
