---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: ingress-tls-cert
  namespace: {{ .Values.namespace }}
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDrjCCApagAwIBAgIUDYyFqUpOv4X5lrVdHmSYmdcZMqQwDQYJKoZIhvcNAQEL
    BQAwRDETMBEGA1UEAwwKZGJyZXBvLmFwcDELMAkGA1UEBhMCQVQxDzANBgNVBAgM
    BlZpZW5uYTEPMA0GA1UEBwwGVmllbm5hMB4XDTI0MDQwODA2NDYxOFoXDTI1MDQw
    ODA2NDYxOFowRDETMBEGA1UEAwwKZGJyZXBvLmFwcDELMAkGA1UEBhMCQVQxDzAN
    BgNVBAgMBlZpZW5uYTEPMA0GA1UEBwwGVmllbm5hMIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEAvxE/sh9kySmHV1CWriicftdWOUQH2KmMKBud9Gklcj7G
    MBdQxtMbwqSV5NJpF0WlA7hVX2BLdOTn0M4HPkS8VfXkbloW6uBsiPkXpX16LVe3
    p3bTaKRipeoLnRU6qF586wwMnYBYafym3v0xXkO8pjo1f23ry5E185hhjyQGxihI
    T15bEWkQmCJvvSu+MB/zuUTPjuCBSQWA8VvRRor8IqLCs8CHjqTcrmVWoyxSIKZy
    xJqb/VwJYjc1w6yEYM5UNEdcpk5lot3Lhns/3mVrpQBCEtwGp9UtwyW27PuqPnJk
    Sj8R0RNB458ne+XmPJi7atZ4M1qcgDSHhT1ly1xx2wIDAQABo4GXMIGUMB0GA1Ud
    DgQWBBQnJaxVcby97xhkAMXnXtGvxB6m0DAfBgNVHSMEGDAWgBQnJaxVcby97xhk
    AMXnXtGvxB6m0DAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEG
    CCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwFQYDVR0RBA4wDIIKZGJyZXBvLmFwcDAN
    BgkqhkiG9w0BAQsFAAOCAQEARxV88dr1rpmJvth7LGEstHrgyBn8NISTkCJtY3UL
    mIi4WEyAgqAdN4ZJ7R5WREm7rz3VPGrvAwD9rxrTxMdzyy+AifX8E2zXsaGYU5s+
    FkcExZ1pCKpc5Ioa1MovaFkAXHTlv919c+HAa1B2EFYq6uVuldltbdAqKpLam+A/
    emS4RITCi19717Q+0gom/zfUKm1ajwTTpI9BzyIEthQvUTG6crtW0R2rW26pbwco
    wizrhnLFNZJp+AyB+UZqBh9Ezii2hyM/CiK7p48j1/TCA6zpjzFSXzq1gopvhJpA
    Xskj/uAu/souD8WdkAUz4eFitIj2+cTNAmvUt/YiJ5ji3Q==
    -----END CERTIFICATE-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDrjCCApagAwIBAgIUDYyFqUpOv4X5lrVdHmSYmdcZMqQwDQYJKoZIhvcNAQEL
    BQAwRDETMBEGA1UEAwwKZGJyZXBvLmFwcDELMAkGA1UEBhMCQVQxDzANBgNVBAgM
    BlZpZW5uYTEPMA0GA1UEBwwGVmllbm5hMB4XDTI0MDQwODA2NDYxOFoXDTI1MDQw
    ODA2NDYxOFowRDETMBEGA1UEAwwKZGJyZXBvLmFwcDELMAkGA1UEBhMCQVQxDzAN
    BgNVBAgMBlZpZW5uYTEPMA0GA1UEBwwGVmllbm5hMIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEAvxE/sh9kySmHV1CWriicftdWOUQH2KmMKBud9Gklcj7G
    MBdQxtMbwqSV5NJpF0WlA7hVX2BLdOTn0M4HPkS8VfXkbloW6uBsiPkXpX16LVe3
    p3bTaKRipeoLnRU6qF586wwMnYBYafym3v0xXkO8pjo1f23ry5E185hhjyQGxihI
    T15bEWkQmCJvvSu+MB/zuUTPjuCBSQWA8VvRRor8IqLCs8CHjqTcrmVWoyxSIKZy
    xJqb/VwJYjc1w6yEYM5UNEdcpk5lot3Lhns/3mVrpQBCEtwGp9UtwyW27PuqPnJk
    Sj8R0RNB458ne+XmPJi7atZ4M1qcgDSHhT1ly1xx2wIDAQABo4GXMIGUMB0GA1Ud
    DgQWBBQnJaxVcby97xhkAMXnXtGvxB6m0DAfBgNVHSMEGDAWgBQnJaxVcby97xhk
    AMXnXtGvxB6m0DAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEG
    CCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwFQYDVR0RBA4wDIIKZGJyZXBvLmFwcDAN
    BgkqhkiG9w0BAQsFAAOCAQEARxV88dr1rpmJvth7LGEstHrgyBn8NISTkCJtY3UL
    mIi4WEyAgqAdN4ZJ7R5WREm7rz3VPGrvAwD9rxrTxMdzyy+AifX8E2zXsaGYU5s+
    FkcExZ1pCKpc5Ioa1MovaFkAXHTlv919c+HAa1B2EFYq6uVuldltbdAqKpLam+A/
    emS4RITCi19717Q+0gom/zfUKm1ajwTTpI9BzyIEthQvUTG6crtW0R2rW26pbwco
    wizrhnLFNZJp+AyB+UZqBh9Ezii2hyM/CiK7p48j1/TCA6zpjzFSXzq1gopvhJpA
    Xskj/uAu/souD8WdkAUz4eFitIj2+cTNAmvUt/YiJ5ji3Q==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/ET+yH2TJKYdX
    UJauKJx+11Y5RAfYqYwoG530aSVyPsYwF1DG0xvCpJXk0mkXRaUDuFVfYEt05OfQ
    zgc+RLxV9eRuWhbq4GyI+RelfXotV7endtNopGKl6gudFTqoXnzrDAydgFhp/Kbe
    /TFeQ7ymOjV/bevLkTXzmGGPJAbGKEhPXlsRaRCYIm+9K74wH/O5RM+O4IFJBYDx
    W9FGivwiosKzwIeOpNyuZVajLFIgpnLEmpv9XAliNzXDrIRgzlQ0R1ymTmWi3cuG
    ez/eZWulAEIS3Aan1S3DJbbs+6o+cmRKPxHRE0Hjnyd75eY8mLtq1ngzWpyANIeF
    PWXLXHHbAgMBAAECggEAC7eQE2lPcfKlBRrBEs8UwcaM2Bgu7v9+w9rltd5Y2Ie2
    +a4EWx0JH8eeFZk9rpqrwu2j9qReHD4JZUmtMglfD1pz9rx5mU/H+CJma9SlEHDH
    p3JnBozGK+yNZ8WsgjTBLlzfzSzYvy8qQJSAWYqH4B3DuBvSkPpHt7eJjBCmhbJJ
    jt1oY5pScaqVa3UN/OyMag5/Liuij0GiTU/o4nNBpd1ebvwIyLO2UZjyv1i8b4X8
    2+jhceHFQA9OzpaEbKVVeMNl5OI9+mxkryvYsbm/R4Gb1Czvss0a7Ov/cEaFsGKS
    86dGZ8ceNPbm9yrRvq3tDIF12aenmAtWgaAISdx3AQKBgQDmcuhc96dZ2Jiu5LP4
    cv/rbyTUUM85ldCVFd1BRJEIl3BS8iqNQv9Kvwa3QoZQmjwKA2MacC1VT5g3oGKX
    jG7ICFE8BKIaPYH1DSzZ8Ao+VFuK8EAh+Cm6y3jgbildYcpB0qK/ieZ0N593j03I
    jyW1xRUpeWP5WOK6Q+390PnEWwKBgQDUQIghUxpQYxyBuAQBfQLmrrV21jBRY5KV
    rZ5mEma9hUWneAyY2u8z9isRwmSqj8CRRdn5w4CscJpZ7re9HByoYi0exDA4f8T+
    0nLnxhI+Pg0HyjY9f0WtkUEqjwDNN9rQ+9UCJK5tvP/BX3RS1Uf62uj35kPCUiDp
    KC3X1mmAgQKBgFdXf9gUiRoVbLEEv21P8M1Dv7q0sgXKUVbgBY7CNRIDi6/0VspZ
    dTbYNexpS0zrWAwXgo03rQbjdvbGU/fKYwZvmJJd0y6M11+QUcp8HvXGtTdwnW4C
    h5Zjnfm55vWcpbLS6Zoc4vpzRn5jEwELuCgvfTjN6GVOGgiszFvhw3h3AoGBALq+
    kEcps8Q4f3NOMRASKkRGQNhuuRJS1jylBfFujUCACnm+8O5n6f/AvcIhU6qRUe8/
    EvpiXUraw6MOmlBjdH9d6a7hFEARgoRlKr3rkk97DsHk0vYmjWqZm0lTinQEiZxH
    hfEdzu40VJ2RW2opxuvaQREjYkiNM/GP7U2ykx6BAoGAMF5OQusl0Ytm2cemJGgU
    n1c04Gr9+HTWIXIUkrFITTZQtYou70gtfqMDtFdOM+gLCJH90w06Di/q/HUfC5+c
    mRNMi29eRosAJwnZjv9cxojduWkq1qsBHjpi9Whqv4I0IXeW+Jr5ylPfbajthwd5
    M5AReVppJDflS5ipk4s59RI=
    -----END PRIVATE KEY-----