---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: dbrepo-ingress-tls-cert
  namespace: {{ .Values.namespace }}
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQWNtZ0F3SUJBZ0lRQjJvZzZXSVBG
    NzVQUEgzS0FkTytMREFOQmdrcWhraUc5dzBCQVFzRkFEQVUKTVJJd0VBWURWUVFERXdsc2IyTmhi
    R2h2YzNRd0hoY05NalF3TkRBM01UZzFPVE0zV2hjTk1qVXdOREF5TVRnMQpPVE0zV2pBVU1SSXdF
    QVlEVlFRREV3bHNiMk5oYkdodmMzUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdn
    Z0VLQW9JQkFRRGE1MmxnTFJXYlZ6Sy8wZWFLS0xHaUxtSzl4RlVzczh6cElHZTNaWk5PcVJ5UUlQ
    NTQKTTNLYXZseGsySGMzaVBsRXdsZkcxY1pFL1ptSWlBQXFyaHQrU0txOVR6Ykk0VzlBWkFyOURD
    MkVWMEtnUVRRNgpkQ0lSRGhzalZnbDllMTg4SVV4MXRPSmMzcCtTdjVGbEZ1bUY2VG5sUnpxMkdZ
    Y2tSQmhLTGlJMG1CTGNNNjlYCnJhUWIwU2N3SXJSTktvcUdwd0duejQ0cjFEWG80eXp3Qzh1ZzBQ
    RWZUTktBeVZBeFU3UjBUeHJodHlCTUhZS2kKYnJnK2JqcVBRS3R2UDl6eXZXUXdhdlpCaFZPVlpY
    WVN3QVdpdUIwcFVGdnByZW94cWtXbHhOazlpZVRyQSs5egozSjlhbzFSZmw2eFhuQmJYdjBGZlVR
    SVhwME1VaGtObXZwZDNBZ01CQUFHakx6QXRNQjBHQTFVZEpRUVdNQlFHCkNDc0dBUVVGQndNQkJn
    Z3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFR
    QXAyTWdORHZUZFZEd3Bjam0yQ3laZ01JQ01HUTlYc2hmUzA4eEc0d1NBU1BQY0Q2OHp1MlAvTkJ4
    dQptcUl3NEptT2UxVkFrb0VmeDRRYXh4ZkwybzlQWTVGVDhRMU9jb3JVdmd3c09TVFdYdS85Q21j
    ZnA5U25FZlA2Ck5KU2k5T3UrL1VzTzRITGlMem5EdkVYdGZBQUJWdVR3d2tnOTAvMWFXZ0dFT3ZD
    cUprbHB3VjRPbFZhZ3hIZzkKTXZrd2pkTlNhRWE0Y2pEUlZhMzNPMkJPTDZkdmZZYlJET0tuUkcr
    d3BSaXBkN05VSW9hWGsrQXJzWU5JMWVOSApnWThjU3ZoL1gyWndTb3BoWGxUbXBoeFhqa3RiVUcz
    bCtxaHhIRlQ5YWIrTm5aRm1MOWZ5SWNmdEhiQjdKQnpLCnVzdlhKdWdyVUppWWxPQURKRTRZRjdE
    TGZtT2wKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQWNtZ0F3SUJBZ0lRQjJvZzZXSVBG
    NzVQUEgzS0FkTytMREFOQmdrcWhraUc5dzBCQVFzRkFEQVUKTVJJd0VBWURWUVFERXdsc2IyTmhi
    R2h2YzNRd0hoY05NalF3TkRBM01UZzFPVE0zV2hjTk1qVXdOREF5TVRnMQpPVE0zV2pBVU1SSXdF
    QVlEVlFRREV3bHNiMk5oYkdodmMzUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdn
    Z0VLQW9JQkFRRGE1MmxnTFJXYlZ6Sy8wZWFLS0xHaUxtSzl4RlVzczh6cElHZTNaWk5PcVJ5UUlQ
    NTQKTTNLYXZseGsySGMzaVBsRXdsZkcxY1pFL1ptSWlBQXFyaHQrU0txOVR6Ykk0VzlBWkFyOURD
    MkVWMEtnUVRRNgpkQ0lSRGhzalZnbDllMTg4SVV4MXRPSmMzcCtTdjVGbEZ1bUY2VG5sUnpxMkdZ
    Y2tSQmhLTGlJMG1CTGNNNjlYCnJhUWIwU2N3SXJSTktvcUdwd0duejQ0cjFEWG80eXp3Qzh1ZzBQ
    RWZUTktBeVZBeFU3UjBUeHJodHlCTUhZS2kKYnJnK2JqcVBRS3R2UDl6eXZXUXdhdlpCaFZPVlpY
    WVN3QVdpdUIwcFVGdnByZW94cWtXbHhOazlpZVRyQSs5egozSjlhbzFSZmw2eFhuQmJYdjBGZlVR
    SVhwME1VaGtObXZwZDNBZ01CQUFHakx6QXRNQjBHQTFVZEpRUVdNQlFHCkNDc0dBUVVGQndNQkJn
    Z3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFR
    QXAyTWdORHZUZFZEd3Bjam0yQ3laZ01JQ01HUTlYc2hmUzA4eEc0d1NBU1BQY0Q2OHp1MlAvTkJ4
    dQptcUl3NEptT2UxVkFrb0VmeDRRYXh4ZkwybzlQWTVGVDhRMU9jb3JVdmd3c09TVFdYdS85Q21j
    ZnA5U25FZlA2Ck5KU2k5T3UrL1VzTzRITGlMem5EdkVYdGZBQUJWdVR3d2tnOTAvMWFXZ0dFT3ZD
    cUprbHB3VjRPbFZhZ3hIZzkKTXZrd2pkTlNhRWE0Y2pEUlZhMzNPMkJPTDZkdmZZYlJET0tuUkcr
    d3BSaXBkN05VSW9hWGsrQXJzWU5JMWVOSApnWThjU3ZoL1gyWndTb3BoWGxUbXBoeFhqa3RiVUcz
    bCtxaHhIRlQ5YWIrTm5aRm1MOWZ5SWNmdEhiQjdKQnpLCnVzdlhKdWdyVUppWWxPQURKRTRZRjdE
    TGZtT2wKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktjd2dnU2pBZ0VBQW9JQkFRRGE1MmxnTFJXYlZ6Sy8KMGVhS0tMR2lMbUs5eEZVc3M4enBJ
    R2UzWlpOT3FSeVFJUDU0TTNLYXZseGsySGMzaVBsRXdsZkcxY1pFL1ptSQppQUFxcmh0K1NLcTlU
    emJJNFc5QVpBcjlEQzJFVjBLZ1FUUTZkQ0lSRGhzalZnbDllMTg4SVV4MXRPSmMzcCtTCnY1RmxG
    dW1GNlRubFJ6cTJHWWNrUkJoS0xpSTBtQkxjTTY5WHJhUWIwU2N3SXJSTktvcUdwd0duejQ0cjFE
    WG8KNHl6d0M4dWcwUEVmVE5LQXlWQXhVN1IwVHhyaHR5Qk1IWUtpYnJnK2JqcVBRS3R2UDl6eXZX
    UXdhdlpCaFZPVgpaWFlTd0FXaXVCMHBVRnZwcmVveHFrV2x4Tms5aWVUckErOXozSjlhbzFSZmw2
    eFhuQmJYdjBGZlVRSVhwME1VCmhrTm12cGQzQWdNQkFBRUNnZ0VCQUxzR2hmQ0c5SFB4RDBuMkV3
    c3RjMzhHTkpTL3ZxbmZ3STNaZ3VPZEpEdEwKbnp6QkE4azg0NGkwWllvL3E3UEdFbnFkdEpNTUtF
    YmZpU0t1Vjc0ZlhSd0xCOTJRWlZWQnptUnNWVHNZQVhlVgplallqSDNWbHJZbDJ6TmJtOWxyQVlv
    Q2tUb2d1a0V3YVpLbmpoRnlqTThlV21VRjhGdnhvV1I4eUVyS21NZEZPCkczS281VVE5dml2QVQy
    RGRTcitVc1JqRG9RMDFIY3hlTEw3Rk1XVFFVQ3FndkpVUmZjSlczOTROTHp3RkVjZXIKR25vd3Vh
    bXpvempaZ013cCsyZzIzanBUSG5pMW05amt5SHdFU1ZMc2N6YzVJSUtrZkl0Si9vS0NlZGxMMDg3
    dgpybG1xNkZsU2I4Y1lLYWlaOGVyM0dVYzJiM1plWXNsT0JYQlowcTZUTmdFQ2dZRUErditvUCtF
    V2FGNkFBTHdwCkdEMlpJbXpKT0VzTnJpdzIxMmIwK0RPdWY1Y1Q5QnFGTFVQNDJmTGlzVHJQTDFX
    MTd4TUcxTmxKWjRGSzZ4b3YKV25nWWNZMjBPaTdwQ2N4cDJLVDBnNFo4YTBDVjRFQUVVVnJPcm1Z
    NFMyK0dsZ3h4ckJWV1h5TTl2NXZQaTdWNwpRa055VFJXYUtTR2pIT2d1NjlzRVNwbnNLUUVDZ1lF
    QTMwUUtHbDVabDM0ampzRFdJTXFIWGpXd0w3QmpPSW1pClp3VlcxZUZuVDA2cWlPaTNjcGxPdXY1
    UWVPemN5RzBOZ1FhaXVYWHQ3amJ0bWFLTDNJNk45Q2Z4Y2dzSkFvK08KM0xDREVKSSt5dXorTXJV
    cG05RHVMUUNDQnkzYTVoSUREV1lxYk10RDlzSXBHVGNPOU9QQlBBaTZqemJqK3piNQpQcTlkRDkw
    dmlIY0NnWUFheVVIWlgxb1cxVTd2eFNUVmsyMU9RVEhRTWlKSm5pcFVIb2F5SGtIWEYvWm5MSlZk
    CjJVMHJaVUpRQzZpa3NvN3g3cVBoL3paWU4zSVpXUGdJdlp4T01nTXoybUhBUy9KWHpuTFJ2bjUw
    cTdYUzhzSUQKTkordCtQYTFCamZrdDN0Q0ZCemRsbE0ycVpnaW5zR0N0dFB4NmdaRHNYVkkxblo3
    Y1NvcUUvY2lBUUtCZ0YzOApBbFMvU3UrZXhkRWVGQVdSdkJKSWYzWlR4akRTbjI3R3JKczBXNHpq
    REo2OWVCdmh0V2E2RDU0WDk0alhmMHZGClExTFc5ZVhGY1pldStUbExPUzZDY2YwVDhDTUgwNWZM
    SmlFZnJ4YzFWSHg4RHB2dEE1WW1GSlo1RXlDdWpHSmoKazVCZ3NLZDdiRm1VOTlMVzNVMHNUM3hp
    R3U1eFlkS2xkNE5xRk14WkFvR0FmSHc0eTdPRGpFTG53Sk40eWpxTQpHOEEzdVYreSs4TjI3UjF3
    aDVNOHk3VDFVQVhNMlo5YTV1UitVdG5GSS84dDBTUVhNQ1BBRGdraWhTdS8wcExUCmJpY2dnMm1p
    bldJMlNScGZSWHlvK21ia1N3clR6ak53MUs0NnFsTmh3SmJsRy9uU29SanBhVVErbUxWLzVFNWgK
    WGNNZjZHUFZlNk9PUEVpdVpONnprSmM9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K