app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: "jdbc:mariadb://metadata-db:3306/${METADATA_DB}"
    driver-class-name: org.mariadb.jdbc.Driver
    username: "${METADATA_USERNAME}"
    password: "${METADATA_PASSWORD}"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      search:
        default:
          elasticsearch:
            host: search-db
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: "${METADATA_DB}"
        jdbc:
          time_zone: UTC
  application:
    name: table-service
  rabbitmq:
    host: broker-service
    virtual-host: dbrepo
    username: "${BROKER_USERNAME}"
    password: "${BROKER_PASSWORD}"
  opensearch:
    username: "${SEARCH_USERNAME}"
    password: "${SEARCH_PASSWORD}"
    host: search-db
    port: 9200
    protocol: http
  cloud:
    loadbalancer.ribbon.enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
server:
  port: 9094
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: "${LOG_LEVEL}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
fda:
  jwt:
    issuer: "${JWT_ISSUER}"
    public_key: "${JWT_PUBKEY}"
  client_secret: "${DBREPO_CLIENT_SECRET}"
  client_id: "${CLIENT_ID}"
  gateway.endpoint: http://gateway-service