app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: "jdbc:mariadb://metadata-db:3306/${METADATA_DB}"
    driver-class-name: org.mariadb.jdbc.Driver
    username: "${METADATA_USERNAME}"
    password: "${METADATA_PASSWORD}"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: "${METADATA_DB}"
        jdbc:
          time_zone: UTC
  application:
    name: metadata-service
  rabbitmq:
    host: broker-service
    username: "${BROKER_USERNAME}"
    password: "${BROKER_PASSWORD}"
  cloud:
    loadbalancer.ribbon.enabled: false
management.endpoints.web.exposure.include: health,info,prometheus
server:
  port: 9099
  ssl:
    enabled: true
    key-alias: "${KEY_ALIAS}"
    key-store: "${KEY_STORE}"
    key-store-type: jks
    key-store-password: "${KEY_STORE_PASS}"
    key-password: "${KEY_PASS}"
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: "${LOG_LEVEL}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  instance:
    hostname: metadata-service
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 9099
  client.serviceUrl.defaultZone: http://discovery-service:9090/eureka/
fda:
  ready.path: ./ready
  pid.base: "${PID_BASE}"
  gateway.endpoint: "${GATEWAY_ENDPOINT}"
dbrepo:
  repository-name: "${REPOSITORY_NAME}"
  base-url: "${BASE_URL}"
  admin-email: "${ADMIN_MAIL}"
  earliest-datestamp: "${EARLIEST_DATESTAMP}"
  deleted-record: "${DELETED_RECORD}"
  granularity: "${GRANULARITY}"
