app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: "jdbc:postgresql://metadata-db:5432/${METADATA_DB}"
    driver-class-name: org.postgresql.Driver
    username: "${METADATA_USERNAME}"
    password: "${METADATA_PASSWORD}"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  application:
    name: table-service
  rabbitmq:
    host: broker-service
    username: "${BROKER_USERNAME}"
    password: "${BROKER_PASSWORD}"
  cloud:
    loadbalancer.ribbon.enabled: false
server.port: 9094
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
    at.tuwien.mapper.: trace
    at.tuwien.service.: debug
    at.tuwien.config.: debug
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  instance.hostname: table-service
  client.serviceUrl.defaultZone: http://discovery-service:9090/eureka/
fda:
  ready.path: ./ready
  gateway.endpoint: "${GATEWAY_ENDPOINT}"
dbrepo:
  repository-name: "${REPOSITORY_NAME}"
  base-url: "${BASE_URL}"
  admin-email: "${ADMIN_MAIL}"
  earliest-datestamp: "${EARLIEST_DATESTAMP}"
  deleted-record: "${DELETED_RECORD}"
  granularity: "${GRANULARITY}"
