{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-setup
  namespace: {{ .Values.namespace }}
data:
  dbrepo.config.json: |
    {{ .Values.ui.config | nindent 4 }}
{{- end }}