{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-setup
  namespace: {{ $.Values.namespace }}
data:
  dbrepo.config.json: |
    {
      "title": "Database Repository",
      "version": "1.4.1",
      "ssl": {
        "force": false
      },
      "logo": {
        "path": "/logo.svg"
      },
      "icon": {
        "path": "/favicon.ico"
      },
      "appleTouchIcon": {
        "path": "/apple-touch-icon.png"
      },
      "api": {
        "useSsl": false
      },
      "broker": {
        "connection": {
          "host": "localhost",
          "ports": [
            5672
          ],
          "extraInfo": null
        }
      },
      "storage": {
        "endpoint": "storage-service",
        "port": 9000,
        "useSsl": false,
        "accessKey": {
          "id": "seaweedfsadmin",
          "secret": "seaweedfsadmin"
        }
      },
      "upload": {
        "endpoint": "localhost",
        "port": 1080,
        "useSsl": false
      },
      "database": {
        "connection": {
          "extraInfo": null
        }
      },
      "keycloak": {
        "client": {
          "id": "dbrepo-client",
          "secret": "MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG"
        }
      },
      "opensearch": {
        "username": "admin",
        "password": "admin"
      },
      "pid": {
        "default": {
          "publisher": "Example University"
        }
      },
      "doi": {
        "url": "https://doi.org"
      },
      "pages": {
        "login": {
          "links": []
        },
        "information": {
          "links": [
            {
              "text": "Online Documentation",
              "blank": true,
              "href": "https://www.ifs.tuwien.ac.at/infrastructures/dbrepo/"
            },
            {
              "text": "Sourcecode Documentation",
              "blank": true,
              "href": "https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services"
            },
            {
              "text": "Docker Images",
              "blank": true,
              "href": "https://hub.docker.com/u/dbrepo"
            },
            {
              "text": "Demo Instance (Kubernetes)",
              "blank": true,
              "href": "https://test.dbrepo.tuwien.ac.at/"
            },
            {
              "text": "Pilot Instance (Docker Compose)",
              "blank": true,
              "href": "https://dbrepo1.ec.tuwien.ac.at/"
            },
            {
              "text": "Paper",
              "blank": true,
              "href": "https://doi.org/10.2218/ijdc.v17i1.825"
            }
          ]
        }
      }
    }
{{- end }}