{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-setup
  namespace: {{ $.Values.namespace }}
data:
  dbrepo.config.json: |
    {
      "title": "{{ .Values.ui.title }}",
      "version": "{{ .Values.ui.version }}",
      "ssl": {
        "force": "{{ .Values.ui.forceSsl }}"
      },
      "logo": {
        "path": "{{ .Values.ui.logo }}"
      },
      "icon": {
        "path": "{{ .Values.ui.icon }}"
      },
      "appleTouchIcon": {
        "path": "{{ .Values.ui.appleTouchIcon }}"
      },
      "api": {
        "useSsl": "{{ .Values.ui.forceSsl }}"
      },
      "broker": {
        "connection": {
          "host": "{{ .Values.ui.broker.host }}",
          "ports": {{ .Values.ui.broker.ports | toJson }},
          "extraInfo": "{{ .Values.ui.broker.extraInfo}}"
        }
      },
      "storage": {
        "endpoint": "storage-service",
        "port": 9000,
        "useSsl": false,
        "accessKey": {
          "id": "seaweedfsadmin",
          "secret": "seaweedfsadmin"
        }
      },
      "database": {
        "connection": {
          "extraInfo": "128.130.0.0/15"
        }
      },
      "keycloak": {
        "client": {
          "id": "dbrepo-client",
          "secret": "MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG"
        }
      },
      "opensearch": {
        "username": "admin",
        "password": "admin"
      },
      "pid": {
        "default": {
          "publisher": "TU Wien"
        }
      },
      "doi": {
        "url": "{{ .Values.ui.datacite.url }}"
      },
      "pages": {
        "login": {
          "links": [
            {
              "text": "OpenSearch Admin",
              "blank": true,
              "href": "{{ printf "https://%s/admin/dashboard" .Values.hostname }}"
            },
            {
              "text": "RabbitMQ Admin",
              "blank": true,
              "href": "{{ printf "https://%s/admin/broker/" .Values.hostname }}"
            },
            {
              "text": "Keycloak Admin",
              "blank": true,
              "href": "{{ printf "https://%s/api/auth/" .Values.hostname }}"
            }
          ]
        },
        "information": {
          "links": [
            {
              "text": "Online Documentation",
              "blank": true,
              "href": "https://www.ifs.tuwien.ac.at/infrastructures/dbrepo/latest/"
            },
            {
              "text": "Sourcecode Documentation",
              "blank": true,
              "href": "https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services"
            },
            {
              "text": "Docker Images",
              "blank": true,
              "href": "https://hub.docker.com/u/dbrepo"
            },
            {
              "text": "Demo Instance (Kubernetes)",
              "blank": true,
              "href": "https://test.dbrepo.tuwien.ac.at/"
            },
            {
              "text": "Demo Instance (Docker Compose)",
              "blank": true,
              "href": "https://dbrepo2.ec.tuwien.ac.at/"
            },
            {
              "text": "Paper",
              "blank": true,
              "href": "https://doi.org/10.2218/ijdc.v17i1.825"
            }
          ]
        }
      }
    }
{{- end }}