---
apiVersion: v1
kind: Secret
metadata:
  name: ui-secret
  namespace: {{ .Values.namespace }}
stringData:
  public-api-client: "{{ .Values.ui.public.api.client }}"
  public-api-server: "{{ .Values.ui.public.api.server }}"
  public-title: "{{ .Values.ui.public.title }}"
  public-logo: "{{ .Values.ui.public.logo }}"
  public-icon: "{{ .Values.ui.public.icon }}"
  public-touch: "{{ .Values.ui.public.touch }}"
  public-broker-host: "{{ .Values.ui.public.broker.host }}"
  public-broker-port: {{ .Values.ui.public.broker.port | toJson | quote }}
  public-broker-extra: "{{ .Values.ui.public.broker.extra }}"
  public-database-extra: "{{ .Values.ui.public.database.extra }}"
  public-pid-default-publisher: "{{ .Values.ui.public.pid.default.publisher }}"
  public-doi-enabled: "{{ .Values.ui.public.doi.enabled }}"
  public-doi-endpoint: "{{ .Values.ui.public.doi.endpoint }}"