openapi: 3.0.1
info:
  title: Database Repository Data Service API
  description: Service that manages the data
  contact:
    name: Prof. Andreas Rauber
    email: andreas.rauber@tuwien.ac.at
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.4.0
externalDocs:
  description: Sourcecode Documentation
  url: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
servers:
- url: http://localhost:9093
  description: Generated server url
- url: https://test.dbrepo.tuwien.ac.at
  description: Sandbox
paths: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
