components:
  schemas: {}
externalDocs:
  description: Sourcecode Documentation
  url: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
info:
  contact:
    email: andreas.rauber@tuwien.ac.at
    name: Prof. Andreas Rauber
  description: Service that analyses data structures
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: Database Repository Analyse Service API
  version: 1.4.0
openapi: 3.0.0
paths:
  /api/analyse/determinedt:
    post:
      consumes:
        - application/json
      description: This is a simple API which returns the datatypes of a (path) csv
        file
      parameters:
        - description: to-do description
          in: body
          name: body
          required: true
          schema:
            properties:
              enum:
                example: true
                type: boolean
              enum_tol:
                example: 0.1
              filename:
                example: sample.csv
                type: string
              separator:
                example: ','
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
      summary: Determine datatypes
  /api/analyse/determinepk:
    post:
      consumes:
        - application/json
      description: This is a simple API which returns the primary keys + ranking of
        a (path) csv file
      parameters:
        - description: to-do description
          in: body
          name: body
          required: true
          schema:
            properties:
              filepath:
                example: /data/testdt08.csv
                type: string
              seperator:
                example: ','
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
      summary: Determine primary keys
  /health:
    get:
      consumes:
        - application/json
      description: This is a simple API which checks if the application is healthy
      parameters:
        - description: to-do description
          in: body
          name: body
          required: true
          schema:
            properties:
              status:
                example: UP
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
      summary: Check if application is running
servers:
  - description: Generated server url
    url: http://localhost:5000
  - description: Sandbox
    url: https://dbrepo2.tuwien.ac.at
