app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: jdbc:mariadb://localhost:3306/fda
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dbrepo
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      search:
        default:
          elasticsearch:
            host: localhost
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: fda
        jdbc:
          time_zone: UTC
  application:
    name: search-startup-agent
  opensearch:
    username: admin
    password: admin
    host: localhost
    port: 9200
    protocol: http
  cloud:
    loadbalancer.ribbon.enabled: false
management.endpoints.web.exposure.include: health,info,prometheus
server:
  port: 9050
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: trace
    org.opensearch.client.: trace
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
