# coding: utf-8

"""
    Database Repository Query Service API

    Service that manages the queries  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from api_query.api_client import ApiClient


class TableDataEndpointApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete(self, body, id, database_id, table_id, **kwargs):  # noqa: E501
        """Delete data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete(body, id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TableCsvDeleteDto body: (required)
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_with_http_info(body, id, database_id, table_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_with_http_info(body, id, database_id, table_id, **kwargs)  # noqa: E501
            return data

    def delete_with_http_info(self, body, id, database_id, table_id, **kwargs):  # noqa: E501
        """Delete data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_with_http_info(body, id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TableCsvDeleteDto body: (required)
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id', 'database_id', 'table_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `delete`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `delete`")  # noqa: E501
        # verify the required parameter 'database_id' is set
        if ('database_id' not in params or
                params['database_id'] is None):
            raise ValueError("Missing the required parameter `database_id` when calling `delete`")  # noqa: E501
        # verify the required parameter 'table_id' is set
        if ('table_id' not in params or
                params['table_id'] is None):
            raise ValueError("Missing the required parameter `table_id` when calling `delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'database_id' in params:
            path_params['databaseId'] = params['database_id']  # noqa: E501
        if 'table_id' in params:
            path_params['tableId'] = params['table_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/container/{id}/database/{databaseId}/table/{tableId}/data', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all2(self, id, database_id, table_id, **kwargs):  # noqa: E501
        """Find data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all2(id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :param datetime timestamp:
        :param int page:
        :param int size:
        :return: QueryResultDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all2_with_http_info(id, database_id, table_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_all2_with_http_info(id, database_id, table_id, **kwargs)  # noqa: E501
            return data

    def get_all2_with_http_info(self, id, database_id, table_id, **kwargs):  # noqa: E501
        """Find data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all2_with_http_info(id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :param datetime timestamp:
        :param int page:
        :param int size:
        :return: QueryResultDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'database_id', 'table_id', 'timestamp', 'page', 'size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all2" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `get_all2`")  # noqa: E501
        # verify the required parameter 'database_id' is set
        if ('database_id' not in params or
                params['database_id'] is None):
            raise ValueError("Missing the required parameter `database_id` when calling `get_all2`")  # noqa: E501
        # verify the required parameter 'table_id' is set
        if ('table_id' not in params or
                params['table_id'] is None):
            raise ValueError("Missing the required parameter `table_id` when calling `get_all2`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'database_id' in params:
            path_params['databaseId'] = params['database_id']  # noqa: E501
        if 'table_id' in params:
            path_params['tableId'] = params['table_id']  # noqa: E501

        query_params = []
        if 'timestamp' in params:
            query_params.append(('timestamp', params['timestamp']))  # noqa: E501
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'size' in params:
            query_params.append(('size', params['size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/container/{id}/database/{databaseId}/table/{tableId}/data', 'HEAD',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='QueryResultDto',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all3(self, id, database_id, table_id, **kwargs):  # noqa: E501
        """Find data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all3(id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :param datetime timestamp:
        :param int page:
        :param int size:
        :return: QueryResultDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all3_with_http_info(id, database_id, table_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_all3_with_http_info(id, database_id, table_id, **kwargs)  # noqa: E501
            return data

    def get_all3_with_http_info(self, id, database_id, table_id, **kwargs):  # noqa: E501
        """Find data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all3_with_http_info(id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :param datetime timestamp:
        :param int page:
        :param int size:
        :return: QueryResultDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'database_id', 'table_id', 'timestamp', 'page', 'size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all3" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `get_all3`")  # noqa: E501
        # verify the required parameter 'database_id' is set
        if ('database_id' not in params or
                params['database_id'] is None):
            raise ValueError("Missing the required parameter `database_id` when calling `get_all3`")  # noqa: E501
        # verify the required parameter 'table_id' is set
        if ('table_id' not in params or
                params['table_id'] is None):
            raise ValueError("Missing the required parameter `table_id` when calling `get_all3`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'database_id' in params:
            path_params['databaseId'] = params['database_id']  # noqa: E501
        if 'table_id' in params:
            path_params['tableId'] = params['table_id']  # noqa: E501

        query_params = []
        if 'timestamp' in params:
            query_params.append(('timestamp', params['timestamp']))  # noqa: E501
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'size' in params:
            query_params.append(('size', params['size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/container/{id}/database/{databaseId}/table/{tableId}/data', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='QueryResultDto',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def import_csv(self, body, id, database_id, table_id, **kwargs):  # noqa: E501
        """Insert data from csv  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.import_csv(body, id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ImportDto body: (required)
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.import_csv_with_http_info(body, id, database_id, table_id, **kwargs)  # noqa: E501
        else:
            (data) = self.import_csv_with_http_info(body, id, database_id, table_id, **kwargs)  # noqa: E501
            return data

    def import_csv_with_http_info(self, body, id, database_id, table_id, **kwargs):  # noqa: E501
        """Insert data from csv  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.import_csv_with_http_info(body, id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ImportDto body: (required)
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id', 'database_id', 'table_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method import_csv" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `import_csv`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `import_csv`")  # noqa: E501
        # verify the required parameter 'database_id' is set
        if ('database_id' not in params or
                params['database_id'] is None):
            raise ValueError("Missing the required parameter `database_id` when calling `import_csv`")  # noqa: E501
        # verify the required parameter 'table_id' is set
        if ('table_id' not in params or
                params['table_id'] is None):
            raise ValueError("Missing the required parameter `table_id` when calling `import_csv`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'database_id' in params:
            path_params['databaseId'] = params['database_id']  # noqa: E501
        if 'table_id' in params:
            path_params['tableId'] = params['table_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/container/{id}/database/{databaseId}/table/{tableId}/data/import', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def insert(self, body, id, database_id, table_id, **kwargs):  # noqa: E501
        """Insert data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.insert(body, id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TableCsvDto body: (required)
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.insert_with_http_info(body, id, database_id, table_id, **kwargs)  # noqa: E501
        else:
            (data) = self.insert_with_http_info(body, id, database_id, table_id, **kwargs)  # noqa: E501
            return data

    def insert_with_http_info(self, body, id, database_id, table_id, **kwargs):  # noqa: E501
        """Insert data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.insert_with_http_info(body, id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TableCsvDto body: (required)
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id', 'database_id', 'table_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method insert" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `insert`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `insert`")  # noqa: E501
        # verify the required parameter 'database_id' is set
        if ('database_id' not in params or
                params['database_id'] is None):
            raise ValueError("Missing the required parameter `database_id` when calling `insert`")  # noqa: E501
        # verify the required parameter 'table_id' is set
        if ('table_id' not in params or
                params['table_id'] is None):
            raise ValueError("Missing the required parameter `table_id` when calling `insert`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'database_id' in params:
            path_params['databaseId'] = params['database_id']  # noqa: E501
        if 'table_id' in params:
            path_params['tableId'] = params['table_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/container/{id}/database/{databaseId}/table/{tableId}/data', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update(self, body, id, database_id, table_id, **kwargs):  # noqa: E501
        """Update data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update(body, id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TableCsvUpdateDto body: (required)
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_with_http_info(body, id, database_id, table_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_with_http_info(body, id, database_id, table_id, **kwargs)  # noqa: E501
            return data

    def update_with_http_info(self, body, id, database_id, table_id, **kwargs):  # noqa: E501
        """Update data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_with_http_info(body, id, database_id, table_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TableCsvUpdateDto body: (required)
        :param int id: (required)
        :param int database_id: (required)
        :param int table_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id', 'database_id', 'table_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `update`")  # noqa: E501
        # verify the required parameter 'database_id' is set
        if ('database_id' not in params or
                params['database_id'] is None):
            raise ValueError("Missing the required parameter `database_id` when calling `update`")  # noqa: E501
        # verify the required parameter 'table_id' is set
        if ('table_id' not in params or
                params['table_id'] is None):
            raise ValueError("Missing the required parameter `table_id` when calling `update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'database_id' in params:
            path_params['databaseId'] = params['database_id']  # noqa: E501
        if 'table_id' in params:
            path_params['tableId'] = params['table_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/container/{id}/database/{databaseId}/table/{tableId}/data', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
