# coding: utf-8

"""
    Database Repository Container Service API

    Service that manages the containers  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ImageCreateDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'repository': 'str',
        'tag': 'str',
        'dialect': 'str',
        'logo': 'str',
        'local': 'bool',
        'environment': 'list[ImageEnvItemDto]',
        'driver_class': 'str',
        'jdbc_method': 'str',
        'default_port': 'int'
    }

    attribute_map = {
        'repository': 'repository',
        'tag': 'tag',
        'dialect': 'dialect',
        'logo': 'logo',
        'local': 'local',
        'environment': 'environment',
        'driver_class': 'driver_class',
        'jdbc_method': 'jdbc_method',
        'default_port': 'default_port'
    }

    def __init__(self, repository=None, tag=None, dialect=None, logo=None, local=None, environment=None, driver_class=None, jdbc_method=None, default_port=None):  # noqa: E501
        """ImageCreateDto - a model defined in Swagger"""  # noqa: E501
        self._repository = None
        self._tag = None
        self._dialect = None
        self._logo = None
        self._local = None
        self._environment = None
        self._driver_class = None
        self._jdbc_method = None
        self._default_port = None
        self.discriminator = None
        self.repository = repository
        self.tag = tag
        self.dialect = dialect
        self.logo = logo
        self.local = local
        if environment is not None:
            self.environment = environment
        self.driver_class = driver_class
        self.jdbc_method = jdbc_method
        self.default_port = default_port

    @property
    def repository(self):
        """Gets the repository of this ImageCreateDto.  # noqa: E501


        :return: The repository of this ImageCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._repository

    @repository.setter
    def repository(self, repository):
        """Sets the repository of this ImageCreateDto.


        :param repository: The repository of this ImageCreateDto.  # noqa: E501
        :type: str
        """
        if repository is None:
            raise ValueError("Invalid value for `repository`, must not be `None`")  # noqa: E501

        self._repository = repository

    @property
    def tag(self):
        """Gets the tag of this ImageCreateDto.  # noqa: E501


        :return: The tag of this ImageCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ImageCreateDto.


        :param tag: The tag of this ImageCreateDto.  # noqa: E501
        :type: str
        """
        if tag is None:
            raise ValueError("Invalid value for `tag`, must not be `None`")  # noqa: E501

        self._tag = tag

    @property
    def dialect(self):
        """Gets the dialect of this ImageCreateDto.  # noqa: E501


        :return: The dialect of this ImageCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._dialect

    @dialect.setter
    def dialect(self, dialect):
        """Sets the dialect of this ImageCreateDto.


        :param dialect: The dialect of this ImageCreateDto.  # noqa: E501
        :type: str
        """
        if dialect is None:
            raise ValueError("Invalid value for `dialect`, must not be `None`")  # noqa: E501

        self._dialect = dialect

    @property
    def logo(self):
        """Gets the logo of this ImageCreateDto.  # noqa: E501


        :return: The logo of this ImageCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._logo

    @logo.setter
    def logo(self, logo):
        """Sets the logo of this ImageCreateDto.


        :param logo: The logo of this ImageCreateDto.  # noqa: E501
        :type: str
        """
        if logo is None:
            raise ValueError("Invalid value for `logo`, must not be `None`")  # noqa: E501

        self._logo = logo

    @property
    def local(self):
        """Gets the local of this ImageCreateDto.  # noqa: E501


        :return: The local of this ImageCreateDto.  # noqa: E501
        :rtype: bool
        """
        return self._local

    @local.setter
    def local(self, local):
        """Sets the local of this ImageCreateDto.


        :param local: The local of this ImageCreateDto.  # noqa: E501
        :type: bool
        """
        if local is None:
            raise ValueError("Invalid value for `local`, must not be `None`")  # noqa: E501

        self._local = local

    @property
    def environment(self):
        """Gets the environment of this ImageCreateDto.  # noqa: E501


        :return: The environment of this ImageCreateDto.  # noqa: E501
        :rtype: list[ImageEnvItemDto]
        """
        return self._environment

    @environment.setter
    def environment(self, environment):
        """Sets the environment of this ImageCreateDto.


        :param environment: The environment of this ImageCreateDto.  # noqa: E501
        :type: list[ImageEnvItemDto]
        """

        self._environment = environment

    @property
    def driver_class(self):
        """Gets the driver_class of this ImageCreateDto.  # noqa: E501


        :return: The driver_class of this ImageCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._driver_class

    @driver_class.setter
    def driver_class(self, driver_class):
        """Sets the driver_class of this ImageCreateDto.


        :param driver_class: The driver_class of this ImageCreateDto.  # noqa: E501
        :type: str
        """
        if driver_class is None:
            raise ValueError("Invalid value for `driver_class`, must not be `None`")  # noqa: E501

        self._driver_class = driver_class

    @property
    def jdbc_method(self):
        """Gets the jdbc_method of this ImageCreateDto.  # noqa: E501


        :return: The jdbc_method of this ImageCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._jdbc_method

    @jdbc_method.setter
    def jdbc_method(self, jdbc_method):
        """Sets the jdbc_method of this ImageCreateDto.


        :param jdbc_method: The jdbc_method of this ImageCreateDto.  # noqa: E501
        :type: str
        """
        if jdbc_method is None:
            raise ValueError("Invalid value for `jdbc_method`, must not be `None`")  # noqa: E501

        self._jdbc_method = jdbc_method

    @property
    def default_port(self):
        """Gets the default_port of this ImageCreateDto.  # noqa: E501


        :return: The default_port of this ImageCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._default_port

    @default_port.setter
    def default_port(self, default_port):
        """Sets the default_port of this ImageCreateDto.


        :param default_port: The default_port of this ImageCreateDto.  # noqa: E501
        :type: int
        """
        if default_port is None:
            raise ValueError("Invalid value for `default_port`, must not be `None`")  # noqa: E501

        self._default_port = default_port

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImageCreateDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImageCreateDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
