application:
  title: DBRepo
  version: '@project.version@'
spring:
  datasource:
    url: "jdbc:mariadb://${METADATA_HOST:metadata-db}:3306/${METADATA_DB:dbrepo}${METADATA_JDBC_EXTRA_ARGS}"
    driver-class-name: org.mariadb.jdbc.Driver
    username: "${METADATA_USERNAME:root}"
    password: "${METADATA_PASSWORD:dbrepo}"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: "${METADATA_DB:dbrepo}"
        jdbc:
          time_zone: UTC
  application:
    name: metadata-service
  rabbitmq:
    host: "${BROKER_HOST:broker-service}"
    virtual-host: "${BROKER_VIRTUALHOST:dbrepo}"
    username: "${BROKER_USERNAME:admin}"
    password: "${BROKER_PASSWORD:admin}"
    port: ${BROKER_PORT:5672}
  main:
    banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
server:
  port: 8080
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: "${LOG_LEVEL:info}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
dbrepo:
  repository-name: "${REPOSITORY_NAME:Database Repository}"
  base-url: "${BASE_URL:http://localhost}"
  admin-email: "${ADMIN_EMAIL:noreply@example.com}"
  deleted-record: "${DELETED_RECORD:persistent}"
  granularity: "${GRANULARITY:YYYY-MM-DDThh:mm:ssZ}"
  exchangeName: "${BROKER_EXCHANGE_NAME:dbrepo}"
  queueName: "${BROKER_QUEUE_NAME:dbrepo}"
  connectionTimeout: "${SPARQL_CONNECTION_TIMEOUT:10000}"
  s3:
    accessKeyId: "${S3_ACCESS_KEY_ID:seaweedfsadmin}"
    secretAccessKey: "${S3_SECRET_ACCESS_KEY:seaweedfsadmin}"
    bucket: "${S3_BUCKET:dbrepo}"
  system:
    username: "${SYSTEM_USERNAME:admin}"
    password: "${SYSTEM_PASSWORD:admin}"
  endpoints:
    searchService: "${SEARCH_SERVICE_ENDPOINT:http://gateway-service}"
    analyseService: "${ANALYSE_SERVICE_ENDPOINT:http://gateway-service}"
    dataService: "${DATA_SERVICE_ENDPOINT:http://data-service:8080}"
    brokerService: "${BROKER_SERVICE_ENDPOINT:http://gateway-service/admin/broker}"
    authService: "${AUTH_SERVICE_ENDPOINT:http://gateway-service/api/auth}"
    storageService: "${S3_ENDPOINT:http://gateway-service/api/storage}"
    rorService: "${ROR_ENDPOINT:https://api.ror.org}"
    crossRefService: "${CROSSREF_ENDPOINT:http://data.crossref.org}"
  pid:
    base: "${PID_BASE:http://localhost/pid/}"
  jwt:
    public_key: "${JWT_PUBKEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqqnHQ2BWWW9vDNLRCcxD++xZg/16oqMo/c1l+lcFEjjAIJjJp/HqrPYU/U9GvquGE6PbVFtTzW1KcKawOW+FJNOA3CGo8Q1TFEfz43B8rZpKsFbJKvQGVv1Z4HaKPvLUm7iMm8Hv91cLduuoWx6Q3DPe2vg13GKKEZe7UFghF+0T9u8EKzA/XqQ0OiICmsmYPbwvf9N3bCKsB/Y10EYmZRb8IhCoV9mmO5TxgWgiuNeCTtNCv2ePYqL/U0WvyGFW0reasIK8eg3KrAUj8DpyOgPOVBn3lBGf+3KFSYi+0bwZbJZWqbC/Xlk20Go1YfeJPRIt7ImxD27R/lNjgDO/MwIDAQAB}"
  keycloak:
    username: "${AUTH_SERVICE_ADMIN:admin}"
    password: "${AUTH_SERVICE_ADMIN_PASSWORD:admin}"
    client: "${AUTH_SERVICE_CLIENT:dbrepo-client}"
    clientSecret: "${AUTH_SERVICE_CLIENT_SECRET:MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG}"
  website: "${BASE_URL:http://localhost}"
