app.version: '@project.version@'
spring:
  main.banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration, org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
  datasource:
    url: "jdbc:mariadb://${METADATA_HOST}:3306/${METADATA_DB}${METADATA_JDBC_EXTRA_ARGS}"
    driver-class-name: org.mariadb.jdbc.Driver
    username: "${METADATA_USERNAME}"
    password: "${METADATA_PASSWORD}"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      search:
        default:
          elasticsearch:
            host: search-db
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: "${METADATA_DB}"
        jdbc:
          time_zone: UTC
  application:
    name: metadata-service
  rabbitmq:
    host: "${BROKER_HOST}"
    virtual-host: "${BROKER_VIRTUALHOST}"
    password: "${BROKER_PASSWORD}"
    username: "${BROKER_USERNAME}"
    port: ${BROKER_PORT}
  opensearch:
    username: "${SEARCH_USERNAME}"
    password: "${SEARCH_PASSWORD}"
    host: search-db
    port: 9200
    protocol: http
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
server:
  port: 9099
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: "${LOG_LEVEL}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
fda:
  privileges: "${GRANT_PRIVILEGES}"
  pid:
    base: "${PID_BASE}"
  broker:
    endpoint: "${BROKER_ENDPOINT}"
  s3:
    endpoint: "${S3_STORAGE_ENDPOINT}"
    accessKeyId: "${S3_ACCESS_KEY_ID}"
    secretAccessKey: "${S3_SECRET_ACCESS_KEY}"
    importBucket: "${S3_IMPORT_BUCKET}"
    exportBucket: "${S3_EXPORT_BUCKET}"
  jwt:
    issuer: "${JWT_ISSUER}"
    public_key: "${JWT_PUBKEY}"
  keycloak:
    endpoint: "${KEYCLOAK_HOST}"
    username: "${KEYCLOAK_ADMIN}"
    password: "${KEYCLOAK_ADMIN_PASSWORD}"
  unsupported: "${NOT_SUPPORTED_KEYWORDS}"
  website: "${WEBSITE}"
  minConcurrent: "${MIN_CONCURRENT_CONSUMERS}"
  maxConcurrent: "${MAX_CONCURRENT_CONSUMERS}"
  requeueRejected: ${REQUEUE_REJECTED}
  queueName: "${QUEUE_NAME}"
  exchangeName: "${EXCHANGE_NAME}"
  routingKey: "${ROUTING_KEY}"
  connectionTimeout: ${CONNECTION_TIMEOUT}
  mirrorRate: "${MIRROR_RATE}"
  obtainMetadataRate: "${OBTAIN_METADATA_RATE}"
  deleteStaleQueriesRate: "${DELETE_STALE_QUERIES_RATE}"
dbrepo:
  repository-name: "${REPOSITORY_NAME}"
  base-url: "${BASE_URL}"
  admin-email: "${ADMIN_MAIL}"
  earliest-datestamp: "${EARLIEST_DATESTAMP}"
  deleted-record: "${DELETED_RECORD}"
  granularity: "${GRANULARITY}"
