app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: jdbc:mariadb://localhost:3306/fda
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dbrepo
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      search:
        default:
          elasticsearch:
            host: localhost
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: fda
        jdbc:
          time_zone: UTC
  application:
    name: metadata-service
  rabbitmq:
    host: localhost
    virtual-host: dbrepo
    username: fda
    password: fda
    port: 5672
  opensearch:
    username: admin
    password: admin
    host: localhost
    port: 9200
    protocol: http
  cloud:
    loadbalancer.ribbon.enabled: false
management.endpoints.web.exposure.include: health,info,prometheus
server:
  port: 19099
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: trace
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
fda:
  privileges: SELECT, CREATE, CREATE VIEW, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, INDEX, TRIGGER, INSERT, UPDATE, DELETE
  pid:
    base: https://example.com/pid/
  broker:
    endpoint: http://localhost:15672
  s3:
    endpoint: http://localhost:9000
    accessKeyId: seaweedfsadmin
    secretAccessKey: seaweedfsadmin
    importBucket: dbrepo-upload
    exportBucket: dbrepo-download
  jwt:
    issuer: http://localhost/api/auth/realms/dbrepo
    public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqqnHQ2BWWW9vDNLRCcxD++xZg/16oqMo/c1l+lcFEjjAIJjJp/HqrPYU/U9GvquGE6PbVFtTzW1KcKawOW+FJNOA3CGo8Q1TFEfz43B8rZpKsFbJKvQGVv1Z4HaKPvLUm7iMm8Hv91cLduuoWx6Q3DPe2vg13GKKEZe7UFghF+0T9u8EKzA/XqQ0OiICmsmYPbwvf9N3bCKsB/Y10EYmZRb8IhCoV9mmO5TxgWgiuNeCTtNCv2ePYqL/U0WvyGFW0reasIK8eg3KrAUj8DpyOgPOVBn3lBGf+3KFSYi+0bwZbJZWqbC/Xlk20Go1YfeJPRIt7ImxD27R/lNjgDO/MwIDAQAB
  keycloak:
    endpoint: "http://authentication-service:8080"
    username: fda
    password: fda
    clientSecret: MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG
  unsupported: \*,AVG,BIT_AND,BIT_OR,BIT_XOR,COUNT,COUNTDISTINCT,GROUP_CONCAT,JSON_ARRAYAGG,JSON_OBJECTAGG,MAX,MIN,STD,STDDEV,STDDEV_POP,STDDEV_SAMP,SUM,VARIANCE,VAR_POP,VAR_SAMP,--
  website: http://localhost
  minConcurrent: 1
  maxConcurrent: 5
  requeueRejected: true
  queueName: "dbrepo"
  exchangeName: "dbrepo"
  routingKey: "dbrepo.#"
  connectionTimeout: 60000
  mirrorRate: 60
  obtainMetadataRate: 60
  deleteStaleQueriesRate: 60
dbrepo:
  repository-name: TU Wien Database Repository
  base-url: https://dbrepo1.ec.tuwien.at/api/oai
  admin-email: noreply@example.com
  earliest-datestamp: 2022-09-17T16:09:00Z
  deleted-record: persistent
  granularity: YYYY-MM-DDThh:mm:ssZ
