application:
  title: DBRepo
  version: '@project.version@'
spring:
  data:
    redis:
      host: "${CACHE_DB_HOST:cache-db}"
      port: "${CACHE_DB_PORT:6379}"
      timeout: 3000
      connectTimeout: 10000
      clientName: dbrepo
      password: "${CACHE_DB_PASSWORD:valkey}"
      username: "${CACHE_DB_USERNAME:default}"
  datasource:
    url: "${METADATA_DB_URL:jdbc:postgresql://localhost:5432/dbrepo}"
    driverClassName: "${METADATA_DB_DRIVER:org.postgresql.Driver}"
    username: "${METADATA_DB_USERNAME:dbrepo}"
    password: "${METADATA_DB_PASSWORD:dbrepo}"
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: "${METADATA_DB_SCHEMA:dbrepo}"
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${OAUTH_ISSUER_URI:http://localhost:8080/realms/dbrepo}"
          jwk-set-uri: "${OAUTH_JWK_SET_URI:http://auth-service:8080/realms/dbrepo/protocol/openid-connect/certs}"
  application:
    name: metadata-service
  rabbitmq:
    host: "${BROKER_HOST:localhost}"
    virtual-host: "${BROKER_VIRTUALHOST:dbrepo}"
    username: "${BROKER_USERNAME:admin}"
    password: "${BROKER_PASSWORD:admin}"
    port: ${BROKER_PORT:5672}
  main:
    banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
server:
  port: 8080
  max-http-request-header-size: 64KB
logging:
  file:
    name: /var/log/app/service/metadata/app.log
  level:
    root: "${LOG_ROOT_LEVEL:warn}"
    at.ac.tuwien.ifs.dbrepo.: "${LOG_APPLICATION_LEVEL:info}"
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
  pattern:
    console: "%d %highlight(%-5level) %msg%n"
  structured:
    format:
      file: ecs
dbrepo:
  cache:
    provider: "${CACHE_DB_PROVIDER:valkey}"
    ttl: "${CACHE_TTL:60}"
  datacite:
    url: "${DATACITE_URL:https://api.datacite.org}"
    prefix: "${DATACITE_PREFIX}"
    username: "${DATACITE_USERNAME}"
    password: "${DATACITE_PASSWORD}"
  endpoints:
    analyseService: "${ANALYSE_SERVICE_ENDPOINT:http://analyse-service:8080}"
    authService: "${AUTH_SERVICE_ENDPOINT:http://auth-service:8080}"
    brokerService: "${BROKER_SERVICE_ENDPOINT:http://broker-service:15672}"
    crossRefService: "${CROSSREF_ENDPOINT:http://data.crossref.org}"
    dashboardService: "${DASHBOARD_SERVICE_ENDPOINT:http://dashboard-service:8080}"
    doiService: "${DOI_ENDPOINT:https://doi.org}"
    dataService: "${DATA_SERVICE_ENDPOINT:http://data-service:8080}"
    rorService: "${ROR_ENDPOINT:https://api.ror.org}"
    searchService: "${SEARCH_SERVICE_ENDPOINT:http://search-service:8080}"
    storageService: "${S3_ENDPOINT:http://storage-service:9000}"
  s3:
    accessKeyId: "${S3_ACCESS_KEY_ID:seaweedfsadmin}"
    secretAccessKey: "${S3_SECRET_ACCESS_KEY:seaweedfsadmin}"
    bucket: "${S3_BUCKET:dbrepo}"
  system:
    username: "${SYSTEM_USERNAME:admin}"
    password: "${SYSTEM_PASSWORD:admin}"
  pid:
    base: "${BASE_URL:http://localhost}/pid/"
  keycloak:
    realm: "${REALM_NAME:dbrepo}"
    username: "${AUTH_SERVICE_ADMIN:admin}"
    password: "${AUTH_SERVICE_ADMIN_PASSWORD:admin}"
    client: "${AUTH_SERVICE_CLIENT:dbrepo-client}"
    clientSecret: "${AUTH_SERVICE_CLIENT_SECRET:MUwRc7yfXSJwX8AdRMWaQC3Nep1VjwgG}"
  website: "${BASE_URL:http://localhost}"
  repositoryName: "${REPOSITORY_NAME:Database Repository}"
  baseUrl: "${BASE_URL:http://localhost}"
  adminEmail: "${ADMIN_EMAIL:noreply@example.com}"
  deletedRecord: "${DELETED_RECORD:persistent}"
  granularity: "${GRANULARITY:YYYY-MM-DDThh:mm:ssZ}"
  exchangeName: "${BROKER_EXCHANGE_NAME:dbrepo}"
  queueName: "${BROKER_QUEUE_NAME:dbrepo}"
  connectionTimeout: "${SPARQL_CONNECTION_TIMEOUT:10000}"
