package at.tuwien.api.database.table.columns;

import at.tuwien.api.container.image.ImageDateDto;
import at.tuwien.api.database.table.columns.concepts.ConceptDto;
import at.tuwien.api.database.table.columns.concepts.UnitDto;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import lombok.extern.jackson.Jacksonized;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;

import java.util.List;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Jacksonized
@ToString
@Document(indexName = "column")
public class ColumnDto {

    @Id
    @NotNull
    @Field(name = "id", type = FieldType.Keyword)
    private Long id;

    @NotNull
    @Field(name = "database_id", type = FieldType.Keyword)
    @JsonProperty("database_id")
    private Long databaseId;

    @NotNull
    @Field(name = "table_id", type = FieldType.Keyword)
    @JsonProperty("table_id")
    private Long tableId;

    @NotBlank
    @Schema(example = "Date")
    @Field(name = "name", type = FieldType.Keyword)
    private String name;

    @NotBlank
    @JsonProperty("internal_name")
    @Field(name = "internal_name", type = FieldType.Keyword)
    @Schema(example = "mdb_date")
    private String internalName;

    @Field(name = "alias", type = FieldType.Keyword)
    @Schema
    private String alias;

    @JsonProperty("date_format")
    @Field(name = "date_format", includeInParent = true, type = FieldType.Nested)
    private ImageDateDto dateFormat;

    @NotNull
    @JsonProperty("auto_generated")
    @Field(name = "auto_generated", type = FieldType.Boolean)
    @Schema(example = "false")
    private Boolean autoGenerated;

    @NotNull
    @JsonProperty("is_primary_key")
    @Field(name = "is_primary_key", type = FieldType.Boolean)
    @Schema(example = "true")
    private Boolean isPrimaryKey;

    @Field(name = "index_length", type = FieldType.Integer)
    @JsonProperty("index_length")
    private Integer indexLength;

    @NotNull
    @JsonProperty("column_type")
    @Field(name = "column_type", type = FieldType.Keyword)
    @Schema(example = "string")
    private ColumnTypeDto columnType;

    @Schema(example = "255")
    @Field(name = "size", type = FieldType.Integer)
    private Integer size;

    @Schema(example = "0")
    @Field(name = "d", type = FieldType.Integer)
    private Integer d;

    @Field(name = "concept", includeInParent = true, type = FieldType.Nested)
    private ConceptDto concept;

    @Field(name = "unit", includeInParent = true, type = FieldType.Nested)
    private UnitDto unit;

    @NotNull
    @JsonProperty("is_public")
    @Field(name = "is_public", type = FieldType.Boolean)
    @Schema(example = "true")
    private Boolean isPublic;

    @NotNull
    @JsonProperty("is_null_allowed")
    @Field(name = "is_null_allowed", type = FieldType.Boolean)
    @Schema(example = "false")
    private Boolean isNullAllowed;

    @Field(name = "enums", includeInParent = true, type = FieldType.Nested)
    @Parameter(description = "enum values, only considered when type = ENUM")
    private List<String> enums;

    @Field(name = "sets", includeInParent = true, type = FieldType.Nested)
    @Parameter(description = "enum values, only considered when type = ENUM")
    private List<String> sets;

}
