package at.tuwien.entities.database.table.columns;

import at.tuwien.entities.container.image.ContainerImageDate;
import at.tuwien.entities.database.table.Table;
import at.tuwien.entities.database.table.columns.concepts.ColumnConcept;
import at.tuwien.entities.database.table.columns.concepts.Concept;
import at.tuwien.entities.user.User;
import lombok.*;
import lombok.extern.log4j.Log4j2;
import net.sf.jsqlparser.statement.select.SelectItem;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.time.Instant;
import java.util.List;

@Data
@Entity
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Document(indexName = "columnindex", createIndex = false)
@IdClass(TableColumnKey.class)
@ToString
@Log4j2
@EntityListeners(AuditingEntityListener.class)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@javax.persistence.Table(name = "mdb_columns", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"tid", "internalName"})
})
public class TableColumn implements Comparable<TableColumn> {

    @Id
    @EqualsAndHashCode.Include
    @GeneratedValue(generator = "column-sequence")
    @GenericGenerator(
            name = "column-sequence",
            strategy = "enhanced-sequence",
            parameters = @org.hibernate.annotations.Parameter(name = "sequence_name", value = "mdb_columns_seq")
    )
    private Long id;

    @Id
    @EqualsAndHashCode.Include
    private Long tid;

    @Id
    @EqualsAndHashCode.Include
    private Long cdbid;

    @Column
    private Long dfid;

    @ToString.Exclude
    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "dfid", referencedColumnName = "id", insertable = false, updatable = false)
    private ContainerImageDate dateFormat;

    @org.springframework.data.annotation.Transient
    @ToString.Exclude
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumns({
            @JoinColumn(name = "tid", referencedColumnName = "id", insertable = false, updatable = false),
            @JoinColumn(name = "cdbid", referencedColumnName = "tdbid", insertable = false, updatable = false)
    })
    private Table table;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumns({
            @JoinColumn(name = "createdBy", referencedColumnName = "UserID")
    })
    private User creator;

    @Column(name = "cname", nullable = false)
    private String name;

    @Column(name = "auto_generated")
    private Boolean autoGenerated = false;

    @Column(nullable = false)
    private String internalName;

    @Column(nullable = false)
    private Boolean isPrimaryKey = false;

    @Column(name = "datatype", nullable = false)
    @Enumerated(EnumType.STRING)
    private TableColumnType columnType;

    @Column(nullable = false)
    private Boolean isNullAllowed = true;

    @Column(nullable = false)
    private Boolean isUnique;

    @Column
    private String checkExpression;

    @ElementCollection
    @CollectionTable(name = "mdb_columns_enums", joinColumns = {
            @JoinColumn(name = "id", insertable = false, updatable = false),
            @JoinColumn(name = "tid", insertable = false, updatable = false),
            @JoinColumn(name = "edbid", insertable = false, updatable = false)
    })
    private List<String> enumValues;

    @Column(nullable = false)
    private Integer ordinalPosition;

    @Column
    private String foreignKey;

    @Column(name = "reference_table")
    private String references;

    @Column(nullable = false, updatable = false)
    @CreatedDate
    private Instant created;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinTable(name = "mdb_columns_concepts",
            joinColumns = {
                    @JoinColumn(name = "cid", referencedColumnName = "id", insertable = false, updatable = false),
                    @JoinColumn(name = "tid", referencedColumnName = "tid", insertable = false, updatable = false),
                    @JoinColumn(name = "cdbid", referencedColumnName = "cdbid", insertable = false, updatable = false)
            },
            inverseJoinColumns = @JoinColumn(name = "uri"))
    private Concept concept;

    @Column
    @LastModifiedDate
    private Instant lastModified;

    @Override
    public int compareTo(TableColumn tableColumn) {
        return Integer.compare(this.ordinalPosition, tableColumn.getOrdinalPosition());
    }

    public boolean equals(SelectItem other) {
        final String name = other.toString()
                .replace("`","");
        final int idx = name.indexOf('.');
        if (idx == -1) {
            log.trace("internal name {} =?= name {}", this.internalName, name);
            return name.equals(this.internalName);
        }
        log.trace("internal name {} =?= name {}", this.internalName, name.substring(idx + 1));
        return name.substring(idx + 1)
                .equals(this.internalName);
    }
}
