# coding: utf-8

"""
    Database Repository Document Service API

    Service that manages the documents  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DraftVersionsDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'index': 'int',
        'is_latest': 'bool',
        'is_latest_draft': 'bool'
    }

    attribute_map = {
        'index': 'index',
        'is_latest': 'is_latest',
        'is_latest_draft': 'is_latest_draft'
    }

    def __init__(self, index=None, is_latest=None, is_latest_draft=None):  # noqa: E501
        """DraftVersionsDto - a model defined in Swagger"""  # noqa: E501
        self._index = None
        self._is_latest = None
        self._is_latest_draft = None
        self.discriminator = None
        if index is not None:
            self.index = index
        if is_latest is not None:
            self.is_latest = is_latest
        if is_latest_draft is not None:
            self.is_latest_draft = is_latest_draft

    @property
    def index(self):
        """Gets the index of this DraftVersionsDto.  # noqa: E501


        :return: The index of this DraftVersionsDto.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this DraftVersionsDto.


        :param index: The index of this DraftVersionsDto.  # noqa: E501
        :type: int
        """

        self._index = index

    @property
    def is_latest(self):
        """Gets the is_latest of this DraftVersionsDto.  # noqa: E501


        :return: The is_latest of this DraftVersionsDto.  # noqa: E501
        :rtype: bool
        """
        return self._is_latest

    @is_latest.setter
    def is_latest(self, is_latest):
        """Sets the is_latest of this DraftVersionsDto.


        :param is_latest: The is_latest of this DraftVersionsDto.  # noqa: E501
        :type: bool
        """

        self._is_latest = is_latest

    @property
    def is_latest_draft(self):
        """Gets the is_latest_draft of this DraftVersionsDto.  # noqa: E501


        :return: The is_latest_draft of this DraftVersionsDto.  # noqa: E501
        :rtype: bool
        """
        return self._is_latest_draft

    @is_latest_draft.setter
    def is_latest_draft(self, is_latest_draft):
        """Sets the is_latest_draft of this DraftVersionsDto.


        :param is_latest_draft: The is_latest_draft of this DraftVersionsDto.  # noqa: E501
        :type: bool
        """

        self._is_latest_draft = is_latest_draft

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DraftVersionsDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DraftVersionsDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
