# coding: utf-8

"""
    Database Repository Document Service API

    Service that manages the documents  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FileAnnounceDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'entries': 'list[FileEntryDto]',
        'links': 'LinksDto',
        'default_preview': 'str'
    }

    attribute_map = {
        'enabled': 'enabled',
        'entries': 'entries',
        'links': 'links',
        'default_preview': 'default_preview'
    }

    def __init__(self, enabled=None, entries=None, links=None, default_preview=None):  # noqa: E501
        """FileAnnounceDto - a model defined in Swagger"""  # noqa: E501
        self._enabled = None
        self._entries = None
        self._links = None
        self._default_preview = None
        self.discriminator = None
        self.enabled = enabled
        self.entries = entries
        if links is not None:
            self.links = links
        if default_preview is not None:
            self.default_preview = default_preview

    @property
    def enabled(self):
        """Gets the enabled of this FileAnnounceDto.  # noqa: E501


        :return: The enabled of this FileAnnounceDto.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this FileAnnounceDto.


        :param enabled: The enabled of this FileAnnounceDto.  # noqa: E501
        :type: bool
        """
        if enabled is None:
            raise ValueError("Invalid value for `enabled`, must not be `None`")  # noqa: E501

        self._enabled = enabled

    @property
    def entries(self):
        """Gets the entries of this FileAnnounceDto.  # noqa: E501


        :return: The entries of this FileAnnounceDto.  # noqa: E501
        :rtype: list[FileEntryDto]
        """
        return self._entries

    @entries.setter
    def entries(self, entries):
        """Sets the entries of this FileAnnounceDto.


        :param entries: The entries of this FileAnnounceDto.  # noqa: E501
        :type: list[FileEntryDto]
        """
        if entries is None:
            raise ValueError("Invalid value for `entries`, must not be `None`")  # noqa: E501

        self._entries = entries

    @property
    def links(self):
        """Gets the links of this FileAnnounceDto.  # noqa: E501


        :return: The links of this FileAnnounceDto.  # noqa: E501
        :rtype: LinksDto
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this FileAnnounceDto.


        :param links: The links of this FileAnnounceDto.  # noqa: E501
        :type: LinksDto
        """

        self._links = links

    @property
    def default_preview(self):
        """Gets the default_preview of this FileAnnounceDto.  # noqa: E501


        :return: The default_preview of this FileAnnounceDto.  # noqa: E501
        :rtype: str
        """
        return self._default_preview

    @default_preview.setter
    def default_preview(self, default_preview):
        """Sets the default_preview of this FileAnnounceDto.


        :param default_preview: The default_preview of this FileAnnounceDto.  # noqa: E501
        :type: str
        """

        self._default_preview = default_preview

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FileAnnounceDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileAnnounceDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
