# coding: utf-8

"""
    Database Repository Query Service API

    Service that manages the queries  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatabaseDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'exchange': 'str',
        'creator': 'UserBriefDto',
        'subjects': 'list[str]',
        'language': 'str',
        'license': 'LicenseDto',
        'description': 'str',
        'publisher': 'str',
        'contact': 'UserDto',
        'tables': 'list[TableBriefDto]',
        'image': 'ImageDto',
        'container': 'ContainerDto',
        'created': 'datetime',
        'deleted': 'datetime',
        'internal_name': 'str',
        'publication_year': 'int',
        'publication_month': 'int',
        'publication_day': 'int',
        'is_public': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'exchange': 'exchange',
        'creator': 'creator',
        'subjects': 'subjects',
        'language': 'language',
        'license': 'license',
        'description': 'description',
        'publisher': 'publisher',
        'contact': 'contact',
        'tables': 'tables',
        'image': 'image',
        'container': 'container',
        'created': 'created',
        'deleted': 'deleted',
        'internal_name': 'internal_name',
        'publication_year': 'publication_year',
        'publication_month': 'publication_month',
        'publication_day': 'publication_day',
        'is_public': 'is_public'
    }

    def __init__(self, id=None, name=None, exchange=None, creator=None, subjects=None, language=None, license=None, description=None, publisher=None, contact=None, tables=None, image=None, container=None, created=None, deleted=None, internal_name=None, publication_year=None, publication_month=None, publication_day=None, is_public=None):  # noqa: E501
        """DatabaseDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._exchange = None
        self._creator = None
        self._subjects = None
        self._language = None
        self._license = None
        self._description = None
        self._publisher = None
        self._contact = None
        self._tables = None
        self._image = None
        self._container = None
        self._created = None
        self._deleted = None
        self._internal_name = None
        self._publication_year = None
        self._publication_month = None
        self._publication_day = None
        self._is_public = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.exchange = exchange
        self.creator = creator
        if subjects is not None:
            self.subjects = subjects
        if language is not None:
            self.language = language
        if license is not None:
            self.license = license
        if description is not None:
            self.description = description
        if publisher is not None:
            self.publisher = publisher
        if contact is not None:
            self.contact = contact
        if tables is not None:
            self.tables = tables
        if image is not None:
            self.image = image
        if container is not None:
            self.container = container
        if created is not None:
            self.created = created
        if deleted is not None:
            self.deleted = deleted
        self.internal_name = internal_name
        if publication_year is not None:
            self.publication_year = publication_year
        if publication_month is not None:
            self.publication_month = publication_month
        if publication_day is not None:
            self.publication_day = publication_day
        if is_public is not None:
            self.is_public = is_public

    @property
    def id(self):
        """Gets the id of this DatabaseDto.  # noqa: E501


        :return: The id of this DatabaseDto.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DatabaseDto.


        :param id: The id of this DatabaseDto.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this DatabaseDto.  # noqa: E501


        :return: The name of this DatabaseDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DatabaseDto.


        :param name: The name of this DatabaseDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def exchange(self):
        """Gets the exchange of this DatabaseDto.  # noqa: E501


        :return: The exchange of this DatabaseDto.  # noqa: E501
        :rtype: str
        """
        return self._exchange

    @exchange.setter
    def exchange(self, exchange):
        """Sets the exchange of this DatabaseDto.


        :param exchange: The exchange of this DatabaseDto.  # noqa: E501
        :type: str
        """
        if exchange is None:
            raise ValueError("Invalid value for `exchange`, must not be `None`")  # noqa: E501

        self._exchange = exchange

    @property
    def creator(self):
        """Gets the creator of this DatabaseDto.  # noqa: E501


        :return: The creator of this DatabaseDto.  # noqa: E501
        :rtype: UserBriefDto
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this DatabaseDto.


        :param creator: The creator of this DatabaseDto.  # noqa: E501
        :type: UserBriefDto
        """
        if creator is None:
            raise ValueError("Invalid value for `creator`, must not be `None`")  # noqa: E501

        self._creator = creator

    @property
    def subjects(self):
        """Gets the subjects of this DatabaseDto.  # noqa: E501

        database subjects  # noqa: E501

        :return: The subjects of this DatabaseDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._subjects

    @subjects.setter
    def subjects(self, subjects):
        """Sets the subjects of this DatabaseDto.

        database subjects  # noqa: E501

        :param subjects: The subjects of this DatabaseDto.  # noqa: E501
        :type: list[str]
        """

        self._subjects = subjects

    @property
    def language(self):
        """Gets the language of this DatabaseDto.  # noqa: E501


        :return: The language of this DatabaseDto.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this DatabaseDto.


        :param language: The language of this DatabaseDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["ab", "aa", "af", "ak", "sq", "am", "ar", "an", "hy", "as", "av", "ae", "ay", "az", "bm", "ba", "eu", "be", "bn", "bh", "bi", "bs", "br", "bg", "my", "ca", "km", "ch", "ce", "ny", "zh", "cu", "cv", "kw", "co", "cr", "hr", "cs", "da", "dv", "nl", "dz", "en", "eo", "et", "ee", "fo", "fj", "fi", "fr", "ff", "gd", "gl", "lg", "ka", "de", "ki", "el", "kl", "gn", "gu", "ht", "ha", "he", "hz", "hi", "ho", "hu", "is", "io", "ig", "id", "ia", "ie", "iu", "ik", "ga", "it", "ja", "jv", "kn", "kr", "ks", "kk", "rw", "kv", "kg", "ko", "kj", "ku", "ky", "lo", "la", "lv", "lb", "li", "ln", "lt", "lu", "mk", "mg", "ms", "ml", "mt", "gv", "mi", "mr", "mh", "ro", "mn", "na", "nv", "nd", "ng", "ne", "se", "no", "nb", "nn", "ii", "oc", "oj", "or", "om", "os", "pi", "pa", "ps", "fa", "pl", "pt", "qu", "rm", "rn", "ru", "sm", "sg", "sa", "sc", "sr", "sn", "sd", "si", "sk", "sl", "so", "st", "nr", "es", "su", "sw", "ss", "sv", "tl", "ty", "tg", "ta", "tt", "te", "th", "bo", "ti", "to", "ts", "tn", "tr", "tk", "tw", "ug", "uk", "ur", "uz", "ve", "vi", "vo", "wa", "cy", "fy", "wo", "xh", "yi", "yo", "za", "zu"]  # noqa: E501
        if language not in allowed_values:
            raise ValueError(
                "Invalid value for `language` ({0}), must be one of {1}"  # noqa: E501
                .format(language, allowed_values)
            )

        self._language = language

    @property
    def license(self):
        """Gets the license of this DatabaseDto.  # noqa: E501


        :return: The license of this DatabaseDto.  # noqa: E501
        :rtype: LicenseDto
        """
        return self._license

    @license.setter
    def license(self, license):
        """Sets the license of this DatabaseDto.


        :param license: The license of this DatabaseDto.  # noqa: E501
        :type: LicenseDto
        """

        self._license = license

    @property
    def description(self):
        """Gets the description of this DatabaseDto.  # noqa: E501


        :return: The description of this DatabaseDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this DatabaseDto.


        :param description: The description of this DatabaseDto.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def publisher(self):
        """Gets the publisher of this DatabaseDto.  # noqa: E501


        :return: The publisher of this DatabaseDto.  # noqa: E501
        :rtype: str
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher):
        """Sets the publisher of this DatabaseDto.


        :param publisher: The publisher of this DatabaseDto.  # noqa: E501
        :type: str
        """

        self._publisher = publisher

    @property
    def contact(self):
        """Gets the contact of this DatabaseDto.  # noqa: E501


        :return: The contact of this DatabaseDto.  # noqa: E501
        :rtype: UserDto
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this DatabaseDto.


        :param contact: The contact of this DatabaseDto.  # noqa: E501
        :type: UserDto
        """

        self._contact = contact

    @property
    def tables(self):
        """Gets the tables of this DatabaseDto.  # noqa: E501


        :return: The tables of this DatabaseDto.  # noqa: E501
        :rtype: list[TableBriefDto]
        """
        return self._tables

    @tables.setter
    def tables(self, tables):
        """Sets the tables of this DatabaseDto.


        :param tables: The tables of this DatabaseDto.  # noqa: E501
        :type: list[TableBriefDto]
        """

        self._tables = tables

    @property
    def image(self):
        """Gets the image of this DatabaseDto.  # noqa: E501


        :return: The image of this DatabaseDto.  # noqa: E501
        :rtype: ImageDto
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this DatabaseDto.


        :param image: The image of this DatabaseDto.  # noqa: E501
        :type: ImageDto
        """

        self._image = image

    @property
    def container(self):
        """Gets the container of this DatabaseDto.  # noqa: E501


        :return: The container of this DatabaseDto.  # noqa: E501
        :rtype: ContainerDto
        """
        return self._container

    @container.setter
    def container(self, container):
        """Sets the container of this DatabaseDto.


        :param container: The container of this DatabaseDto.  # noqa: E501
        :type: ContainerDto
        """

        self._container = container

    @property
    def created(self):
        """Gets the created of this DatabaseDto.  # noqa: E501


        :return: The created of this DatabaseDto.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this DatabaseDto.


        :param created: The created of this DatabaseDto.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def deleted(self):
        """Gets the deleted of this DatabaseDto.  # noqa: E501


        :return: The deleted of this DatabaseDto.  # noqa: E501
        :rtype: datetime
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this DatabaseDto.


        :param deleted: The deleted of this DatabaseDto.  # noqa: E501
        :type: datetime
        """

        self._deleted = deleted

    @property
    def internal_name(self):
        """Gets the internal_name of this DatabaseDto.  # noqa: E501


        :return: The internal_name of this DatabaseDto.  # noqa: E501
        :rtype: str
        """
        return self._internal_name

    @internal_name.setter
    def internal_name(self, internal_name):
        """Sets the internal_name of this DatabaseDto.


        :param internal_name: The internal_name of this DatabaseDto.  # noqa: E501
        :type: str
        """
        if internal_name is None:
            raise ValueError("Invalid value for `internal_name`, must not be `None`")  # noqa: E501

        self._internal_name = internal_name

    @property
    def publication_year(self):
        """Gets the publication_year of this DatabaseDto.  # noqa: E501

        database publication year  # noqa: E501

        :return: The publication_year of this DatabaseDto.  # noqa: E501
        :rtype: int
        """
        return self._publication_year

    @publication_year.setter
    def publication_year(self, publication_year):
        """Sets the publication_year of this DatabaseDto.

        database publication year  # noqa: E501

        :param publication_year: The publication_year of this DatabaseDto.  # noqa: E501
        :type: int
        """

        self._publication_year = publication_year

    @property
    def publication_month(self):
        """Gets the publication_month of this DatabaseDto.  # noqa: E501

        database publication month  # noqa: E501

        :return: The publication_month of this DatabaseDto.  # noqa: E501
        :rtype: int
        """
        return self._publication_month

    @publication_month.setter
    def publication_month(self, publication_month):
        """Sets the publication_month of this DatabaseDto.

        database publication month  # noqa: E501

        :param publication_month: The publication_month of this DatabaseDto.  # noqa: E501
        :type: int
        """

        self._publication_month = publication_month

    @property
    def publication_day(self):
        """Gets the publication_day of this DatabaseDto.  # noqa: E501

        database publication day  # noqa: E501

        :return: The publication_day of this DatabaseDto.  # noqa: E501
        :rtype: int
        """
        return self._publication_day

    @publication_day.setter
    def publication_day(self, publication_day):
        """Sets the publication_day of this DatabaseDto.

        database publication day  # noqa: E501

        :param publication_day: The publication_day of this DatabaseDto.  # noqa: E501
        :type: int
        """

        self._publication_day = publication_day

    @property
    def is_public(self):
        """Gets the is_public of this DatabaseDto.  # noqa: E501

        database publicity  # noqa: E501

        :return: The is_public of this DatabaseDto.  # noqa: E501
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """Sets the is_public of this DatabaseDto.

        database publicity  # noqa: E501

        :param is_public: The is_public of this DatabaseDto.  # noqa: E501
        :type: bool
        """

        self._is_public = is_public

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatabaseDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatabaseDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
