# coding: utf-8

"""
    Database Repository Query Service API

    Service that manages the queries  # noqa: E501

    OpenAPI spec version: 1.1.0-alpha
    Contact: andreas.rauber@tuwien.ac.at
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QueryDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'cid': 'int',
        'dbid': 'int',
        'creator': 'UserDto',
        'execution': 'datetime',
        'query': 'str',
        'created': 'datetime',
        'query_normalized': 'str',
        'query_hash': 'str',
        'result_hash': 'str',
        'result_number': 'int',
        'last_modified': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'cid': 'cid',
        'dbid': 'dbid',
        'creator': 'creator',
        'execution': 'execution',
        'query': 'query',
        'created': 'created',
        'query_normalized': 'query_normalized',
        'query_hash': 'query_hash',
        'result_hash': 'result_hash',
        'result_number': 'result_number',
        'last_modified': 'last_modified'
    }

    def __init__(self, id=None, cid=None, dbid=None, creator=None, execution=None, query=None, created=None, query_normalized=None, query_hash=None, result_hash=None, result_number=None, last_modified=None):  # noqa: E501
        """QueryDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._cid = None
        self._dbid = None
        self._creator = None
        self._execution = None
        self._query = None
        self._created = None
        self._query_normalized = None
        self._query_hash = None
        self._result_hash = None
        self._result_number = None
        self._last_modified = None
        self.discriminator = None
        self.id = id
        self.cid = cid
        self.dbid = dbid
        self.creator = creator
        if execution is not None:
            self.execution = execution
        self.query = query
        self.created = created
        if query_normalized is not None:
            self.query_normalized = query_normalized
        self.query_hash = query_hash
        if result_hash is not None:
            self.result_hash = result_hash
        if result_number is not None:
            self.result_number = result_number
        if last_modified is not None:
            self.last_modified = last_modified

    @property
    def id(self):
        """Gets the id of this QueryDto.  # noqa: E501


        :return: The id of this QueryDto.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this QueryDto.


        :param id: The id of this QueryDto.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def cid(self):
        """Gets the cid of this QueryDto.  # noqa: E501


        :return: The cid of this QueryDto.  # noqa: E501
        :rtype: int
        """
        return self._cid

    @cid.setter
    def cid(self, cid):
        """Sets the cid of this QueryDto.


        :param cid: The cid of this QueryDto.  # noqa: E501
        :type: int
        """
        if cid is None:
            raise ValueError("Invalid value for `cid`, must not be `None`")  # noqa: E501

        self._cid = cid

    @property
    def dbid(self):
        """Gets the dbid of this QueryDto.  # noqa: E501


        :return: The dbid of this QueryDto.  # noqa: E501
        :rtype: int
        """
        return self._dbid

    @dbid.setter
    def dbid(self, dbid):
        """Sets the dbid of this QueryDto.


        :param dbid: The dbid of this QueryDto.  # noqa: E501
        :type: int
        """
        if dbid is None:
            raise ValueError("Invalid value for `dbid`, must not be `None`")  # noqa: E501

        self._dbid = dbid

    @property
    def creator(self):
        """Gets the creator of this QueryDto.  # noqa: E501


        :return: The creator of this QueryDto.  # noqa: E501
        :rtype: UserDto
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this QueryDto.


        :param creator: The creator of this QueryDto.  # noqa: E501
        :type: UserDto
        """
        if creator is None:
            raise ValueError("Invalid value for `creator`, must not be `None`")  # noqa: E501

        self._creator = creator

    @property
    def execution(self):
        """Gets the execution of this QueryDto.  # noqa: E501


        :return: The execution of this QueryDto.  # noqa: E501
        :rtype: datetime
        """
        return self._execution

    @execution.setter
    def execution(self, execution):
        """Sets the execution of this QueryDto.


        :param execution: The execution of this QueryDto.  # noqa: E501
        :type: datetime
        """

        self._execution = execution

    @property
    def query(self):
        """Gets the query of this QueryDto.  # noqa: E501


        :return: The query of this QueryDto.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this QueryDto.


        :param query: The query of this QueryDto.  # noqa: E501
        :type: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    @property
    def created(self):
        """Gets the created of this QueryDto.  # noqa: E501


        :return: The created of this QueryDto.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this QueryDto.


        :param created: The created of this QueryDto.  # noqa: E501
        :type: datetime
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def query_normalized(self):
        """Gets the query_normalized of this QueryDto.  # noqa: E501


        :return: The query_normalized of this QueryDto.  # noqa: E501
        :rtype: str
        """
        return self._query_normalized

    @query_normalized.setter
    def query_normalized(self, query_normalized):
        """Sets the query_normalized of this QueryDto.


        :param query_normalized: The query_normalized of this QueryDto.  # noqa: E501
        :type: str
        """

        self._query_normalized = query_normalized

    @property
    def query_hash(self):
        """Gets the query_hash of this QueryDto.  # noqa: E501


        :return: The query_hash of this QueryDto.  # noqa: E501
        :rtype: str
        """
        return self._query_hash

    @query_hash.setter
    def query_hash(self, query_hash):
        """Sets the query_hash of this QueryDto.


        :param query_hash: The query_hash of this QueryDto.  # noqa: E501
        :type: str
        """
        if query_hash is None:
            raise ValueError("Invalid value for `query_hash`, must not be `None`")  # noqa: E501

        self._query_hash = query_hash

    @property
    def result_hash(self):
        """Gets the result_hash of this QueryDto.  # noqa: E501


        :return: The result_hash of this QueryDto.  # noqa: E501
        :rtype: str
        """
        return self._result_hash

    @result_hash.setter
    def result_hash(self, result_hash):
        """Sets the result_hash of this QueryDto.


        :param result_hash: The result_hash of this QueryDto.  # noqa: E501
        :type: str
        """

        self._result_hash = result_hash

    @property
    def result_number(self):
        """Gets the result_number of this QueryDto.  # noqa: E501


        :return: The result_number of this QueryDto.  # noqa: E501
        :rtype: int
        """
        return self._result_number

    @result_number.setter
    def result_number(self, result_number):
        """Sets the result_number of this QueryDto.


        :param result_number: The result_number of this QueryDto.  # noqa: E501
        :type: int
        """

        self._result_number = result_number

    @property
    def last_modified(self):
        """Gets the last_modified of this QueryDto.  # noqa: E501


        :return: The last_modified of this QueryDto.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """Sets the last_modified of this QueryDto.


        :param last_modified: The last_modified of this QueryDto.  # noqa: E501
        :type: datetime
        """

        self._last_modified = last_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QueryDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QueryDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
