<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.10.RELEASE</version>
    </parent>

    <groupId>at.tuwien</groupId>
    <artifactId>dbrepo-metadata-service</artifactId>
    <version>1.2.0</version>
    <name>dbrepo-metadata-service</name>
    <description>Service that manages the metadata</description>

    <url>https://dbrepo-docs.ossdip.at</url>
    <developers>
        <developer>
            <name>Martin Weise</name>
            <email>martin.weise@tuwien.ac.at</email>
            <organization>TU Wien</organization>
        </developer>
        <developer>
            <name>Moritz Staudinger</name>
            <email>moritz.staudinger@tuwien.ac.at</email>
            <organization>TU Wien</organization>
        </developer>
    </developers>

    <packaging>pom</packaging>
    <modules>
        <module>rest-service</module>
        <module>services</module>
        <module>report</module>
    </modules>

    <properties>
        <java.version>11</java.version>
        <spring-cloud.version>3.0.1</spring-cloud.version>
        <mapstruct.version>1.4.2.Final</mapstruct.version>
        <swagger.version>2.1.7</swagger.version>
        <springfox.version>3.0.0</springfox.version>
        <jacoco.version>0.8.7</jacoco.version>
        <javax-ws-rs.version>2.1.1</javax-ws-rs.version>
        <spring-saml.version>1.0.10.RELEASE</spring-saml.version>
        <javax-rs.version>2.1.1</javax-rs.version>
        <javax-mail.version>1.4.7</javax-mail.version>
        <jwt.version>3.18.3</jwt.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
            <version>${spring-cloud.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <!-- Datasource -->
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>${mariadb.version}</version>
        </dependency>
        <!-- Monitoring -->
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <scope>runtime</scope>
        </dependency>
        <!-- Entity and API -->
        <dependency>
            <groupId>at.tuwien</groupId>
            <artifactId>dbrepo-metadata-db-oai</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>at.tuwien</groupId>
            <artifactId>dbrepo-metadata-db-api</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>at.tuwien</groupId>
            <artifactId>dbrepo-metadata-db-entites</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>at.tuwien</groupId>
            <artifactId>dbrepo-metadata-db-querystore</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <!-- IDE -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <!-- Mapping -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>${mapstruct.version}</version>
            <optional>true</optional><!-- IntelliJ -->
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
        <!-- Testing -->
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>${javax-ws-rs.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.jupiter</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <version>${jacoco.version}</version>
        </dependency>
        <dependency>
            <groupId>at.tuwien</groupId>
            <artifactId>dbrepo-metadata-db-test</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>${basedir}/src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/application*.yml</include>
                    <include>**/templates/*.xml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <configuration>
                    <excludes>
                        <exclude>at/tuwien/utils/**/*</exclude>
                        <exclude>at/tuwien/seeder/**/*</exclude>
                        <exclude>at/tuwien/mapper/**/*</exclude>
                        <exclude>at/tuwien/handlers/**/*</exclude>
                        <exclude>at/tuwien/exception/**/*</exclude>
                        <exclude>at/tuwien/config/**/*</exclude>
                        <exclude>**/DbrepoMetadataServiceApplication.class</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.7.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.0.0</version>
            </plugin>
            <plugin>
                <groupId>com.soebes.maven.plugins</groupId>
                <artifactId>doxygen-maven-plugin</artifactId>
                <version>1.1.0</version>
                <configuration>
                    <haveDot>false</haveDot>
                    <quiet>false</quiet>
                    <projectName>This is a Test Project (basicReportTest)</projectName>
                    <outputDirectory>docs</outputDirectory>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
