app.version: '@project.version@'
spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://metadata-db:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  application:
    name: identifier-service
  cloud:
    loadbalancer.ribbon.enabled: false
server.port: 9096
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
    at.tuwien.auth.UserPermissionEvaluator: trace
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
eureka:
  instance.hostname: identifier-service
  client.serviceUrl.defaultZone: http://discovery-service:9090/eureka/
fda:
  ready.path: /ready
  gateway.endpoint: "${GATEWAY_ENDPOINT}"