package at.tuwien.api.database.table;

import lombok.*;
import lombok.extern.jackson.Jacksonized;

import java.sql.PreparedStatement;

@Getter
@Setter
@Builder
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@Jacksonized
@ToString
public class TableCreateRawQuery {

    private PreparedStatement preparedStatement;

    /**
     * True if the "id" column was autogenerated by the service (e.g. not present before)
     */
    private Boolean generated;

}
