# Copyright the DBRepo developers
# SPDX-License-Identifier: APACHE-2.0

## @param namespaceOverride The namespace to install the chart

s3:
  endpoint: http://storage-service-s3:8333
  auth:
    adminAccessKeyId: seaweedfsadmin
    adminSecretAccessKey: seaweedfsadmin

database:
  ## @param database.enabled Enable the Metadata Database.
  enabled: true
  ## @skip database.fullnameOverride
  fullnameOverride: data-db
  ## @param database.host The hostname for the microservices.
  host: data-db
  rootUser:
    ## @param database.rootUser.user The root username.
    user: root
    ## @param database.rootUser.password The root user password.
    password: dbrepo
  db:
    ## @param database.db.name The database name.
    name: dbrepo
  galera:
    mariabackup:
      ## @param database.galera.mariabackup.user The database backup username.
      user: backup
      ## @param database.galera.mariabackup.password The database backup user password
      password: backup
  ## @param database.jdbcExtraArgs The extra arguments for JDBC connections in the microservices.
  jdbcExtraArgs: ""
  metrics:
    ## @skip database.metrics.enabled The Prometheus settings.
    enabled: false
  ## @skip database.initdbScriptsConfigMap The initial database scripts.
  initdbScriptsConfigMap: database-setup
  ## @param database.extraInitDbScripts Additional init.db scripts that are executed on the first start.
  extraInitDbScripts: { }
  #    03-additional-data.sql: |
  #      BEGIN;
  #      INSERT INTO `mdb_containers` (name, internal_name, image_id, host, port, sidecar_host, sidecar_port, privileged_username, privileged_password)
  #        VALUES ('MariaDB Galera TEST', 'mariadb_11_1_3', 1, 'data-db', 3306, 'data-db', 80, 'root', 'dbrepo');
  #      COMMIT;
  ## @param database.replicaCount The number of cluster nodes, should be uneven i.e. 2n+1
  replicaCount: 3
  persistence:
    ## @param database.persistence.enabled Enable persistent storage.
    enabled: true
  ## @skip database.service
  service:
    extraPorts:
      - name: "sidecar"
        port: 8080
        targetPort: 8080
        protocol: TCP
  ## @skip database.sidecars
  sidecars:
    - name: sidecar
      image: registry.datalab.tuwien.ac.at/dbrepo/data-db-sidecar:1.4.5
      imagePullPolicy: Always
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      ports:
        - name: "sidecar"
          containerPort: 8080
          protocol: TCP
      envFrom:
        - secretRef:
            name: data-service-secret
      livenessProbe:
        exec:
          command:
            - /bin/bash
            - -ec
            - "curl -sSL localhost:8080/health | grep 'UP' || exit 1"
        initialDelaySeconds: 120
        periodSeconds: 30
      readinessProbe:
        exec:
          command:
            - /bin/bash
            - -ec
            - "curl -sSL localhost:8080/health | grep 'UP' || exit 1"
        initialDelaySeconds: 30
        periodSeconds: 30
      volumeMounts:
        - name: s3
          mountPath: /s3
  ## @skip database.extraVolumeMounts
  extraVolumeMounts:
    - name: s3
      mountPath: /s3
  ## @skip database.extraVolumes
  extraVolumes:
    - name: s3
      emptyDir: { }
