apiVersion: v2
name: dbrepo
description: Helm Chart for installing DBRepo
sources:
  - https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
type: application
version: "1.4.2"
appVersion: "1.4.2"
keywords:
  - dbrepo
maintainers:
  - name: Martin Weise
    email: martin.weise@tuwien.ac.at
home: https://www.ifs.tuwien.ac.at/infrastructures/dbrepo/
icon: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services/-/raw/master/.docs/images/signet_white.png
dependencies:
  - name: opensearch
    alias: searchdb
    version: 2.15.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: searchdb.enabled
  - name: opensearch-dashboards
    alias: searchDbDashboard
    version: 2.13.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: searchDbDashboard.enabled
  - name: keycloak
    alias: authService
    version: 17.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: authService.enabled
  - name: mariadb-galera
    alias: dataDb
    version: 11.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: dataDb.enabled
  - name: mariadb-galera
    alias: metadataDb
    version: 11.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: metadataDb.enabled
  - name: postgresql-ha
    alias: authDb
    version: 12.1.7
    repository: https://charts.bitnami.com/bitnami
    condition: authDb.enabled
  - name: rabbitmq
    alias: brokerService
    version: 12.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: brokerService.enabled
  - name: seaweedfs
    alias: storageservice
    version: 3.59.4
    repository: https://seaweedfs.github.io/seaweedfs/helm
    condition: storageservice.enabled
