components:
  schemas: {}
externalDocs:
  description: Sourcecode Documentation
  url: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
info:
  contact:
    email: andreas.rauber@tuwien.ac.at
    name: Prof. Andreas Rauber
  description: Service that analyses data structures
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: Database Repository Analyse Service API
  version: dbrepo-latest
openapi: 3.0.0
paths:
  /api/analyse/determinedt:
    post:
      consumes:
        - application/json
      description: This is a simple API which returns the datatypes of a (path) csv
        file
      parameters:
        - description: to-do description
          in: body
          name: body
          required: true
          schema:
            properties:
              enum:
                example: true
                type: boolean
              enum_tol:
                example: 0.1
              filename:
                example: sample.csv
                type: string
              separator:
                example: ','
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
      summary: Determine datatypes
      tags:
        - analyse-endpoint
  /api/analyse/determinepk:
    post:
      consumes:
        - application/json
      description: This is a simple API which returns the primary keys + ranking of
        a (path) csv file
      parameters:
        - description: to-do description
          in: body
          name: body
          required: true
          schema:
            properties:
              filepath:
                example: /data/testdt08.csv
                type: string
              seperator:
                example: ','
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
      summary: Determine primary keys
      tags:
        - analyse-endpoint
  /api/analyse/determinestat:
    post:
      operationId: determinestat
      requestBody:
        content:
          application/json:
            schema:
              properties:
                database_id:
                  example: 1
                  type: integer
                table_id:
                  example: 1
                  type: integer
              required:
                - database_id
                - table_id
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: Analysed statistical properties
                    type: string
                  status:
                    example: '200'
                    type: integer
                required:
                  - message
                  - status
                type: object
          description: Determined statistics
        '400':
          description: Invalid input
          ontent:
            application/json:
              schema:
                properties:
                  message:
                    example: Analysed statistical properties
                    type: string
                  status:
                    example: '200'
                    type: integer
                required:
                  - message
                  - status
                type: object
      summary: Determine statistics
      tags:
        - analyse-endpoint
  /api/analyse/determinestats:
    post:
      operationId: determinestats
      requestBody:
        content:
          application/json:
            schema:
              properties:
                filepath:
                  example: file.csv
                  type: string
                separator:
                  example: ','
                  type: string
              required:
                - filepath
                - separator
              type: object
      responses:
        '200':
          description: Determined statistics
        '400':
          description: Invalid input
      summary: Determine statistics
      tags:
        - analyse-endpoint
  /health:
    get:
      consumes:
        - application/json
      description: This is a simple API which checks if the application is healthy
      parameters:
        - description: to-do description
          in: body
          name: body
          required: true
          schema:
            properties:
              status:
                example: UP
                type: string
            type: object
      produces:
        - application/json
      responses:
        '200':
          description: OK
      summary: Check if application is running
      tags:
        - health-endpoint
servers:
  - description: Generated server url
    url: http://localhost:5000
  - description: Sandbox
    url: https://test.dbrepo.tuwien.ac.at
