components:
  schemas:
    DataTypesDto:
      properties:
        columns:
          $ref: '#/components/schemas/SuggestedColumnDto'
        line_termination:
          example: "\r\n"
          type: string
        separator:
          example: ','
          type: string
      type: object
    DetermineDataTypesDto:
      properties:
        enum:
          example: false
          type: boolean
        enum_tol:
          example: 0.01
          type: double
        filename:
          example: s3-key-from-seaweedfs
          type: string
        separator:
          example: ','
          type: string
      required:
        - filename
        - separator
      type: object
    ErrorDto:
      properties:
        message:
          example: Message
          type: string
        success:
          example: false
          type: boolean
      type: object
    KeysDto:
      properties:
        keys:
          items:
            properties:
              column_name:
                format: int64
                type: integer
          type: array
      required:
        - keys
      type: object
    Stats:
      properties:
        mean:
          example: '0.3'
          type: float
        median:
          example: '0.45'
          type: float
        std_dev:
          example: '0.12'
          type: float
        val_max:
          example: '1.0'
          type: float
        val_min:
          example: '0.0'
          type: float
      type: object
    SuggestedColumnDto:
      properties:
        column_name:
          type: string
      type: object
    TableStats:
      properties:
        columns:
          properties:
            column_name:
              $ref: '#/components/schemas/Stats'
          type: object
      required:
        - columns
      type: object
externalDocs:
  description: Sourcecode Documentation
  url: https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services
info:
  contact:
    email: andreas.rauber@tuwien.ac.at
    name: Prof. Andreas Rauber
  description: Service that analyses data structures
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: Database Repository Analyse Service API
  version: __APPVERSION__
openapi: 3.0.0
paths:
  /api/analyse/database/{database_id}/table/{table_id}/statistics:
    get:
      operationId: determine_table_stat
      parameters:
        - example: 1
          in: path
          name: database_id
          required: true
          schema:
            format: int64
            type: integer
        - example: 1
          in: path
          name: table_id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableStats'
          description: Determined statistics
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Missing parameters
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Table not found
      summary: Determine table statistics
      tags:
        - analyse-endpoint
  /api/analyse/datatypes:
    get:
      consumes:
        - application/json
      description: This is a simple API which returns the datatypes of a (path) csv
        file
      parameters:
        - example: filename_s3_key
          in: query
          name: filename
          required: true
          schema:
            type: string
        - example: ','
          in: query
          name: separator
          required: true
          schema:
            type: string
        - example: 'false'
          in: query
          name: enum
          required: false
          schema:
            type: boolean
        - example: '2.5'
          in: query
          name: enum_tol
          required: false
          schema:
            type: float
      produces:
        - application/json
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataTypesDto'
          description: Determined data types successfully
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Failed to determine data types
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Failed to find file in Storage Service
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Unexpected system error
      summary: Determine datatypes
      tags:
        - analyse-endpoint
  /api/analyse/keys:
    get:
      consumes:
        - application/json
      description: This is a simple API which returns the primary keys + ranking of
        a (path) csv file
      parameters:
        - example: filename_s3_key
          in: query
          name: filename
          required: true
          schema:
            type: string
        - example: ','
          in: query
          name: separator
          required: true
          schema:
            type: string
      produces:
        - application/json
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeysDto'
          description: Determined keys successfully
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Failed to determine keys
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Failed to find file in Storage Service or is empty
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Unexpected system error
      summary: Determine primary keys
      tags:
        - analyse-endpoint
  /health:
    get:
      consumes:
        - application/json
      description: This is a simple API which checks if the application is healthy
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            properties:
              status:
                example: UP
                type: string
            type: object
      summary: Check if application is running
      tags:
        - health-endpoint
servers:
  - description: Generated server url
    url: http://localhost:5000
  - description: Sandbox
    url: https://test.dbrepo.tuwien.ac.at
