# coding: utf-8

"""
    units

    powered by Flasgger  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UnitsSavecolumnsconceptBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cdbid': 'int',
        'cid': 'int',
        'tid': 'int',
        'uri': 'str'
    }

    attribute_map = {
        'cdbid': 'cdbid',
        'cid': 'cid',
        'tid': 'tid',
        'uri': 'uri'
    }

    def __init__(self, cdbid=None, cid=None, tid=None, uri=None):  # noqa: E501
        """UnitsSavecolumnsconceptBody - a model defined in Swagger"""  # noqa: E501
        self._cdbid = None
        self._cid = None
        self._tid = None
        self._uri = None
        self.discriminator = None
        if cdbid is not None:
            self.cdbid = cdbid
        if cid is not None:
            self.cid = cid
        if tid is not None:
            self.tid = tid
        if uri is not None:
            self.uri = uri

    @property
    def cdbid(self):
        """Gets the cdbid of this UnitsSavecolumnsconceptBody.  # noqa: E501


        :return: The cdbid of this UnitsSavecolumnsconceptBody.  # noqa: E501
        :rtype: int
        """
        return self._cdbid

    @cdbid.setter
    def cdbid(self, cdbid):
        """Sets the cdbid of this UnitsSavecolumnsconceptBody.


        :param cdbid: The cdbid of this UnitsSavecolumnsconceptBody.  # noqa: E501
        :type: int
        """

        self._cdbid = cdbid

    @property
    def cid(self):
        """Gets the cid of this UnitsSavecolumnsconceptBody.  # noqa: E501


        :return: The cid of this UnitsSavecolumnsconceptBody.  # noqa: E501
        :rtype: int
        """
        return self._cid

    @cid.setter
    def cid(self, cid):
        """Sets the cid of this UnitsSavecolumnsconceptBody.


        :param cid: The cid of this UnitsSavecolumnsconceptBody.  # noqa: E501
        :type: int
        """

        self._cid = cid

    @property
    def tid(self):
        """Gets the tid of this UnitsSavecolumnsconceptBody.  # noqa: E501


        :return: The tid of this UnitsSavecolumnsconceptBody.  # noqa: E501
        :rtype: int
        """
        return self._tid

    @tid.setter
    def tid(self, tid):
        """Sets the tid of this UnitsSavecolumnsconceptBody.


        :param tid: The tid of this UnitsSavecolumnsconceptBody.  # noqa: E501
        :type: int
        """

        self._tid = tid

    @property
    def uri(self):
        """Gets the uri of this UnitsSavecolumnsconceptBody.  # noqa: E501


        :return: The uri of this UnitsSavecolumnsconceptBody.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this UnitsSavecolumnsconceptBody.


        :param uri: The uri of this UnitsSavecolumnsconceptBody.  # noqa: E501
        :type: str
        """

        self._uri = uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UnitsSavecolumnsconceptBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnitsSavecolumnsconceptBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
